[core]
name:Ek_snake
displayText:Змей
displayDescription:-Очень быстрый\n-Одиночная атака\n-Сложен в управлении
price:0, cash=25000
maxHp:1500
mass:3000
buildSpeed:70s
techLevel:2
radius:25
displayRadius:40
isBio:false
softCollisionOnAll:0
fogOfWarSightRange:20
builtFrom_1_name:landFactory
builtFrom_1_pos:10.019
energyMax:40
energyRegen:0.1
energyNeedsToRechargeToFull:true
transportSlotsNeeded:1
[graphics]
total_frames:1
image:snake.png
image_turret:snake-turret.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
teamColorsOnTurret:true
scaleImagesTo:50
scaleTurretImagesTo:30
movementEffect:CUSTOM:EkRotorwash,CUSTOM:EkRotordust
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:16
turretTurnSpeed:2
maxAttackRange:140
shootDelay:0.05s
aimOffsetSpread:0.25
[turret_1]
x:0
y:-9
idleDir:0
turnSpeed:1.5
turnSpeedAcceleration:0.5
canShoot:false
[turret_2]
x:10
y:17
size:0
invisible:true
attachedTo:1
slave:true
projectile:1
chargeEffectImage:gauss_charge_small.png
#energyUsage:1
delay:170
shoot_sound_vol:15
shoot_sound:前摇并开火.ogg
limitingAngle:30
[turret_3]
x:-10
y:17
invisible:true
copyFrom:2
[projectile_1]
delayedStartTimer:24
life:20
instant:true
beamImage:SHARED:beam3.png
beamImageEnd:SHARED:beam1_end.png
beamImageStart:SHARED:beam1_start.png
beamImageOffsetRate:2
largeHitEffect:true
color:#63e6e8
directDamage:250
moveWithParent:true
[movement]
movementType:HOVER
moveSpeed:1.25
moveAccelerationSpeed: 0.3
moveDecelerationSpeed: 0.3
maxTurnSpeed:1.5
turnAcceleration: 1
#note: joinsGroupFormations=false could case slowdowns for groups of non-flying units
joinsGroupFormations:false
moveSlidingMode:false
moveIgnoringBody:false
moveSlidingDir:35
targetHeightDrift:1
targetHeight:2
[effect_EkRotorwash]
image:rotorwash.png
createWhenOverLand:false
life:40
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:2
scaleFrom:0.25
scaleTo:1.5
alpha:0.5
drawUnderUnits:true
hOffset:-5
dirOffsetRandom:180
dirSpeedRandom:0.6
atmospheric:true
[effect_EkRotordust]
image:rotorwash.png
createWhenOverLiquid:false
life:40
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:2
scaleFrom:0.25
scaleTo:1.5
alpha:1
color:#916C5B
drawUnderUnits:true
hOffset:-5
dirOffsetRandom:180
dirSpeedRandom:0.6
atmospheric:true