[core]
name: flameEffect
price: 0
buildSpeed: 5s
maxHp: 1000
class: CustomUnitMetadata
mass: 99999999
techLevel: 1
radius: 16
isBug: false
isBio: false
disableAllUnitCollisions: true
showInEditor: false
experimental: false
isUnrepairableUnit: true
disableDeathOnZeroHp: true
autoTriggerCooldownTime:60
autoTriggerCooldownTime_allowDangerousHighCPU: true
canNotBeDirectlyAttacked: true
isUnselectable:true
showOnMinimap:false
ignoreInUnitCapCalculation: true

[hiddenAction_transferKill]
autoTriggerOnEvent: killedAnyUnit
takeResources: indirectKills=-1
takeResources_includeReference: customTarget1
takeResources_discardCollected: true

[hiddenAction_remove]
autoTrigger: if self.timeAlive > 15 or self.isOverWater
deleteSelf: true

[hiddenAction_new]
requireConditional: if not self.isOverWater
playSoundAtUnit: ROOT:assets/sounds/fire_2000.ogg : 0.06
autoTriggerOnEvent: created
#autoTrigger: if not self.hasParent()
setBodyRotation: -90

[hiddenAction_fireLoop]
playSoundAtUnit: ROOT:assets/sounds/fire_2000.ogg : 0.06
autoTrigger: if self.timeAlive > 5 and self.timeAlive < 6 or self.timeAlive > 10 and self.timeAlive < 11

[hiddenAction_areaDenial]
requireConditional: if not self.isOverWater
autoTrigger: true
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 0,0


[graphics]
icon_zoomed_out_neverShow: true
drawLayer:experimentals
total_frames: 25
frame_width: 64
frame_height: 97
animation_idle_start: 0
animation_idle_end: 24
animation_idle_speed: 2
image: flame_loop.png
image_back: crater.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE

[attack]
canAttackLandUnits: false
canAttack: false
canAttackFlyingUnits: false
canAttackUnderwaterUnits: false
turretSize: 0
turretTurnSpeed: 6
aimOffsetSpread: 0
maxAttackRange: 0
shootDelay: 1

[turret_1]
#
x: 0
y: 0
turnSpeed: 999
invisible: true
turnSpeedAcceleration: 999
projectile: 1

[projectile_1]
explodeEffect: shockwave,fire*2,fire2*2,smoke*2
life: 0
speed: 0
areaDamage: 15
areaRadius: 50
image: SHARED:blank.png
explodeOnEndOfLife: true
shieldDefectionMultiplier: 0

[effect_shockwave]
life: 30
drawUnderUnits: true
fadeOut: true
scaleFrom: 0.1
scaleTo: 0.4
dirOffsetRandom: 360
image: ROOT:assets/graphicsEffects/wave2.png
alpha: 1
attachedToUnit: false

[effect_fire]
attachedToUnit: false
life: 150

image: ROOT:assets/graphicsEffects/flame.png

xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10

dirOffsetRandom: 180

xSpeedRelative: 0.4
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.3
hSpeed: 0.2
hSpeedRandom: 0.1
hOffset: 3
hOffsetRandom: 1

dirSpeedRandom: 1

fadeInTime: 13

delayedStartTimer: 7

atmospheric: true

drawUnderUnits: false

createWhenOverLiquid: false

alpha: 0.5

scaleFrom: 0.1
scaleTo: 1
color: #CCFFFF
priority: veryhigh

[effect_fire2]
attachedToUnit: false
life: 100

image: ROOT:assets/graphicsEffects/flame.png

xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10

dirOffsetRandom: 180

xSpeedRelative: -0.4
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.3
hSpeed: 0.2
hSpeedRandom: 0.1
hOffset: 3
hOffsetRandom: 1

dirSpeedRandom: 1

fadeInTime: 13

delayedStartTimer: 7

atmospheric: true

drawUnderUnits: false

createWhenOverLiquid: false

alpha: 0.5

scaleFrom: 0.1
scaleTo: 1
color: #CCFFFF
priority: critical

[effect_smoke]
#priority:high

frameIndex: 0
stripIndex: smoke_black

#spawnChance: 1

createWhenZoomedOut: false

life: 300
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF

fadeInTime:2
scaleFrom: 1
scaleTo: 2
alpha: 2
drawUnderUnits:false
liveAfterAttachedDies: false
hOffset: 20
hSpeed:0.2

dirOffsetRandom:180
xSpeedRelativeRandom: 0.4


atmospheric: true

[movement]
movementType:BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
targetHeight: 0
maxTurnSpeed: 0
turnAcceleration: 0
ignoreMoveOrders: true
