[core]


name:Ek_EXP_flak_mech
displayText:Arrakis
displayDescription:-Experimental AA-Flak mech\n-Great to any air targets Even is a airship or a Swarm of small one\n-4 heavy flaks guns\n-Slow and shielded
displayText_zh:阿拉基斯机甲
displayDescription_zh:实验型高射炮防空机甲\n强力攻击任何空中目标甚至可以击落空中战舰\n四门重型高射炮\n缓慢且自带护盾系统\n机载雷达
price:70000,experimental=3000
maxHp:5000
mass:90000
techLevel:1
experimental:true
buildSpeed:60s
fogOfWarSightRange:34
numBitsOnDeath:20
explodeTypeOnDeath:largeUnit
radius:42
displayRadius:50
softCollisionOnAll:0
maxShield:5000
shieldRegen:0.20
shieldDisplayOnlyDeflection:true
shieldDeflectionDisplayRate:4096
shieldRenderRadius:1
armour:15
tags:radar,detect,Experimental
builtFrom_1_name:experimentalLandFactory
builtFrom_1_pos:10.008
transportSlotsNeeded:5
[graphics]
drawLayer:experimentals
total_frames:1
image:flak_mech_bottem.png
image_wreak:NONE
image_turret:flak_mech_top.png
lock_shadow_rotation_with_main_turret:true
image_shadow:SHADOW:flak_mech_top.png
shadowOffsetX:2
shadowOffsetY:2
teamColorsOnTurret:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:false
canAttackUnderwaterUnits:false
turretSize:20
turretTurnSpeed:2
maxAttackRange:600
setMainTurretAs:1
turretRotateWithBody:false
aimOffsetSpread:0
[turret_barral_L_1]
x:-15.5
y:20
image:lionheart_Gun_barrel_A.png
shouldResetTurret:true
attachedTo:1
slave:true
size:20
projectile:2
shoot_sound:flak fire.ogg
shoot_sound_vol:0.36
shoot_flame:shockwave,CUSTOM:EkMuzzleTiny,CUSTOM:fire smoke
shoot_light:#FFFF2211
canShoot:true
recoilOffset:-8
recoilOutTime:8
recoilReturnTime:80
delay:115
[turret_barral_L_2]
@copyFromSection:turret_barral_L_1
x:-12
delay:110
[turret_barral_R_1]
@copyFromSection:turret_barral_L_1
x:12
delay:105
[turret_barral_R_2]
@copyFromSection:turret_barral_L_1
x:15.5
delay:100
[turret_1]
invisible:false
x:0
y:0
size:14
idleDir:0
turnSpeed:3
turnSpeedAcceleration:0.1
canShoot:false
[turret_dish]
x:0
y:-33
image:dish_2.png
size:0
attachedTo:1
idleDir:0
idleSpin:3
canShoot:false
[projectile_2]
life:100
speed:25
directDamage:100
areaDamage:400
areaRadius:100
explodeOnEndOfLife:true
explodeEffect:CUSTOM:Cannon effect1
frame:11
color:#FFDDDD
drawSize:1.2
largeHitEffect:true
lightColor:#FFFF2211
lightSize:0.9
tags:EKAmmo
trailEffect:CUSTOM:trail
trailEffectRate:0.7
[effect_EkMuzzleTiny]
life:8
attachedToUnit:true
image:muzzle_tiny.png
total_frames:3
animateFrameStart:0
animateFrameEnd:2
animateFrameSpeed:0.5
fadeOut:false
yOffsetRelative:0
xOffsetRelative:0
[effect_Cannon effect1]
alsoPlaySound:ROOT:ASSETS/sounds/cannon_shoot.ogg
image:ROOT:ASSETS/graphicsEffects/explosion_flak2.png
life:160
total_frames:18
animateFrameStart:0
animateFrameEnd:18
animateFrameSpeed:0.4
fadeOut:false
scaleFrom:1
scaleTo:1
yOffsetRelative:0
xOffsetRelative:5
[effect_trail]
createWhenZoomedOut:false
priority:low
xOffsetRelative:0
yOffsetRelative:0
image:trail_A.png
life:50
fadeOut:true
attachedToUnit:false
fadeInTime:1
scaleFrom:2.0
scaleTo:2.0
alpha:0.5
drawUnderUnits:true
ySpeedRelative:0.3
[effect_fire smoke]
#priorityhigh
frameIndex:0
stripIndex:effects
spawnChance:1
createWhenZoomedOut:false
image:blackSmoke1.png
life:80
fadeOut:true
attachedToUnit:false
color:#FFA817
fadeInTime:10
scaleFrom:1
scaleTo:1.5
alpha:0.8
drawUnderUnits:false
liveAfterAttachedDies:false
hSpeed:0.2
dirOffsetRandom:180
ySpeedRelativeRandom:0.6
xSpeedRelativeRandom:0.7
atmospheric:true
[leg_1]
x:-20
y:20
attach_x:-5
attach_y:10
moveSpeed:1.6
rotateSpeed:4
heightSpeed:0.6
resetAngle:25
image_leg:kingSman_leg.png
image_foot:kingSman_foot.png
image_foot_shadow:SHADOW:kingSman_foot.png
holdDisMin:0
holdDisMax:24
[leg_2]
x:20
y:20
attach_x:5
attach_y:10
copyFrom:1
[leg_3]
x:-20
y:-20
attach_x:-5
attach_y:-10
copyFrom:1
[leg_4]
x:20
y:-20
attach_x:5
attach_y:-10
copyFrom:1

[movement]
movementType:OVER_CLIFF
moveSpeed:0.65
moveAccelerationSpeed:0.07
moveDecelerationSpeed:0.17
maxTurnSpeed:1.5
turnAcceleration:0.025
moveSlidingMode:false
moveIgnoringBody:true
reverseSpeedPercentage:1
slowDeathFall:true