[core]

copyFrom: laboratoryt2.ini
name:Eklaboratoryt3
displayText_ru: Лаборатория Т3
displayText:Laboratory T3
displayDescription:-Высокотехнологичный комплекс, преобразующий нестабильный Кристаллин в чистый Экспериментал\n-Внутри его реакторов минерал подвергается интенсивному нагреву и электромагнитной стабилизации, выбрасывая излишки энергии в виде ослепительных вспышек\n-Требует значительного количества электроэнергии и бережного контроля — ошибка в процессе может привести к катастрофическому взрыву
price:75000
maxHp:3000
mass:9000
radius:50
nukeOnDeath:true
nukeOnDeathRange:250
nukeOnDeathDamage:3500
nukeOnDeathDisableWhenNoNuke:false
explodeTypeOnDeath:verylargeBuilding
numBitsOnDeath:35
autoTriggerCooldownTime:40
[action_autoBuild]
#autoTriggerOnEvent:created
text: Recursive build
text_zh: 循环建造
text_ru: Авто переработка
description:-Автоматически запускает новый цикл переработки\n-Работает только если достаточно ресурсов
description_zh:-自动将完成的项目重新加入队列
#description_ru:-Автоматически перерабатывает кристаллы
isVisible: if memory.recursiveBuild == false
buildSpeed: 0.5s
pos: 100
highPriorityQueue: true
setUnitMemory: recursiveBuild = true
iconImage: other_recursion.png
ai_isDisabled: true
[action_upgrade]
isVisible: false
[action_noAutoBuild]
text: Single build
text_zh: 单次建造
text_ru: Выкл. авто переработку
description:-Build queue will behave as normal
description_zh:-建造队列将正常表现
description_ru:-Автоматически перерабатывает кристаллы
isVisible: if memory.recursiveBuild == true
pos: 100
highPriorityQueue: true
setUnitMemory: recursiveBuild = false
iconImage: ${action_autoBuild.iconImage}
iconExtraImage: ability_no.png
ai_isDisabled: true
buildSpeed: 0.5s
[graphics]
total_frames:1
image:baset3.png
image_wreak:base_dead.png
image_shadow:NONE
shadowOffsetX:1
shadowOffsetY:1
[animation_idle]
KeyframeTimeScale:0.33
onActions:idle
arm1_0s:{alpha:0.6}
arm1_1.5s:{alpha:0.9}
arm1_2.6s:{alpha:0.8}
arm1_3.9s:{alpha:0.6}
[arm_1]
x:-22
y:-27
image_end:SHARED:glow_green.png
drawOverBody:true
[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
[movement]
movementType:OVER_CLIFF
moveSpeed:0
maxTurnSpeed:0
[ai]
upgradedFrom:Eklaboratory