[core]
name: EkZombieSpawner
class: CustomUnitMetadata
displayText:Споры зомби
displayDescription: -Очаг зомби-вируса\n-Очень опасный вирус!
price: 80000
maxHp: 99999
mass: 0
buildSpeed:0s
isUnselectable: true
canNotBeDirectlyAttacked: true
canNotBeDamaged: true
disableAllUnitCollisions: true
showOnMinimap: false
energyMax: 1
energyStartingPercentage: 1
energyRegen: 0
dieOnZeroEnergy:true
techLevel: 1
transportSlotsNeeded: 0
footprint: 0,0,0,0
constructionFootprint: 0,0,0,0
radius: 0
displayRadius: 0
isBio: false
isBuilding: true
softCollisionOnAll: 0
stayNeutral: true
createNeutral: true
explodeOnDeath: false
explodeOnDeathGroundCollision: false
# onNewMapSpawn: mapCenter_asNeutral

[hiddenAction_spawner]
autoTrigger: if not self.isEnergyEmpty
fireTurretXAtGround: 1
addEnergy: -0.01

[turret_1]
x: 0
y: 0
canShoot: false
projectile: 1

[projectile_1]
life: 999
deflectionPower: -1
directDamage: 0
targetGround: true
targetGroundSpread: 270
instant: true
areaRadius: 0
areaDamage: 0
explodeOnEndOfLife: false
largeHitEffect: false
spawnUnit: EkZombieMeleeSmall

[graphics]
image: ROOT:ASSETS/null.png
imageScale: 0.22

[attack]
canAttack: false

[movement]
movementType: NONE