[core]
name: cyberstanCC
copyFrom: ROOT:assets/templates/T1engineer.ini
displayText: Киберстан
class:             CustomUnitMetadata
techLevel:1
price:10000
maxHp:10000
mass:9000
buildSpeed:150s
radius:59
isBio:false
isBuilding:true
energyMax:1
energyRegen:0.0001
energyNeedsToRechargeToFull: true
autoRepair:true
nanoRange:400
nanoRepairSpeed:0.6
nanoBuildSpeed:8
canRepairBuildings:true
canRepairUnits:true
selfRegenRate:0.05
generation_credits: 25
softCollisionOnAll: 5
footprint:-3,-2,3,3
reclaimPrice:0
constructionFootprint:-3,-2,3,3
exit_x:-8
exit_y:50
tags: commandCenter
@global level: 1

[action_showLore]
@copyFromSection: template_showLoreAction
description: Киберстан — фракция, основанная на принципах кибернетики и искусственного интеллекта. После распада Империи, группа учёных и инженеров объединилась, чтобы создать киборгов. Все эти 4 тысячелетия абсолютно все граждане Киберстана активно интегрировали кибернетические импланты, улучшая свои физические и ментальные способности. В итоге в них ничего не осталось от человеческого.\nИдеология: Социализм и технологический прогресс. Киберстан стремится к совершенствованию человеческой расы через технологии, видя в этом путь к преодолению биологических ограничений и обеспечению бессмертия, а также равенству.\nВоенные силы: Высокотехнологичные кибернетические войска, автономные боевые единицы и искусственный интеллект командования. Основные единицы — усиленные солдаты с имплантами и роботизированные экзоскелеты.\nОсобенности: Развитая научная база, передовые исследования в области ИИ и кибернетики. Экономика основана на производстве высокотехнологичных устройств и кибернетических компонентов.

[action_upgrade]
@copyFromSection: template_buildingUpgrade
price:325000
text: Улучшить до Т2
isVisible: if ${level} == 1
description: -Ускоренное строительство\n-Больше здоровья
buildSpeed: 30s
convertTo: cyberstanCCT2
ai_isHighPriority: true

[canBuild_1]
name:doggidoggiBuilder, scout, EkmegaBuilder, setRally
pos:1

#[canBuild_2]
#name: extractor,c_turret_t1, c_antiAirTurret, landFactory, airFactory, EkInfantryFactoryT1, mechFactory,EkSupportFactory, EkHelipad, EkResourceDrill,EkTech,experimentalLandFactory, EkHarvesterSolar, seaFactory
#pos:2

[action_showPowersToPlayer]
@copyFromSection: template_showMenuAction
@define menuID:101
text: Силы
isVisible: true

[template_baseSuperPowerAction]
@define menuID: 1
isVisible: if memory.currentMenu == ${menuID} 

[template_powersAction]
@define menuID:101
isVisible:if memory.currentMenu == ${menuID}
pos:1.01

[action_summonBlackHole]
@copyFromSection: template_powersAction
iconImage: ROOT:assets/ui/action_icons/area_shock.png
isLocked:if ${level} == 1
isLockedMessage:Улучшите базу до второго уровня
price:energy=0.5
text:Вызвать черную дыру
pos: 1.01
buildSpeed: 0.8s
highPriorityQueue: true
canPlayerCancel:false
refundAllQueuedItems:true
fireTurretXAtGround:2

[action_propaganda1]
@copyFromSection: template_powersAction
iconImage: ROOT:assets/ui/action_icons/area_shock.png
price:energy=1
text:Пропаганда
pos: 1.01
alsoTriggerAction:1
buildSpeed: 0.8s
highPriorityQueue: true
refundAllQueuedItems:true

[action_propaganda2]
@copyFromSection: template_powersAction
iconImage: ROOT:assets/ui/action_icons/area_shock.png
price:energy=1
text:Пропаганда
pos: 1.01
alsoTriggerAction:2
buildSpeed: 0.8s
highPriorityQueue: true
refundAllQueuedItems:true

[action_propaganda3]
@copyFromSection: template_powersAction
iconImage: ROOT:assets/ui/action_icons/area_shock.png
price:energy=1
text:Пропаганда
pos: 1.01
alsoTriggerAction:3
buildSpeed: 0.8s
highPriorityQueue: true
refundAllQueuedItems:true

[hiddenAction_1]
showQuickWarLogToAllPlayers:[ПЛАНЕТАРНОЕ ПРЕДУПРЕЖДЕНИЕ] СДАВАЙСЯ! ОЧЕНЬ ХОРОШАЯ ИДЕЯ - ПОКИНУТЬ ТОНУЩИЙ КОРАБЛЬ. ТЫ ЖЕ ЗНАЕШЬ, ЧТО НЕ СМОЖЕШЬ ВЫИГРАТЬ ЭТУ ВОЙНУ.
playSoundGlobally:ROOT:assets/sounds/event_warning2.wav

[hiddenAction_2]
showQuickWarLogToAllPlayers:[ПЛАНЕТАРНОЕ ПРЕДУПРЕЖДЕНИЕ] ТВОИ СОЮЗНИКИ ТЕБЯ БРОСИЛИ. ОНИ ОСТАВИЛИ ТЕБЯ УМИРАТЬ. НЕ ДОВЕРЯЙ ИМ. ОНИ СОЛГАЛИ ТЕБЕ, ТЫ ЖЕ ЗНАЕШЬ, ЧТО НЕ СМОЖЕШЬ ВЫИГРАТЬ ЭТУ ВОЙНУ.
playSoundGlobally:ROOT:assets/sounds/event_warning2.wav

[hiddenAction_3]
showQuickWarLogToAllPlayers:[ПЛАНЕТАРНОЕ ПРЕДУПРЕЖДЕНИЕ] КИБЕРСТАН НЕ ПАДЕТ. КИБЕРСТАН НЕ СДАСТСЯ. КИБЕРСТАН ПОБЕДИТ. ТЫ НЕ МОЖЕШЬ ВЫИГРАТЬ ЭТУ ВОЙНУ.
playSoundGlobally:ROOT:assets/sounds/event_warning2.wav

[graphics]
image:        body.png
image_shadow: NONE
image_wreak:  dead.png
shadowOffsetX:1
shadowOffsetY:1
rotate_with_direction:false

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:16
turretTurnSpeed:4
maxAttackRange:400
shootDelay:70
aimOffsetSpread:0.25

[turret_nano]
x:55
y:40
idleDir:-60
turnSpeed:0.5
size:27
image:excelsior_crane.png
canShoot:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
isMainNanoTurret:true

[turret_1]
x: 0
y: 0
shoot_sound:missile_fire
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC
shouldResetTurret: false
idleSpin: 0
recoilOffset:    -3
recoilOutTime:    6
recoilReturnTime: 12
projectile:1

[turret_2]
x: 0
y: 0
projectile:2
canAttackFlyingUnits:false
canAttackLandUnits:false

[projectile_1]
life: 690
speed: 0.6
targetSpeed: 14
trailEffect: true
largeHitEffect: true
ballistic: true
ballistic_delaymove_height: 40
ballistic_height: 60
frame: 4
areaDamage: 120
areaRadius: 75
autoTargetingOnDeadTarget: true

[projectile_2]
directDamage: 0
life: 900
speed: 100
spawnUnit:black_hole
image: NONE


[movement]
movementType:NONE
moveSpeed:0
moveAccelerationSpeed:0.01
moveDecelerationSpeed:0.01
maxTurnSpeed:0
turnAcceleration:0.1
