
[core]

showInEditor:false
name:礼花
displayDescription:NONE
class: CustomUnitMetadata
price: 0
maxHp: 10000000
mass: 999999
tags=magic
disableAllUnitCollisions:  true
isUnselectable:true
ignoreInUnitCapCalculation: true
isBuilder:true
canNotBeDirectlyAttacked:true
techLevel: 2
buildSpeed: 1s
#availableInDemo: true
radius: 1
displayRadius: 1
isBio: false
softCollisionOnAll: 0
hideScorchMark:true
effectOnDeath:NONE
[action_triggerSpawn]
autoTrigger:if self.energy(empty=true)
isVisible:false
fireTurretXAtGround:1
fireTurretXAtGround_withOffset:0,0
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
dieOnAttack:true
[turret_1]
x:0
y:0
warmup:8s
projectile:大和炮1
turnSpeedAcceleration:1.0
canShoot:true
recoilOffset:-2
[projectile_大和炮1]
life:600
areaRadius:150
areaDamage:3000
color:#FFFFFF
speed:50
image:Yamato Cannon.png
deflectionPower:-1
trailEffect:CUSTOM:projectileTrail*3
explodeEffect:CUSTOM:特效2,CUSTOM:闪看看,CUSTOM:特效1,CUSTOM:弹坑*1,CUSTOM:projectileWaterSmoke*3,CUSTOM:projectileWaterSplash*3,CUSTOM:projectileFlash
areaHitAirAndLandAtSameTime:true
spawnUnit:大震
areaDamageNoFalloff:true
spawnProjectilesOnExplode:大和炮2
[projectile_大和炮2]
@copyFromSection:projectile_大和炮1
areaRadius:100
areaIgnoreUnitsCloserThan:50
areaDamageNoFalloff:false
explodeEffect:NONE
spawnUnit:NONE
spawnProjectilesOnExplode:NONE
[effect_projectileFlash]
image:SHARED:light_50.png
life:30
fadeOut:true
attachedToUnit:false
color:#FFC08D
fadeInTime:2
scaleFrom:3.5
scaleTo:2.5
alpha:1
drawUnderUnits:false
atmospheric:false
hOffset:5
yOffsetAbsolute:-10
[effect_projectileWaterSmoke]
createWhenOverLand:false
life:360
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:5
scaleFrom:1.5
scaleTo:8
alpha:0.8
drawUnderUnits:false
hSpeed:0.2
hOffsetRandom:0.15
atmospheric:true
dirOffsetRandom:180
shadow:true
xOffsetRelativeRandom:32
yOffsetRelativeRandom:32
xSpeedAbsoluteRandom:0.3
ySpeedAbsoluteRandom:0.3
[effect_projectileTrail]
image:trail_ring.png
life:20
fadeOut:true
fadeInTime:1
scaleFrom:0.5
scaleTo:1.75
alpha:1
drawUnderUnits:false
attachedToUnit:false
yOffsetRelative:10
dirOffsetRandom:1
atmospheric:true
[effect_projectileWaterSplash]
image:sub_bubbles.png
createWhenOverLand:false
life:120
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:5
scaleFrom:1
scaleTo:4
alpha:1
drawUnderUnits:false
hSpeed:1
hOffsetRandom:0.3
atmospheric:true
dirOffsetRandom:180
physics:true
physicsGravity:0.1
xOffsetRelativeRandom:16
yOffsetRelativeRandom:16
xSpeedAbsoluteRandom:0.8
ySpeedAbsoluteRandom:0.8
[effect_弹坑]
life:6000
showInFog:true
scaleTo:3
scaleFrom:3
priority:critical
physics:true
dirOffsetRandom:360
image:弹坑.png
createWhenOffscreen:true
alwayStartDirAtZero:true
drawUnderUnits:true
[effect_特效1]
life:60000
showInFog:true
priority:critical
physics:true
dirOffsetRandom:360
alsoPlaySound:爆炸音效.ogg
lifeRandom:30
image:blackSmoke1.png
createWhenOffscreen:true
alwayStartDirAtZero:true
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
ySpeedAbsoluteRandom:0.4
ySpeedAbsolute:0.5
xSpeedAbsoluteRandom:0.4
xSpeedAbsolute:0.5
drawUnderUnits:true
[effect_闪看看]
life: 20
image: 闪光.png
drawUnderUnits:true
scaleTo:15
scaleFrom:15
[effect_特效2]
life:600
alsoPlaySound:爆炸音效.ogg
showInFog:true
priority:critical
dirOffsetRandom:360
lifeRandom:30
image:FX_Smoke2.png
ySpeedRelativeRandom:0.5
ySpeedRelative:0.5
xSpeedRelativeRandom:0.5
xSpeedRelative:0
[graphics]
total_frames: 1
#imageScale: 0.8
image:       透明.png
image_wreak:  NONE
image_turret: NONE
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.0
moveDecelerationSpeed: 0.0

maxTurnSpeed: 0.0
turnAcceleration: 0.0

moveSlidingMode :false
moveIgnoringBody:false

[ai]
disableUse:true