[core]
name: flameEffectSmall
price:0, cash=0
buildSpeed: 5s
maxHp: 1000
class: CustomUnitMetadata
mass: 99999999
techLevel: 1
radius: 16
isBug: false
isBio: false
disableAllUnitCollisions: true
showInEditor: false
experimental: false
isUnrepairableUnit: true
disableDeathOnZeroHp: true
autoTriggerCooldownTime:1
autoTriggerCooldownTime_allowDangerousHighCPU: true
canNotBeDirectlyAttacked: true
isUnselectable:true
showOnMinimap:false
ignoreInUnitCapCalculation: true

[hiddenAction_transferKill]
autoTriggerOnEvent: killedAnyUnit
takeResources: indirectKills=-1
takeResources_includeReference: customTarget1
takeResources_discardCollected: true

[hiddenAction_remove]
autoTrigger: if self.timeAlive > self.ammo or self.isOverWater or self.timeAlive > 1 and customTarget2.hp < 1
deleteSelf: true

[hiddenAction_new]
requireConditional: if not self.isOverWater and distanceBetween(self,nearestUnit(relation="enemy")) < 45
autoTriggerOnEvent: created
setCustomTarget2: nearestUnit(relation="enemy")
setHeight: customTarget2.height

[hiddenAction_hpDenial]
requireConditional: if not self.isOverWater
autoTrigger: if customTarget2.hp > 0 and self.customTimer > 1
takeResources: hp=20
takeResources_includeReference: customTarget2
spawnEffects: fire*2,fire2*2,smoke*2
resetCustomTimer: true
takeResources_excludeUnitsWithoutAllResources: false
alsoTriggerAction: transferKill
alsoTriggerOrQueueActionConditional: if customTarget2.hp < 1

[hiddenAction_1]
autoTrigger: if distanceBetween(customTarget2, self) > 1
teleportTo: customTarget2
setHeight: customTarget2.height

[decal_burningIcon]
layer: beforeUI
#shadow
basePosition: customTarget2
image: ROOT:assets/ui/ui.customIcons.burning_icon.png
imageScale: 0.15
alpha: select((self.timeAlive % 2) - 1 < 0, -1 * ((self.timeAlive % 2) - 1), (self.timeAlive % 2) - 1 ) * 0.2 + 0.15
alwaysStartDirAtZero:true


[graphics]
drawLayer: experimentals 
icon_zoomed_out_neverShow: true
total_frames: 1
image: SHARED:blank.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE

[attack]
canAttackLandUnits: false
canAttack: false
canAttackFlyingUnits: false
canAttackUnderwaterUnits: false
turretSize: 0
turretTurnSpeed: 6
aimOffsetSpread: 0
maxAttackRange: 0
shootDelay: 1


[effect_fire]
attachedToUnit: false
life: 150

image: ROOT:assets/graphicsEffects/flame.png

xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10

dirOffsetRandom: 180

xSpeedRelative: 0.4
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.3
hSpeed: 0.2
hSpeedRandom: 0.1
hOffset: 3
hOffsetRandom: 1

dirSpeedRandom: 1

fadeInTime: 13

delayedStartTimer: 7

atmospheric: true

drawUnderUnits: false

createWhenOverLiquid: false

alpha: 0.5

scaleFrom: 0.1
scaleTo: 1
color: #CCFFFF
priority: veryhigh

[effect_fire2]
attachedToUnit: false
life: 100

image: ROOT:assets/graphicsEffects/flame.png

xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10

dirOffsetRandom: 180

xSpeedRelative: -0.4
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.3
hSpeed: 0.2
hSpeedRandom: 0.1
hOffset: 3
hOffsetRandom: 1

dirSpeedRandom: 1

fadeInTime: 13

delayedStartTimer: 7

atmospheric: true

drawUnderUnits: false

createWhenOverLiquid: false

alpha: 0.5

scaleFrom: 0.1
scaleTo: 1
color: #CCFFFF
priority: critical

[effect_smoke]
#priority:high

frameIndex: 0
stripIndex: smoke_black

#spawnChance: 1

createWhenZoomedOut: false

life: 300
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF

fadeInTime:2
scaleFrom: 1
scaleTo: 2
alpha: 2
drawUnderUnits:false
liveAfterAttachedDies: false
hSpeed:0.2

dirOffsetRandom:180
xSpeedRelativeRandom: 0.4


atmospheric: true

[movement]
movementType: BUILDING 
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
targetHeight: 0
maxTurnSpeed: 0
turnAcceleration: 0
ignoreMoveOrders: true
