#Dragonfly by Essential Strategy

[core]
copyFrom:ROOT:ASSETS/templates/bio.template
name: dragonfly
class: CustomUnitMetadata
price: ccredits=2000, crystalline=500
maxHp: 350
mass: 1300
displayText: Dragonfly
displayText_es: Libélula
displayDescription: -Flame attack\n-Attacks ground only\n-Self regenerate
displayDescription_es: -Ataque de fuego\n-Ataca a tierra únicamente\n-Auto-regeneración
techLevel: 2
buildSpeed: 0.0009
#availableInDemo: true
radius: 14
isBio: true
isUnrepairableUnit: true
selfRegenRate:0.1
softCollisionOnAll: 12
energyMax: 8
energyRegen: 0.006
energyNeedsToRechargeToFull: true
isBug: true
numBitsOnDeath: 4
explodeOnDeath: false
explodeOnDeathGroundCollosion: false


[graphics]
total_frames: 2
#imageScale: 1.1
image:        dragonfly.png
image_wreak:  dragonfly_dead.png
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 1
animation_moving_pingPong: true
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 2
animation_idle_pingPong: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
aimOffsetSpread: 0
isFixedFiring: true
turretSize: 20
turretTurnSpeed: 9
maxAttackRange: 170
shootDelay: 5

[turret_1]
x: 0
y: 0
invisible: true
projectile: 1
shoot_flame:small
shoot_light: #ffcc0000
canShoot: true
energyUsage: 0.1

[projectile_1]
life: 70
speed: 5
speedSpread: 1.5
frame: 3
flameWeapon: true
hitSound: false
targetGround:true
targetGroundSpread: 25
buildingDamageMultiplier: 0.5
deflectionPower: -1
areaDamage: 14
areaRadius: 60
lightColor: #ea9642
lightSize: 1.2

[movement]
movementType: AIR
moveSpeed: 3
moveAccelerationSpeed: 0.04
moveDecelerationSpeed: 0.08
maxTurnSpeed: 6
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

#Dragonfly by Essential Strategy