[core]
name:EZRG_RailgunTarget
tags: ${core.name}
mass: 0
price: 0
maxHp: 1
radius: 0
showOnMinimap: false
isUnselectable: true
isUnselectableAsTarget: false
canNotBeDirectlyAttacked: false
disableDeathOnZeroHp: true
disableAllUnitCollisions: true
#canOnlyBeAttackedByUnitsWithTags: EZRG_Railgun
showInEditor: false
ignoreInUnitCapCalculation: true
fogOfWarSightRange: 0
createOnAggressiveTeam: true
energyMax: 2
energyRegen: -1
dieOnZeroEnergy: true
explodeOnDeath: false

[graphics]
image: SHARED:debug_marker.png
disableLowHpFire: true
disableLowHpSmoke: true
showTransportBar: false
showHealthBar: false
showEnergyBar: false
showShieldBar: false
showQueueBar: false
showShotDelayBar: false
showSelectionIndicator: false
#isVisible: false

[attack]
canAttack: false

[movement]
movementType: land

[ai]
#notPassivelyTargetedByOtherUnits: true