[core]


name:EkWildcatHelicopter
displayText:Дикая кошка
mass:1200
price:5000
maxHp:3500
maxShield: 500
shieldRegen: 0.2
shieldDisplayOnlyDeflection: true
shieldRenderRadius:33
radius:16
showInEditor:false
tags:WildcatHelicopter
disableAllUnitCollisions:true
autoTriggerCooldownTime:0
autoTriggerCooldownTime_allowDangerousHighCPU:true
@memory missile1:float
@memory missile2:float
@memory torpedo1:float
@memory torpedo2:float

[graphics]
image:SHARED:blank.png
#imageScale:0.55
image_wreak:snowcat_dead.png
image_shield:shield.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
movementEffect:CUSTOM:EkRotorwash,CUSTOM:EkRotordust
movementEffectRate:8
lock_body_rotation_with_main_turret: true

[decal_body]
layer: afterBody
image: Wildcat_helicopter2.png
onlyWhileAlive: true
teamColors: true
imageScale: ((self.height)/34*0.5+0.5)
order: -1

[decal_bodyShadow]
layer: shadow
image: SHADOW:Wildcat_helicopter2.png
onlyWhileAlive: true
teamColors: true
imageScale: ((self.height)/34*0.5+0.5)
order: -1
yOffsetAbsolute: self.height
alpha:0.3/((self.height)/34*0.5+0.5)

[decal_blade]
layer: afterBody
order: 0.1
image:helicopter_blades.png
total_frames: 1
onlyWithZoomLevelOrMore:0
teamColors: true
basePosition: self.getOffsetRelative(y=2*((self.height)/34*0.5+0.5)).getOffsetRelative(dirOffset=self.timeAlive*select(self.hasParent,1000,2000))
imageScale: 1.1*((self.height)/34*0.5+0.5)
alpha:1.0
isVisible:if self.hp>1 or self.height>1

[decal_missile_rack1]
layer: beforeBody
order: 0.1
image:missile_rack.png
total_frames: 6
frame:self.readUnitMemory('missile1',type='float')
#yOffsetAbsolute:1*((self.height)/34*0.5+0.5)
onlyWithZoomLevelOrMore:0
alwayStartDirAtZero:false
alpha:1.0
isVisible:if self.hp>0 and self.tags(includes='m1')
basePosition: self.getOffsetRelative(y=3*((self.height)/34*0.5+0.5),x=-15*((self.height)/34*0.5+0.5))
imageScale: ((self.height)/34*0.5+0.5)

[decal_missile_rack2]
layer: beforeBody
order: 0.1
image:missile_rack.png
total_frames: 6
frame:self.readUnitMemory('missile2',type='float')
onlyWithZoomLevelOrMore:0
alwayStartDirAtZero:false
basePosition: self.getOffsetRelative(y=3*((self.height)/34*0.5+0.5),x=15*((self.height)/34*0.5+0.5))
imageScale: ((self.height)/34*0.5+0.5)
alpha:1.0
isVisible:if self.hp>0 and self.tags(includes='m2')

[decal_torpedo1]
layer: beforeBody
order: 0.1
image:torpedo_rack.png
total_frames: 3
frame:self.readUnitMemory('torpedo1',type='float')
onlyWithZoomLevelOrMore:0
alwayStartDirAtZero:false
basePosition: self.getOffsetRelative(y=5*((self.height)/34*0.5+0.5),x=-15*((self.height)/34*0.5+0.5))
imageScale: ((self.height)/34*0.5+0.5)
alpha:1.0
isVisible:if self.hp>0 and self.tags(includes='t1')

[decal_torpedo2]
layer: beforeBody
order: 0.1
image:torpedo_rack.png
total_frames: 3
frame:self.readUnitMemory('torpedo2',type='float')
onlyWithZoomLevelOrMore:0
alwayStartDirAtZero:false
basePosition: self.getOffsetRelative(y=5*((self.height)/34*0.5+0.5),x=15*((self.height)/34*0.5+0.5))
imageScale: ((self.height)/34*0.5+0.5)
alpha:1.0
isVisible:if self.hp>0 and self.tags(includes='t2')

[movement]
movementType:AIR
targetHeight: 32
targetHeightDrift: 2
reverseSpeedPercentage: 0.1
moveSpeed: 1.5
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.01
maxTurnSpeed: 3.0
turnAcceleration: 0.4
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:30

[attack]
canAttack:true
canAttackLandUnits:true
canAttackFlyingUnits:true
canAttackUnderwaterUnits:true
maxAttackRange:220
aimOffsetSpread:0
isFixedFiring:true
disablePassiveTargeting:true

[hiddenAction_created]
autoTriggerOnEvent:created
requireConditional:if self.customTarget1==null
setCustomTarget1:parent

[hiddenAction_created2]
autoTriggerOnEvent:created
setUnitMemory:missile1=5,missile2=5
temporarilyAddTags:m1,m2

[hiddenAction_attack1]
autoTrigger:if self.parent.attacking!=null and self.readUnitMemory('missile1',type='float')>4 and self.readUnitMemory('missile2',type='float')>4 and self.parent.attacking.height>-1 and self.readUnitMemory('torpedo1',type='float')<1 and self.readUnitMemory('torpedo2',type='float')<1 and parent.readUnitMemory('stopFly',type='bool')!=true
addWaypoint_type:attack
addWaypoint_target_fromReference:parent.attacking
addWaypoint_target_nearestUnit_team:enemy

[hiddenAction_attack2]
autoTrigger:if self.parent.attacking!=null and self.readUnitMemory('torpedo1',type='float')>1 and self.readUnitMemory('torpedo2',type='float')>1 and self.parent.attacking.isOverLiquid and self.readUnitMemory('missile1',type='float')<1 and self.readUnitMemory('missile2',type='float')<1 and parent.readUnitMemory('stopFly',type='bool')!=true
addWaypoint_type:attack
addWaypoint_target_fromReference:parent.attacking
addWaypoint_target_nearestUnit_team:enemy

[hiddenAction_attack3]
autoTrigger:if self.parent.attacking!=null and self.readUnitMemory('torpedo1',type='float')>1 and self.readUnitMemory('missile2',type='float')>4 and self.parent.attacking.height>-1 and parent.readUnitMemory('stopFly',type='bool')!=true
addWaypoint_type:attack
addWaypoint_target_fromReference:parent.attacking
addWaypoint_target_nearestUnit_team:enemy

[hiddenAction_attack4]
autoTrigger:if self.parent.attacking!=null and self.readUnitMemory('torpedo2',type='float')>1 and self.readUnitMemory('missile1',type='float')>4 and self.parent.attacking.height>-1 and parent.readUnitMemory('stopFly',type='bool')!=true
addWaypoint_type:attack
addWaypoint_target_fromReference:parent.attacking
addWaypoint_target_nearestUnit_team:enemy

[hiddenAction_loadInto]
autoTrigger:if self.parent.attacking==null and not self.hasActiveWaypoint(type='attack')
addWaypoint_type:loadInto
addWaypoint_target_fromReference:customTarget1
addWaypoint_target_nearestUnit_team:own

[hiddenAction_stopAttack1]
autoTrigger:if self.readUnitMemory('missile1',type='float')<1 and self.readUnitMemory('missile2',type='float')<1 and self.activeWaypointTarget==attacking and self.tags(includes='m1') and self.tags(includes='m2')
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_stopAttack2]
autoTrigger:if self.readUnitMemory('torpedo1',type='float')<1 and self.readUnitMemory('torpedo2',type='float')<1 and self.activeWaypointTarget==attacking and self.tags(includes='t1') and self.tags(includes='t2')
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_stopAttack3]
autoTrigger:if self.readUnitMemory('torpedo1',type='float')>0 and self.readUnitMemory('missile2',type='float')<1 and self.activeWaypointTarget==attacking and self.tags(includes='t1') and self.tags(includes='m2') and attacking.height>-1
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_stopAttack4]
autoTrigger:if self.readUnitMemory('torpedo1',type='float')<1 and self.readUnitMemory('missile2',type='float')>0 and self.activeWaypointTarget==attacking and self.tags(includes='t1') and self.tags(includes='m2') and attacking.isOverLiquid
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_stopAttack5]
autoTrigger:if self.readUnitMemory('torpedo1',type='float')<1 and self.readUnitMemory('missile2',type='float')<1 and self.activeWaypointTarget==attacking and self.tags(includes='t1') and self.tags(includes='m2')
clearActiveWaypoint:true
alsoTriggerAction:loadInto


[hiddenAction_stopAttack6]
autoTrigger:if self.readUnitMemory('torpedo2',type='float')>0 and self.readUnitMemory('missile1',type='float')<1 and self.activeWaypointTarget==attacking and self.tags(includes='t2') and self.tags(includes='m1') and attacking.height>-1
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_stopAttack7]
autoTrigger:if self.readUnitMemory('torpedo2',type='float')<1 and self.readUnitMemory('missile1',type='float')>0 and self.activeWaypointTarget==attacking and self.tags(includes='t2') and self.tags(includes='m1') and attacking.isOverLiquid
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_stopAttack8]
autoTrigger:if self.readUnitMemory('torpedo2',type='float')<1 and self.readUnitMemory('missile1',type='float')<1 and self.activeWaypointTarget==attacking and self.tags(includes='t2') and self.tags(includes='m1')
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_reload_ready1]
autoTrigger:if self.readUnitMemory('missile1',type='float')<5 and self.queueSize<1 and self.hasParent and self.tags(includes='m1')
alsoQueueAction:reload1

[hiddenAction_reload1]
buildSpeed:0.5s
setUnitMemory:missile1=memory.missile1+1

[hiddenAction_reload_ready2]
autoTrigger:if self.readUnitMemory('missile2',type='float')<5 and self.queueSize<1 and self.hasParent and self.tags(includes='m2')
alsoQueueAction:reload2

[hiddenAction_reload2]
buildSpeed:0.5s
setUnitMemory:missile2=memory.missile2+1

[hiddenAction_reload_ready3]
autoTrigger:if self.readUnitMemory('torpedo1',type='float')<2 and self.queueSize<1 and self.hasParent and self.tags(includes='t1')
alsoQueueAction:reload3

[hiddenAction_reload3]
buildSpeed:0.5s
setUnitMemory:torpedo1=memory.torpedo1+1

[hiddenAction_reload_ready4]
autoTrigger:if self.readUnitMemory('torpedo2',type='float')<2 and self.queueSize<1 and self.hasParent and self.tags(includes='t2')
alsoQueueAction:reload4

[hiddenAction_reload4]
buildSpeed:0.5s
setUnitMemory:torpedo2=memory.torpedo2+1

[hiddenAction_ForceAttack]
autoTriggerOnEvent:newMessage(withTag="forceAttack")
addWaypoint_type:attack
addWaypoint_target_fromReference:parent.attacking
addWaypoint_target_nearestUnit_team:enemy

[hiddenAction_switch1]
autoTriggerOnEvent:newMessage(withTag="switch1")
temporarilyAddTags:t1
temporarilyRemoveTags:m1
setUnitMemory:missile1=0
requireConditional:if not self.tags(includes='t1')

[hiddenAction_switch2]
autoTriggerOnEvent:newMessage(withTag="switch2")
temporarilyAddTags:t2
temporarilyRemoveTags:m2
setUnitMemory:missile2=0
requireConditional:if not self.tags(includes='t2')

[hiddenAction_switch3]
autoTriggerOnEvent:newMessage(withTag="switch3")
temporarilyAddTags:m1
temporarilyRemoveTags:t1
setUnitMemory:torpedo1=0
requireConditional:if not self.tags(includes='m1')

[hiddenAction_switch4]
autoTriggerOnEvent:newMessage(withTag="switch4")
temporarilyAddTags:m2
temporarilyRemoveTags:t2
setUnitMemory:torpedo2=0
requireConditional:if not self.tags(includes='m2')

[hiddenAction_die]
autoTrigger:if self.customTarget1==null and self.timeAlive(laterThanSeconds=5)
addResources:hp=-999999

[hiddenAction_forceRetuen]
autoTriggerOnEvent:newMessage(withTag="forceReturn")
clearActiveWaypoint:true
alsoTriggerAction:loadInto

[hiddenAction_death]
autoTriggerOnEvent:destroyed
sendMessageTo:unitref customTarget1
sendMessageWithTags:shit

[turret_1]
x: 0
y: 0
canShoot: true
idleDir:0
image:SHARED:blank.png
shouldResetTurret: false
projectile:NULL
shoot_flame:NONE
recoilOffset:0
recoilOutTime:0
recoilReturnTime: 0
turnSpeed:3.0
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits: true
aimOffsetSpread:0

[turret_m1]
x: -15
y: 3
canShoot: true
idleDir:0
image:SHARED:blank.png
shouldResetTurret: false
projectile:missile_I
shoot_flame:NONE
shoot_sound:fire_missile.ogg
shoot_sound_vol:0.25
recoilOffset:0
recoilOutTime:0
recoilReturnTime: 0
turnSpeed:10.0
delay:0.1s
warmup:0.15s
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits: false
canAttackCondition:if self.readUnitMemory('missile1',type='float')>0 and self.tags(includes='m1')
aimOffsetSpread:0
slave:true
attachedTo: 1
onShoot_triggerActions:mr1

[hiddenAction_mr1]
setUnitMemory:missile1=memory.missile1-1

[turret_m2]
x: 15
y: 3
canShoot: true
idleDir:0
image:SHARED:blank.png
shouldResetTurret: false
projectile:missile_I
shoot_flame:NONE
shoot_sound:fire_missile.ogg
shoot_sound_vol:0.25
recoilOffset:0
recoilOutTime:0
recoilReturnTime: 0
turnSpeed:10.0
delay:0.1s
warmup:0.2s
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits: false
canAttackCondition:if self.readUnitMemory('missile2',type='float')>0 and self.tags(includes='m2')
aimOffsetSpread:0
slave:true
attachedTo: 1
onShoot_triggerActions:mr2

[hiddenAction_mr2]
setUnitMemory:missile2=memory.missile2-1

[turret_2]
x: 0
y: 0
canShoot: true
idleDir:0
image:SHARED:blank.png
shouldResetTurret: false
projectile:NULL
shoot_flame:NONE
recoilOffset:0
recoilOutTime:0
recoilReturnTime: 0
turnSpeed:3.0
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits: true
aimOffsetSpread:0

[turret_t1]
x: -15
y: 5
canShoot: true
idleDir:0
image:SHARED:blank.png
shouldResetTurret: false
projectile:torpedo_I
shoot_flame:NONE
shoot_sound:launch_torpedo.ogg
shoot_sound_vol:0.25
recoilOffset:0
recoilOutTime:0
recoilReturnTime: 0
turnSpeed:10.0
delay:0.1s
warmup:0.2s
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits: true
canAttackCondition:if self.readUnitMemory('torpedo1',type='float')>0 and self.tags(includes='t1') and attacking.isOverLiquid
aimOffsetSpread:0
slave:true
attachedTo: 2
onShoot_triggerActions:tr1

[hiddenAction_tr1]
setUnitMemory:torpedo1=memory.torpedo1-1

[turret_t2]
x: 15
y: 5
canShoot: true
idleDir:0
image:SHARED:blank.png
shouldResetTurret: false
projectile:torpedo_I
shoot_flame:NONE
shoot_sound:launch_torpedo.ogg
shoot_sound_vol:0.25
recoilOffset:0
recoilOutTime:0
recoilReturnTime: 0
turnSpeed:10.0
delay:0.1s
warmup:0.4s
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits: true
canAttackCondition:if self.readUnitMemory('torpedo2',type='float')>0 and self.tags(includes='t2') and attacking.isOverLiquid
aimOffsetSpread:0
slave:true
attachedTo: 2
onShoot_triggerActions:tr2

[hiddenAction_tr2]
setUnitMemory:torpedo2=memory.torpedo2-1

[projectile_missile_I]
areaDamage:0
areaRadius:55
life:5
image:missile.png
shadowImage:SHADOW:missile.png
drawSize:1
speed:0
explodeOnEndOfLife:true
explodeEffect:NONE
explodeEffectOnShield:NONE
initialUnguidedSpeedHeight:-0.25
gravity:0.5
ballistic: true
ballistic_delaymove_height:-15
ballistic_height:-80
spawnProjectilesOnExplode:missile_II(maxSpawnLimit=1,recursionLimit=3)
drawUnderUnits: true

[projectile_missile_II]
areaDamage:0
areaRadius:55
life:10
lightColor: #FF5D00
lightSize: 0.6
image:missile.png
shadowImage:SHADOW:missile.png
drawSize: 1
speed:-0.8
targetSpeed:0
explodeOnEndOfLife:true
explodeEffect:NONE
explodeEffectOnShield:NONE
gravity:0.5
initialUnguidedSpeedHeight:-0.5
spawnProjectilesOnExplode:missile_III(maxSpawnLimit=1,recursionLimit=3)
drawUnderUnits: true

[projectile_missile_III]
areaDamage:0
areaRadius:0
life:5
trailEffect:true
lightColor: #FF5D00
lightSize: 0.6
image:missile.png
shadowImage:SHADOW:missile.png
drawSize: 1
speed:8
explodeOnEndOfLife:true
explodeEffect:NONE
explodeEffectOnShield:NONE
autoTargetingOnDeadTarget: false
wobbleAmplitude: 0.8
wobbleFrequency: 0.1s
drawUnderUnits: true
spawnProjectilesOnExplode:missile_IV(maxSpawnLimit=1,recursionLimit=3)

[projectile_missile_IV]
areaDamage:80
areaRadius:35
life:600
trailEffect:true
trailEffectRate:0.8
lightColor: #FF5D00
lightSize: 0.6
image:missile.png
shadowImage:SHADOW:missile.png
drawSize: 1
speed:8
explodeOnEndOfLife:true
autoTargetingOnDeadTarget: false
wobbleAmplitude: 1.4
wobbleFrequency: 0.1s
explodeEffect:CUSTOM:shockwave,CUSTOM:explode,CUSTOM:light

[projectile_torpedo_I]
directDamage:0
life:5
image:torpedo.png
shadowImage:SHADOW:torpedo.png
drawSize:1
speed:0
lightColor: #ffff00
lightSize: 0.4
explodeOnEndOfLife:true
explodeEffect:NONE
explodeEffectOnShield:NONE
initialUnguidedSpeedHeight:-0.25
gravity:0.5
ballistic: true
ballistic_delaymove_height:-30
ballistic_height:-100
spawnProjectilesOnExplode:torpedo_II(maxSpawnLimit=1,recursionLimit=3)
drawUnderUnits: true

[projectile_torpedo_II]
directDamage:0
life:20
lightColor: #ffff00
lightSize: 0.4
image:torpedo.png
shadowImage:SHADOW:torpedo.png
drawSize: 1
speed:0
targetSpeed:0
explodeOnEndOfLife:true
explodeEffect:CUSTOM:displacement_ripples,CUSTOM:ripples*3,CUSTOM:largeRipples
gravity:1.5
ballistic: true
ballistic_delaymove_height:-30
ballistic_height:-100
spawnProjectilesOnExplode:torpedo_III(maxSpawnLimit=1,recursionLimit=3)
drawUnderUnits: true

[projectile_torpedo_III]
areaDamage:400
areaRadius:75
life: 30
speed: 2.2
targetSpeed: 4.0
targetSpeedAcceleration: 0.05
drawSize: 1
trailEffect: true
largeHitEffect: true
deflectionPower: -1
wobbleAmplitude: 0.2
wobbleFrequency: 0.2s
turnSpeed:2
explodeEffect:CUSTOM:explode2,CUSTOM:ripples*3,CUSTOM:largeRipples
explodeEffectOnShield:CUSTOM:explode2,CUSTOM:ripples*3,CUSTOM:largeRipples
image:torpedo_alpha.png
lightColor: #ffff00
lightSize: 0.4
drawUnderUnits: true
spawnProjectilesOnEndOfLife: torpedoLocked(maxSpawnLimit=1,recursionLimit=3)

[projectile_torpedoLocked]
@copyFromSection: projectile_torpedo_III
life: 300
turnSpeed:6
spawnProjectilesOnEndOfLife: NONE
autoTargetingOnDeadTarget: true

[effect_explode]
life: 30
dirOffsetRandom:180
priority:veryhigh
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 1.05
image:explode.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha:0.9

[effect_explode2]
life: 30
dirOffsetRandom:180
priority:veryhigh
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo:0.9
image:explode.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha:0.9
alsoPlaySound:torpedo_explosion.ogg:0.7

[effect_light]
life: 15
priority: high
scaleFrom: 3.0
scaleTo: 1.0
fadeOut: true
attachedToUnit: false
image:SHARED:light_50.png
drawUnderUnits:false
alpha:0.35
color:#ff9000

[effect_shockwave]
life: 30
priority: high
dirOffsetRandom:360
dirSpeedRandom: 5
scaleFrom: 0.3
scaleTo: 2.8
fadeInTime:5
fadeOut: true
attachedToUnit: false
image:shockwave.png
drawUnderUnits: false
alpha:0.35

[effect_EkRotorwash]
image:rotorwash.png
createWhenOverLand:false
life:30
spawnChance:1
fadeOut:true
attachedToUnit:true
fadeInTime:2
scaleFrom:0.25
scaleTo:1.5
alpha:0.5
drawUnderUnits:true
hOffset:-40
dirOffsetRandom:180
dirSpeedRandom:0.6
atmospheric:true

[effect_EkRotordust]
image:rotorwash.png
createWhenOverLiquid:false
life:30
spawnChance:1
fadeOut:true
attachedToUnit:true
fadeInTime:2
scaleFrom:0.25
scaleTo:1.5
alpha:1.0
color:#916C5B
drawUnderUnits:true
hOffset:-40
dirOffsetRandom:180
dirSpeedRandom:0.6
atmospheric:true

[effect_displacement_ripples]
#displacement type ignored if postprocessing is not enabled
drawType: displacement
image: SHARED:ripple_normal_128.png
life: 60
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
liveAfterAttachedDies:true
scaleFrom: 0.15
scaleTo: 0.9
alpha: 0.1
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 1

[effect_ripples]
image: SHARED:ripple.png
life: 60
lifeRandom: 20
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
liveAfterAttachedDies:true
scaleFrom: 0.15
scaleTo: 0.75
alpha: 0.6
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5

[effect_largeRipples]
image: SHARED:ripple.png
life: 40
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.35
scaleTo: 0.85
alpha: 0.7
liveAfterAttachedDies:true
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5