[core]
showInEditor:false

name: vultureOrbitSistem
displayText: F
displayDescription: Flare

price: 0
maxHp: 1
mass: 0
radius: 0

#isBuilding: true
tags:vultureOrbitSistem
isUnselectable:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
disableAllUnitCollisions:true
showOnMinimap:false
autoTriggerCooldownTime:0.1s
techLevel: 1
ignoreInUnitCapCalculation: true

[graphics]
image:       SHARED:blank.png
icon_zoomed_out_neverShow: true



[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false



[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.4
joinsGroupFormations: false
#reverseSpeedPercentage: 1
maxTurnSpeed: 0.5
turnAcceleration: 100

moveSlidingMode :false
moveIgnoringBody:false
