[core]
showInEditor:false

name: vultureOrbitSistem2
displayText: F
displayDescription: Flare

price:0, cash=0
maxHp: 1
mass: 0
radius: 0

#isBuilding: true

isUnselectable:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
disableAllUnitCollisions:true
showOnMinimap:false
autoTriggerCooldownTime:0.1s
techLevel: 1
transportUnitsRequireTag: vultureOrbitSistem
maxTransportingUnits: 999
transportUnitsCanUnloadUnits: false
ignoreInUnitCapCalculation: true

[attachment_orbit]
x: 20
y: 240
isUnselectable: true
addTransportedUnits: true
resetRotationWhenNotAttacking: true
idleDir: 0
height: 0
setDrawLayerOnBottom: false
canAttack: true
deattachIfWantingToMove: true
canBeAttackedAndDamaged: true
smoothlyBlendPositionWhenExistingUnitAdded: false

[hiddenAction_change]
autoTrigger: if customTarget1.hasFlag(id=1)
convertTo: altVultureOrbitSistem2

[hiddenAction_1]
autoTrigger: if distanceBetween(customTarget1.attacking, self) > 1
teleportTo: customTarget1.attacking

[hiddenAction_2]
addWaypoint_type:move
addWaypoint_target_fromReference: self.attachment(slot="orbit")
addWaypoint_prepend:true
autoTrigger: true
clearAllWaypoints: true

[hiddenAction_3]
deleteSelf: true
autoTrigger: if not customTarget1.isAttacking and self.customTimer(withinSeconds=2) or customTarget1.hasActiveWaypoint(type="attack") and customTarget1.activeWaypointTarget != attacking and self.resource(type="check", greaterThan=5)

[hiddenAction_4]
autoTrigger: if customTarget1.isAttacking
resetCustomTimer: true

[hiddenAction_check]
autoTrigger: if customTarget1.hasActiveWaypoint(type="attack") and customTarget1.activeWaypointTarget != attacking
addResources: check=1

[hiddenAction_checkReset]
autoTrigger: if self.resource(type='check', greaterThan=0) and customTarget1.hasActiveWaypoint(type="attack") and customTarget1.activeWaypointTarget != attacking
resourceAmount: check
resourceAmount_setValue: 0

[resource_check]
hidden: true

[graphics]
icon_zoomed_out_neverShow: true
image:       SHARED:blank.png
showTransportBar: false



[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
shootDelay: 1
maxAttackRange: 270

[turret_nothing]
#

x: 0

y: 0

turnSpeed: 999

invisible: true

turnSpeedAcceleration: 999

projectile: nothing

canShoot: true

canAttackLandUnits: false

canAttackFlyingUnits: false

[projectile_nothing]

life: 0
explodeEffect: NONE
speed: 0
directDamage: 0
image: SHARED:blank.png

[movement]
movementType: AIR
moveSpeed: 0
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.4
joinsGroupFormations: false
#reverseSpeedPercentage: 1
maxTurnSpeed: 0.24
turnAcceleration: 100

moveSlidingMode :false
moveIgnoringBody:false
