[core]

name:Ekbattlecruiser
displayText:Battlecruiser
displayText_zh:战列巡洋舰
displayDescription:-Flight manual\n-The main ship that can attack air and ground units\n-Six ATA air-to-air laser gun groups and six ATS air-to-ground laser gun groups \n-These huge heavy warships are simply flying fortresses, built to maintain peace and control of the Copeland region \n-The laser gun group and heavy steel armor make these spectacular warships one of the most powerful weapons in the universe.
displayDescription_zh:-可以攻击空中和地面单位的主力舰\n-六门ATA空对空激光炮组与六门ATS空对地激光炮组\n-激光炮组和厚重的精钢装甲让这些壮观的战舰成为了宇宙中最强大的武器之一\n-这些巨大的重型战舰简直是飞行的堡垒，他们为了维持科普卢星区的和平以及统治制空权而造\n-可使用毁灭性的等离子炮轰击目标
class:CustomUnitMetadata
price:250000,alloys=10000
maxHp:10000
maxShield:15000
shieldRegen:0.5
armour:5
mass:6500000
experimental:true
techLevel:2
buildSpeed:150s
radius:120
uiTargetRadius:60
isBio:false
energyMax:1800
energyRegen:1
fogOfWarSightRange:45
displayRadius:120
tags:Airship
@memory blinktarget:unit
#@memory blinktarget:unit
[graphics]
total_frames:8
image:Battlecruiser 2.png
image_wreak:Battlecruiser dead.png
image_shadow:auto
shadowOffsetX:2
shadowOffsetY:2
animation_moving_start:0
animation_moving_end:7
animation_moving_speed:0.07
teamColorsOnTurret:true
movementEffect:CUSTOM:EkJetfire
movementEffectRate:2
icon_zoomed_out:Battlecruiser icon.png
[attack]
setMainTurretAs:大和炮
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:0
turretTurnSpeed:4
maxAttackRange:500
shootDelay:60
aimOffsetSpread:0.4
turretMultiTargeting:true

[action_blink]
whenBuilding_cannotMove:true
whenBuilding_rotateTo_waitTillRotated:true
whenBuilding_rotateTo_aimAtActionTarget:true
fireTurretXAtGround:blink
fireTurretXAtGround_withProjectile:none
text:Jump module startup
text_zh:跃迁模块启动
displayType:action
buildSpeed:1s
pos:0
highPriorityQueue:true
allowMultipleInQueue:false
playSoundAtUnit:跃迁.ogg
alsoTriggerAction:blink3
setUnitMemory:blinktarget=thisActionTarget
price:energy=900
[hiddenAction_blink2]
buildSpeed:3s
tags:blinking
highPriorityQueue:true
whenBuilding_temporarilyConvertTo:Ekbattlecruiser blinking
fireTurretXAtGround:blink
fireTurretXAtGround_withProjectile:blink
fireTurretXAtGround_withTarget:memory.blinktarget
addActionCooldownTime:60s
addActionCooldownApplyToActions:blink
spawnEffects:CUSTOM:blinkFlash,CUSTOM:blinkGlow,虚化2,爆散,爆旋

[effect_爆散]
priority:veryhigh
image:Hit1.png
life:20
fadeOut:false
attachedToUnit:false
scaleFrom:1.0
scaleTo:1.0
alpha:1.0
dirOffsetRandom:180
drawUnderUnits:false
total_frames:4
animateFrameStart:0
animateFrameEnd:3
animateFrameSpeed:0.2
alsoPlaySound:HLT_explode.ogg:0.4

[effect_爆旋]
priority:veryhigh
image:rotorwash.png
life:40
fadeOut:true
attachedToUnit:false
color:#00ff80
scaleFrom:1.0
scaleTo:2.5
alpha:0.9
drawUnderUnits:false
dirOffsetRandom:180
dirSpeedRandom:0.2
[effect_虚化2]
priority:high
image:SHARED:cone_inverted_normal_128.png
life:45
fadeOut:true
attachedToUnit:false
fadeInTime:15
scaleFrom:4
scaleTo:4
alpha:0.8
drawUnderUnits:true
liveAfterAttachedDies:true
dirOffset:0
xOffsetAbsoluteRandom:0.3
yOffsetAbsoluteRandom:0.3
atmospheric:true
delayedStartTimer:10
drawType:displacement
dirSpeed:6
[effect_虚化]
priority:high
image:SHARED:cone_inverted_normal_128.png
life:45
fadeOut:true
attachedToUnit:false
fadeInTime:15
scaleFrom:4
scaleTo:4
alpha:0.8
drawUnderUnits:true
liveAfterAttachedDies:true
dirOffset:180
xOffsetAbsoluteRandom:0.3
yOffsetAbsoluteRandom:0.3
atmospheric:true

drawType:displacement
dirSpeed:6

[hiddenAction_blink3]
clearAllWaypoints:true
addWaypoint_type:move
addWaypoint_target_fromReference:memory.blinktarget
alsoQueueAction:blink2
[turret_礼花]
x:0
y:0
projectile:礼花
size:1
turnSpeed:15
canShoot:false
invisible:true
[turret_blink]
x:0
y:0
canShoot:false
invisible:true
size:1
turnSpeed:99999
limitingRange:1400
limitingMinRange:180
[turret_blink1]
x:0
y:0
canShoot:false
invisible:true
size:1
canAttackMaxAngle:120
turnSpeed:99999
limitingRange:800
limitingMinRange:180
limitingAngle:60
projectile:10
[projectile_none]
instant:true
directDamage:0
life:9999
speed:12
targetGround:true
[projectile_10]
instant:true
directDamage:0
life:9999
speed:12
targetGround:true
spawnUnit:礼花(spawnChance=1,maxSpawnLimit=1,skipIfOverlapping=false)
[projectile_blink]
teleportSource:true
instant:true
directDamage:0
life:9999
speed:12
targetGround:true
deflectionPower:-1
shouldRevealFog:true
explodeEffect:CUSTOM:blinkFlash,CUSTOM:blinkGlow,虚化
effectOnCreate:CUSTOM:blinkFlash,CUSTOM:blinkGlow
[effect_blinkFlash]
priority:high
image:SHARED:light_50.png
life:78
fadeOut:true
attachedToUnit:false
color:#07eef2
scaleFrom:8.5
scaleTo:5.5
alpha:0.8
drawUnderUnits:false

[effect_blinkGlow]
priority:high
image:SHARED:light_50.png
life:148
fadeOut:true
attachedToUnit:false
color:#07eef2
scaleFrom:4.6
scaleTo:10.5
alpha:0.5
drawUnderUnits:false

[projectile_礼花]
directDamage:0
life:60
deflectionPower:-1
spawnUnit:礼花(alwayStartDirAtZero=true)
instant:true
[action_abl1]
#玩家操作
whenBuilding_rotateTo_waitTillRotated:true
whenBuilding_rotateTo_aimAtActionTarget:true
fireTurretXAtGround:blink1
fireTurretXAtGround_withProjectile:none
text:Yamato Cannon Charging
text_zh:大和炮充能
description:Use destructive plasma cannons to bombard targets
description_zh:使用毁灭性的等离子炮轰击目标
displayType:upgrade
buildSpeed:0.1s
highPriorityQueue:true
canPlayerCancel:false
playAnimation:大和炮
alsoQueueAction:abl2
#spawnEffects:CUSTOM:sparksChargeB*8,CUSTOM:blinkFlash,CUSTOM:blinkGlow
whenBuilding_cannotMove:true
addActionCooldownTime:60s
allowMultipleInQueue:false
price:energy=1200

[hiddenAction_abl2]
#预热
buildSpeed:3s
alsoQueueAction:abl3
playSoundAtUnit:主炮蓄力.ogg
whenBuilding_cannotMove:true
spawnEffects:CUSTOM:sparksChargeB*8

[hiddenAction_abl3]
#攻击
spawnEffects:CUSTOM:輪
buildSpeed:3s
fireTurretXAtGround_withOffset:0,700
fireTurretXAtGround:大和炮
playSoundAtUnit:开火.ogg
alsoQueueAction:abl4
whenBuilding_cannotMove:true
spawnUnits:大震
[hiddenAction_abl4]
#后摇
fireTurretXAtGround:礼花
whenBuilding_cannotMove:true
buildSpeed:0s
alsoQueueAction:1234
[hiddenAction_1234]
#后摇
whenBuilding_cannotMove:true
buildSpeed:3.5s
[animation_大和炮]
#起始
arm1_0s:{x:0, y:0}
arm2_0s:{x:0, y:0}
#打开
arm1_3s:{x:-15, y:0}
arm2_3s:{x:15, y:0}
#保持
arm1_4s:{x:-15, y:0}
arm2_4s:{x:15, y:0}
#关闭
arm1_12s:{x:0, y:0}
arm2_12s:{x:0, y:0}


[effect_輪]
priority:critical
stripIndex:shockwave
life:240
#delayedStartTimer:
color:#fff890
image:輪.png
scaleTo:4
yOffsetRelative:130
[effect_sparksChargeB]
image:spotlight.png
dirOffsetRandom:360
life:0
scaleFrom:1.5
scaleTo:0
alsoEmitEffects:CUSTOM:sparksCharge2B*10,CUSTOM:sparksCharge3B
dirSpeedRandom:0.5
fadeOut:false
priority:high
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
yOffsetRelative:140
[effect_sparksCharge2B]
image:spotlight.png
dirOffsetRandom:360
life:120
scaleFrom:2
scaleTo:0
alpha:0.7
dirSpeedRandom:1
fadeOut:false
delayedStartTimerRandom:60
priority:high

xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
yOffsetRelative:140
[effect_sparksCharge3B]
image:spotlight.png
dirOffsetRandom:360
life:20
scaleFrom:1.8
scaleTo:0
alpha:0.4
dirSpeedRandom:2
fadeOut:false
delayedStartTimer:20
priority:high
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
[arm_1]
x:0
y:-20
image_end:left.png
drawOverBody:true
image_end_teamColors:true
[arm_2]
x:0
y:-20
image_end:right.png
drawOverBody:true
image_end_teamColors:true

[turret_大和炮]
x:0
y:105
canAttack:false
limitingAngle:60
shoot_flame:CUSTOM:闪看看,CUSTOM:测试,CUSTOM:停留,CUSTOM:左*2,CUSTOM:右*2,CUSTOM:后冲

[effect_闪看看]
life:20
image:闪光.png
drawUnderUnits:true
scaleTo:15
scaleFrom:15
[effect_开炮]
life:200
scaleTo:12
scaleFrom:9
image:黑烟.png
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
ySpeedRelative:5
alpha:0.7
attachedToUnit:false
[effect_停留]
life:500
scaleTo:7
scaleFrom:10
image:黑烟.png
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
alpha:0.7
attachedToUnit:false
[effect_左]
life:120
scaleTo:3
scaleFrom:5
image:黑烟.png
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
xSpeedRelative:1

attachedToUnit:false
alpha:0.7
[effect_右]
life:120
scaleTo:3
scaleFrom:5
image:黑烟.png
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
xSpeedRelative:-1
alpha:0.7
attachedToUnit:false
[effect_后冲]
life:120
scaleTo:12
scaleFrom:2
image:黑烟.png
attachedToUnit:false
yOffsetRelativeRandom:50
ySpeedRelative:-0.5
alpha:0.8
[effect_测试]
life:300
scaleTo:12
scaleFrom:7
image:黑烟.png
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
#physics:true
ySpeedRelative:0.6
attachedToUnit:false
[effect_弹坑]
life:6000
showInFog:true
scaleTo:3
scaleFrom:3
priority:critical
physics:true
dirOffsetRandom:360
image:弹坑.png
createWhenOffscreen:true
alwayStartDirAtZero:true
drawUnderUnits:true

[effect_特效1]
life:60000
showInFog:true
priority:critical
physics:true
dirOffsetRandom:360
alsoPlaySound:爆炸音效.ogg
lifeRandom:30
image:blackSmoke1.png
createWhenOffscreen:true
alwayStartDirAtZero:true
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
ySpeedAbsoluteRandom:0.4
ySpeedAbsolute:0.5
xSpeedAbsoluteRandom:0.4
xSpeedAbsolute:0.5
drawUnderUnits:true
[effect_特效2]
life:600
alsoPlaySound:爆炸音效.ogg
showInFog:true
priority:critical
dirOffsetRandom:360
lifeRandom:30
image:FX_Smoke2.png
ySpeedRelativeRandom:0.5
ySpeedRelative:0.5
xSpeedRelativeRandom:0.5
xSpeedRelative:0
[effect_粒子2]
life:180
createWhenOffscreen:true
spawnChance:0.4
hSpeed:0.2
alwayStartDirAtZero:true
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
hSpeedRandom:0.1
fadeOut:1
fadeInTime:0
scaleTo:0.5
scaleFrom:0.5
image:chargeburst.png
dirSpeedRandom:6
attachedToUnit:false
yOffsetRelative:105

[turret_L1]
x:-34
y:49
projectile:cannon
size:0
warmup:40
shoot_sound:cannon fire.ogg
turnSpeed:9999
turnSpeedAcceleration:999
idleDir:-90
limitingAngle:270
shoot_flame:custom:EkMuzzleLarge

[turret_L2]
x:-35
y:25
warmup:60
@copyFromSection:turret_L1

[turret_L3]
x:-34
y:1
warmup:85
@copyFromSection:turret_L1

[turret_R1]
x:34
y:49
warmup:55
idleDir:90
@copyFromSection:turret_L1

[turret_R2]
x:35
y:25
warmup:65
@copyFromSection:turret_R1

[turret_R3]
x:34
y:1
warmup:45
@copyFromSection:turret_R1

[projectile_cannon]
image:projectile_long.png
deflectionPower:3
directDamage:130
life:800
speed:10
#areaDamage:300
#areaRadius:35
frame:11
color:#FFBB99
lightSize:0.7
drawSize:0.6
largeHitEffect:true
explodeEffect:CUSTOM:boom2,CUSTOM:crush,CUSTOM:projectileWaterSmoke small*3,CUSTOM:projectileWaterSplash small*3,CUSTOM:闪光,闪光2,sparks*4
trailEffect:CUSTOM:smoke,CUSTOM:白烟*2
explodeEffectOnShield:CUSTOM:白烟*3
armourIgnoreAmount:40
shieldDamageMultiplier:1.3
tags:EKAmmo

[effect_闪光]
priority:critical
image:SHARED:light_50.png
life:35
fadeOut:true
alpha:0.6
color:#FFB047
attachedToUnit:false
fadeInTime:2
scaleFrom:2
scaleTo:1.5
drawUnderUnits:false
atmospheric:false
[effect_闪光2]
priority:critical
image:flash.png
life:35
fadeOut:true
alpha:0.6
color:#DD7A00
attachedToUnit:false
fadeInTime:1
scaleFrom:0.6
scaleTo:0.3
drawUnderUnits:false
atmospheric:true


[effect_sparks]
attachedToUnit:false
life:150
physics:true
xSpeedRelativeRandom:1.2
ySpeedRelativeRandom:1.3
hSpeed:1.8
image:SHARED:spark.png
priority:verylow
scaleFrom:1.8
scaleTo:0.3
color:#FF9E00
[effect_白烟]
life:40
createWhenOffscreen:true
spawnChance:0.4
hSpeed:1
alwayStartDirAtZero:true
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
hSpeedRandom:0.5
fadeOut:1
fadeInTime:0
scaleTo:0.5
scaleFrom:0.5
image:白烟.png
color:#FFFFFF
attachedToUnit:false
[effect_EkMuzzleLarge]
life:25
showInFog:true
attachedToUnit:true
image:muzzle_large.png
total_frames:5
animateFrameStart:0
animateFrameEnd:4
animateFrameSpeed:0.4
scaleFrom:1.2
scaleTo:1.2
fadeOut:false
yOffsetRelative:17.5
drawUnderUnits:true
[effect_smoke]
createWhenZoomedOut:false
priority:low
xOffsetRelative:0
yOffsetRelative:0
image:白烟.png
life:180
fadeOut:true
attachedToUnit:false
fadeInTime:1
scaleFrom:0.9
scaleTo:0.2
alpha:0.5
drawUnderUnits:true
ySpeedRelative:0.3
[effect_boom2]
life:150
image:explode.png
priority:critical
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
alwayStartDirAtZero:true
scaleFrom:0.8
scaleTo:1.5
[effect_crush]
priority:critical
image:crush.png
createWhenOverLiquid:false
life:600
fadeOut:true
scaleFrom:0.5
scaleTo:0.5
alpha:1
drawUnderUnits:true
attachedToUnit:false
alwayStartDirAtZero:true
[effect_projectileWaterSmoke]
stripIndex:effects
frameIndex:0
createWhenOverLand:false
life:360
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:5
scaleFrom:1.5
scaleTo:8
alpha:0.8
drawUnderUnits:false
hSpeed:0.2
hOffsetRandom:0.15
atmospheric:true
dirOffsetRandom:180
shadow:true
xOffsetRelativeRandom:32
yOffsetRelativeRandom:32
xSpeedAbsoluteRandom:0.3
ySpeedAbsoluteRandom:0.3
[effect_projectileWaterSplash]
image:sub_bubbles.png
createWhenOverLand:false
life:120
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:5
scaleFrom:1
scaleTo:4
alpha:1
drawUnderUnits:false
hSpeed:1
hOffsetRandom:0.3
atmospheric:true
dirOffsetRandom:180
physics:true
physicsGravity:0.1
xOffsetRelativeRandom:16
yOffsetRelativeRandom:16
xSpeedAbsoluteRandom:0.8
ySpeedAbsoluteRandom:0.8
[effect_projectileWaterSmoke small]
stripIndex:effects
frameIndex:0
createWhenOverLand:false
life:360
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:5
scaleFrom:0.5
scaleTo:2.8
alpha:0.8
drawUnderUnits:false
hSpeed:0.2
hOffsetRandom:0.15
atmospheric:true
dirOffsetRandom:180
shadow:true
xOffsetRelativeRandom:32
yOffsetRelativeRandom:32
xSpeedAbsoluteRandom:0.3
ySpeedAbsoluteRandom:0.3
[effect_projectileWaterSplash small]
image:sub_bubbles.png
createWhenOverLand:false
life:120
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:5
scaleFrom:0.5
scaleTo:2
alpha:1
drawUnderUnits:false
hSpeed:1
hOffsetRandom:0.3
atmospheric:true
dirOffsetRandom:180
physics:true
physicsGravity:0.1
xOffsetRelativeRandom:16
yOffsetRelativeRandom:16
xSpeedAbsoluteRandom:0.8
ySpeedAbsoluteRandom:0.8
[effect_projectileTrail]
image:trail_ring.png
life:20
fadeOut:true
fadeInTime:1
scaleFrom:0.5
scaleTo:1.75
alpha:1
drawUnderUnits:false
attachedToUnit:false
yOffsetRelative:10
dirOffsetRandom:1
atmospheric:true
[effect_projectileFlash]
image:SHARED:light_50.png
life:30
fadeOut:true
attachedToUnit:false
color:#FFC08D
fadeInTime:2
scaleFrom:3.5
scaleTo:2.5
alpha:1
drawUnderUnits:false
atmospheric:false
hOffset:5
yOffsetAbsolute:-10
[effect_EkJetfire]
image:jetflame1.png
life:26
fadeOut:true
attachedToUnit:false
fadeInTime:1
scaleFrom:1.6
scaleTo:3
alpha:0.8
xSpeedRelativeRandom:0.1
yOffsetRelative:-105
ySpeedRelative:0.75
dirOffsetRandom:15
drawUnderUnits:true
atmospheric:true
[movement]
movementType:AIR
moveSpeed:0.7
moveAccelerationSpeed:0.025
moveDecelerationSpeed:0.025
reverseSpeedPercentage:0
maxTurnSpeed:0.8
turnAcceleration:0.1
moveSlidingMode:true
moveSlidingDir:45
slowDeathFall:true