#本ini已弃用，现用杀血
[core]

name:大震
price:0, cash=0
maxHp:8
buildSpeed:1
techLevel:1
radius:0
canOnlyBeAttackedByUnitsWithTags:无敌

mass:-1
isUnselectable:true
hideScorchMark:true
explodeOnDeath:false
numBitsOnDeath:0
showInEditor: false
autoTriggerCooldownTime:0.1s
[action_开始]
price:0, cash=0
spawnEffects:CUSTOM:竖,CUSTOM:横
buildSpeed:0
autoTrigger:true
[action_炮击]
autoTrigger:true
price:0,hp=1
addResources:hp=-0.4


[graphics]
image:SHARED:blank.png
scaleImagesTo:1
disableLowHpFire:true
showHealthBar:  false

[attack]
canAttack:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false

[movement]
movementType:land
moveSpeed:0
maxTurnSpeed:1

[effect_横]
image:横向.png
life:5
scaleFrom:15
scaleTo: 15
alpha: 1
#fadeOut:false
atmospheric:true
attachedToUnit: false
drawType:displacement
drawUnderUnits:false
delayedStartTimerRandom:0.3
priority:critical

[effect_竖]
image:竖向.png
life:5
scaleFrom:15
scaleTo: 15
alpha:1
#fadeOut:false
atmospheric:true
attachedToUnit: false
drawType:displacement
drawUnderUnits:false
#delayedStartTimerRandom:0.3
priority:critical