[core]


name:Ek_Principality
displayText:Князь
displayDescription:-Тяжеловооружённый мех\n-способен справиться с большинством боевых ситуаций\n-Два комплекта зенитных ракетных комплексов большой дальности «Hellfire»\n-Два комплекта параллельных 30-мм гладкоствольных цепных пушек\n-Возможности противовоздушной обороны сильнее, чем наземные возможности
class:CustomUnitMetadata
price:0, cash=19000
maxHp:3000
armour:20
mass:14000
techLevel:2
buildSpeed:60s
radius:30
strictLevel:1
autoTriggerCooldownTime_allowDangerousHighCPU:true
autoTriggerCooldownTime:0
isBio:false
softCollisionOnAll:25
transportSlotsNeeded:2
builtFrom_2_name:mechFactoryT2
builtFrom_2_pos:7.15
energyRegenWhenRecharging:0.30
energyMax:60
energyRegen:0.1
energyNeedsToRechargeToFull:true
[graphics]
imageScale:1
total_frames:1
image:body1.png
image_wreak:goliath_dead.png
image_turret:none
image_shadow:auto
shadowOffsetX:4
shadowOffsetY:4
teamColorsOnTurret:true
lock_body_rotation_with_main_turret:true

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
aimOffsetSpread:1.5
maxAttackRange:370
turretRotateWithBody:true
turretTurnSpeed:2.5
setMainTurretAs:cannonbase

[effect_EkMuzzleLarge]
life:20
attachedToUnit:true
image:muzzle_large.png
scaleTo:0.55
scaleFrom:0.65
total_frames:5
animateFrameStart:0
animateFrameEnd:4
animateFrameSpeed:1.25
fadeOut:true
alsoPlaySound:machine_gun.ogg:0.22
spawnChance:0.35
[effect_explode]
life:20
dirOffsetRandom:180
priority:veryhigh
fadeOut:true
attachedToUnit:false
scaleFrom:0.4
scaleTo:0.4
image:explode.png
total_frames:4
animateFrameStart:0
animateFrameEnd:3
animateFramePingPong:false
animateFrameSpeed:0.38
alpha:1.0

[turret_1]
#top left missile
x:-17
y:0
attachedTo:cannonbase
slave:true
projectile:2
turnSpeed:0
shoot_flame:large
shoot_light:#FFff925c
shoot_sound:AA_Missile.ogg
shoot_sound_vol:0.5
warmup:0
canAttackMaxAngle:181
canAttackLandUnits:false
delay:1.8s
size:2
canAttackCondition:if self.hasTags(includes="shift")

[turret_2]
#top left missile
x:17
y:0
attachedTo:cannonbase
slave:true
projectile:2
turnSpeed:0
shoot_flame:large
shoot_light:#FFff925c
delay:1.8s
canAttackMaxAngle:181
canAttackLandUnits:false
size:2
canAttackCondition:if self.hasTags(includes="shift")

[hiddenAction_down]
autoTrigger:if self.attacking.height>= 10
setUnitStats:targetHeight=0.05,moveSpeed=0.5,maxTurnSpeed=0.5
temporarilyAddTags:shift

[hiddenAction_up]
autoTrigger:if self.attacking.height<= 8 and  self.hasTags(includes="shift")
resetUnitStats:true
temporarilyRemoveTags:shift

[hiddenAction_clear]
autoTriggerOnEvent:killedAnyUnit
requireConditional:if self.energy<${core.energyMax/2}
setResourcesWithLogic:energy=1

[turret_cannon1]
x:-18
y:0
attachedTo:cannonbase
slave:true
projectile:3
energyUsage:1
turnSpeed:0
shoot_flame:CUSTOM:EkMuzzleLarge
shoot_light:#FFff925c
canAttackFlyingUnits:false
size:29
delay:0.04s
warmup:0
limitingRange:270

[turret_cannon2]
x:18
y:0
attachedTo:cannonbase
slave:true
projectile:3
energyUsage:1
turnSpeed:0
shoot_flame:CUSTOM:EkMuzzleLarge
shoot_light:#FFff925c
canAttackFlyingUnits:false
size:29
delay:0.02s
warmup:0.02s
limitingRange:270

[turret_cannon3]
x:-13
y:0
attachedTo:cannonbase
slave:true
projectile:3
energyUsage:1
turnSpeed:0
shoot_flame:CUSTOM:EkMuzzleLarge
shoot_light:#FFff925c
canAttackFlyingUnits:false
size:34
delay:0.04s
warmup:0
limitingRange:270

[turret_cannon4]
x:13
y:0
attachedTo:cannonbase
slave:true
projectile:3
energyUsage:1
turnSpeed:0
shoot_flame:CUSTOM:EkMuzzleLarge
shoot_light:#FFff925c
canAttackFlyingUnits:false
size:34
delay:0.02s
warmup:0.02s
limitingRange:270

[turret_cannonbase]
x:0
y:0
projectile:NULL
turnSpeed:2.5
turnSpeedAcceleration:3
delay:1
canShoot:false
aimOffsetSpread:0
recoilOffset:-3
recoilOutTime:2
recoilReturnTime:2
idleSweepAngle:50
idleSweepSpeed:0.5
idleSweepDelay:240
idleSweepAddRandomDelay:25
idleSweepCondition:if not self.isMoving()

[projectile_1]
life:150
speed:5
frame:2
areaDamage:23
areaRadius:23
largeHitEffect:true
targetGround:true
targetGroundSpread:20
areaRadiusFromEdge:true
drawSize:1.2
lightColor:#ffe92b
lightSize:0.4
instant:true
explodeEffect:CUSTOM:explode
tags:EKAmmo

[projectile_2]
life:120
targetSpeed:12
targetSpeedAcceleration:0.001
trailEffect:true
trailEffectRate:0.5
largeHitEffect:true
image:missile.png
drawSize:1.0
autoTargetingOnDeadTarget:true
wobbleAmplitude:0.5
wobbleFrequency:0.5
armourIgnoreAmount:10
areaDamage:260
areaRadius:40
turnSpeed:15
areaRadiusFromEdge:true
turnSpeedWhenNear:15
explodeEffect:CUSTOM:explode2

[projectile_3]
directDamage:23
areaDamage:23
areaRadius:23
life:200
image:projectile_bulletlong.png
speed:25
color:#FF0000
drawSize:1
lightColor:#FF0000
lightSize:2
turnSpeed:0
alwaysVisibleInFog:true
deflectionPower:2
[effect_explode2]
life:30
dirOffsetRandom:180
priority:veryhigh
fadeOut:true
attachedToUnit:false
scaleFrom:1.0
scaleTo:1.1
image:explode2.png
total_frames:14
animateFrameStart:0
animateFrameEnd:13
animateFramePingPong:false
animateFrameSpeed:0.35
alpha:1.1

[leg_1]
x:8
y:0
attach_x:0
attach_y:0
moveSpeed:2.65
moveWarmUp:0.05s
rotateSpeed:9
heightSpeed:1.1
resetAngle:25
image_leg:leg5.png
image_foot:foot1.png
holdDisMin:28
holdDisMax:35

[leg_2]
x:-8
y:0
attach_x:0
attach_y:0
copyFrom:1

[movement]
movementType:OVER_CLIFF
moveSpeed:0.55
moveAccelerationSpeed:0.07
moveDecelerationSpeed:0.17
targetHeight:3
maxTurnSpeed:2.5
turnAcceleration:0.15
moveSlidingMode:true
moveIgnoringBody:true
reverseSpeedPercentage:0.3
slowDeathFall:true

[decal_superheat1]
image:superheat1.png
layer:onTop
xOffsetRelative:-13.3
yOffsetRelative:18
alpha:((self.maxEnergy-self.energy)/self.maxEnergy)-0.2

[decal_superheat2]
image:superheat1.png
layer:onTop
xOffsetRelative:13.3
yOffsetRelative:18
alpha:((self.maxEnergy-self.energy)/self.maxEnergy)-0.2

[decal_superheat3]
image:superheat2.png
layer:onTop
xOffsetRelative:-17.7
yOffsetRelative:13
alpha:((self.maxEnergy-self.energy)/self.maxEnergy)-0.2

[decal_superheat4]
image:superheat2.png
layer:onTop
xOffsetRelative:17.7
yOffsetRelative:13
alpha:((self.maxEnergy-self.energy)/self.maxEnergy)-0.2