#Bug Generator by SUSHIMAKI
#Edited by Essential Strategy

[core]
name: generatorBug
displayText: Generator
displayText_es: Generador
displayDescription: -Generates income slower than extractors\n-Can evolve
displayDescription_es: -Genera ingresos más lento que los extractores\n-Puede evolucionar
class: CustomUnitMetadata
overrideAndReplace: bugGeneratorN
price: 4000
maxHp: 600
mass: 500
techLevel: 1
buildSpeed: 60s
#availableInDemo: true
radius: 12
isBio: true
isBug: true
isUnrepairableUnit: true
selfBuildRate:0.002
selfRegenRate:0.1
generation_credits: 6
generation_resources:crystalline=5
generation_delay: 40
softCollisionOnAll: 12
effectOnDeath: CUSTOM:smallDeath

[action_evolve]
convertTo: generatorBugT2
displayType: upgrade
text: Evolve - E2
text_es: Evolucionar - E2
description: -Generates 3 times more income
description_es: -Genera 3 veces más ingresos
buildSpeed: 0.0007
price: 16000
whenBuilding_cannotMove: true
canPlayerCancel: false
pos: 0

[graphics]
imageScale: 0.9
total_frames: 1
image:        bug_generator.png
image_wreak:  NONE
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 60
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[leg_1]
x: -6
y: 4
attach_x: 0
attach_y: 0
moveSpeed: 1.5
rotateSpeed: 6
resetAngle:5
heightSpeed: 0.8
dust_effect: false
holdDisMin: 1
holdDisMax: 1
image_leg:  leg.png

[leg_2]
x: 6
y: 4
attach_x: 0
attach_y: 0
copyFrom: 1

[leg_3]
x: -8
y: 0
attach_x: 0
attach_y: 0
copyFrom: 1

[leg_4]
x: 8
y: 0
attach_x: 0
attach_y: 0
copyFrom: 1

[leg_5]
x: -8
y: -4
attach_x: 0
attach_y: 0
copyFrom: 1

[leg_6]
x: 8
y: -4
attach_x: 0
attach_y: 0
copyFrom: 1

[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 2
turnAcceleration: 0.1
moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0

[ai]
buildPriority: 0.2
maxEachBase: 5

#Bug Generator by SUSHIMAKI