#Corroder by Static Charge Red Field
#Edited by Essential Strategy

[core]
name: corroderSpit
copyFrom: corroder_spray.ini
showInEditor: false
selfRegenRate:0.01
fogOfWarSightRange: 16
isUnrepairableUnit: true
effectOnDeath: CUSTOM:spitterDeath

[action_switch]
convertTo: corroderSpray
text: Spray
description: -Attacks from a shorter distance at multiple targets, better against weak groups of units\n-Regenerates faster
description_es: -Ataca desde una menor distancia a múltiples objetivos, mejor contra grupos débiles de unidades\n-Se regenera más rápido

[graphics]
image: corroder_spit.png
animation_attack_start: 0
animation_attack_end: 0
animation_attack_speed: 14
animation_attack_scale_start:1
animation_attack_scale_end:0.97
animation_attack_pingPong: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretTurnSpeed: 3
maxAttackRange: 200
shootDelay: 80

[turret_1]
x: 0
y: 0
projectile: 2
shoot_flame: smoke
shoot_sound: bug_attack
shoot_sound_vol:0.05
recoilOffset: -3
recoilOutTime: 6
recoilReturnTime: 18

[projectile_2]
directDamage: 115
life: 150
hitSound: true
speed: 7
lightSize:1.1
color:green
lightColor: green
drawSize: 2
shieldDamageMultiplier: 1.1
explodeEffectOnShield:CUSTOM:hitLightFlash,CUSTOM:spittle*4
explodeEffect: CUSTOM:spittle*4,CUSTOM:spittle2*4

[movement]
movementType: OVER_CLIFF
moveSpeed: 1.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 8.5
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

#Corroder by Static Charge Red Field