#Corroder by Static Charge Red Field
#Edited by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: corroderSpray
class: CustomUnitMetadata
price:0, cash=3200
displayText: Corroder
displayText_es: Corroedor
displayDescription: -Powerful area of effect attack against ground\n-Can switch range and spread\n-Self regenerate
displayDescription_es: -Poderosa área de efecto de ataque contra tierra\n-Puede cambiar rango y spray\n-Auto-regeneración
maxHp: 1200
mass: 10000
techLevel: 2
buildSpeed: 0.0008
#availableInDemo: true
radius: 28
numBitsOnDeath: 8
transportSlotsNeeded: 4
selfRegenRate:0.2
fogOfWarSightRange: 12
isBio: true
isBug: true
isUnrepairableUnit: true
effectOnDeath: CUSTOM:bigDeath

[action_switch]
convertTo: corroderSpit
displayType: action
price:0, cash=0
text: Spit
text_es: Escupir
description: -Attacks from a larger distance at single targets, better against armored units\n-Regenerates more slowly
description_es: -Ataca desde una mayor distancia a objetivos únicos, mejor contra unidades blindadas\n-Se regenera más lentamente
buildSpeed: 0.01
pos:-1

[graphics]
imageScale: 1.1
total_frames: 3
image:        corroder.png
image_wreak:  corroder_dead.png
lock_body_rotation_with_main_turret: true
image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
aimOffsetSpread: 0
isMelee: true
turretSize: 8
turretTurnSpeed: 3
maxAttackRange: 9
shootDelay: 0

[turret_1]
x: 0
y: 0
turnSpeedAcceleration: 0.05

[projectile_1]
life: 100
frame:13
flameWeapon: true
hitSound: false
speed:6
targetGround:true
targetGroundSpread: 20
deflectionPower: -1
areaDamage: 6
areaRadius: 60
lightColor: #ffcc0000
lightSize: 1.5

[leg_1]
x: -25
y: -5
attach_x: 0
attach_y: -6
moveSpeed: 4
resetAngle:20
heightSpeed: 0.8
image_leg:  leg.png
image_foot: NONE
dust_effect: false
holdDisMin: 5
holdDisMax: 16

[leg_2]
x: 25
y: -5
attach_x: 0
attach_y: -6
copyFrom: 1

[leg_3]
x: -20
y: 10
attach_x: 0
attach_y: -10
copyFrom: 1

[leg_4]
x: 20
y: 10
attach_x: 0
attach_y: -10
copyFrom: 1

[leg_5]
x: -20
y: -20
attach_x: 0
attach_y: -8
copyFrom: 1

[leg_6]
x: 20
y: -20
attach_x: 0
attach_y: -8
copyFrom: 1

[movement]
movementType: OVER_CLIFF
moveSpeed: 1.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 8.5
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

#Corroder by Static Charge Red Field