#Bug Turret by Luke Hoschke
#Edited by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: bugTurretMod
class: CustomUnitMetadata
price: 1000
maxHp: 800
mass: 10000
overrideAndReplace: bugTurret
displayText: Bio Turret
displayText_es: Torreta Biológica
displayDescription: -Deffensive organism\n-Attacks ground and air\n-Self regenerate
displayDescription_es: -Organismo defensivo\n-Ataca a tierra y aire\n-Auto-regeneración
techLevel: 1
buildSpeed: 0.002
#availableInDemo: true
radius: 16
isBio: true
isBug: true
isUnrepairableUnit: true
numBitsOnDeath: 3
isBuilding: true
selfRegenRate:0.1
selfBuildRate:0.002
softCollisionOnAll: 3

[action_evolve]
convertTo: bugTurretModT2
price: credits=2100, minerals=400
text: Upgrade - E2
text_es: Mejorar - E2
description: -Increases HP, damage and range
description_es: -Incrementa los PV, el daño y el rango
displayType: upgrade
buildSpeed: 0.0006
pos: 0

[graphics]
total_frames: 2
image:        turret.png
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 75
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true
animation_attack_start: 0
animation_attack_end: 1
animation_attack_speed: 5
animation_attack_scale_start:1
animation_attack_scale_end:1.05
animation_attack_pingPong: true

[animation_build]
onActions: underConstructionWithLinkedBuiltTime
blendOut: 1s
body_0: {scale:0}
body_1: {scale:1.2}

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretSize: 2
turretTurnSpeed: 3
maxAttackRange: 210
shootDelay: 30

[turret_1]
x: 0
y: 8
shoot_light:#FF00CCCC

[projectile_1]
directDamage: 40
life: 70
speed: 7
frame: 6
lightColor: #00ff00
lightSize: 0.2
explodeEffect:CUSTOM:spittle*6,CUSTOM:spittle2*3

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0

[ai]
buildPriority: 0.22
noneInBaseExtraPriority: 0.17
maxEachBase: 3

#Bug Turret by Luke Hoschke