[core]
copyFrom: debugMenu.ini
name: debug
class: CustomUnitMetadata
price: 0
maxHp: 2000
mass: 10000
displayText: debug
displayDescription: -Инструменты разработчиков
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1
techLevel: 1
#availableInDemo: true
radius: 30
isUnrepairableUnit: true
selfRegenRate: 0.1
softCollisionOnAll: 3

# -----ШАБЛОНЫ------

[template_emptybuttom]
text: -----------------------------------------------------------
description:
displayType: infoOnlyNoBox
isLocked: true
isLockedMessage:
isVisible: true

[template_resetRes]
@copyFromSection: template_integratedInNavigator
@define menuID:1
text: ${TEXT}
isLockedMessage: Все исследования уже активированы
isVisible: true
displayType: action
buildSpeed: 0
isActive: if true
setResourcesWithLogic: ${RES}=0

#------РЕСУРСЫ------

[action_addmoney]
@copyFromSection: template_integratedInNavigator
@define menuID:1
price: 0
text: Деньги
description: MONEY
displayType: action
buildSpeed: 0
pos: 1
isActive:if True()
addResources: credits=1000000
[action_addcrystall]
@copyFromSection: template_integratedInNavigator
@define menuID:1
price: 0
text: Кристаллы
description: MONEY
displayType: action
buildSpeed: 0
pos: 2
isActive:if True()
addResources: minerals=1000000
[action_addexperemental]
@copyFromSection: template_integratedInNavigator
@define menuID:1
price: 0
text: Экспериментал
description: MONEY
displayType: action
buildSpeed: 0
pos: 3
isActive:if True()
addResources: alloys=1000000
[action_addtechpoint]
@copyFromSection: template_integratedInNavigator
@define menuID:1
price: 0
text: Теч поинты
description: MONEY
displayType: action
buildSpeed: 0
isActive: if True()
addResources:scientificPotential=100000000
isLockedMessage: Все исследования уже активированы
pos: 4
[action_resetMoney]
@copyFromSection: template_resetRes, template_integratedInNavigator
@define menuID:1
@define RES: credits
@define TEXT: обнулить деньги 
pos: 5
[action_resetCrys]
@copyFromSection: template_resetRes, template_integratedInNavigator
@define menuID:1
@define RES: minerals
@define TEXT: обнулить минералы
pos: 6
[action_resetExp]
@copyFromSection: template_resetRes, template_integratedInNavigator
@define menuID:1
@define RES: alloys
@define TEXT: обнулить экспериментал
pos: 7
[action_resetTech]
@copyFromSection: template_resetRes, template_integratedInNavigator
@define menuID:1
@define RES: scientificPotential
@define TEXT: Обнулить теч поинты
pos: 8

#------ТЕЧ------

[action_removetech]
@copyFromSection: template_integratedInNavigator
@define menuID:2
price: 0
text: УБРАТЬ ТЕЧ
description: MONEY
displayType: action
buildSpeed: 0
isActive: if True()
removeGlobalTeamTags: techNano1,techNano2,techNano3,techProd1,techProd2,techProd3,techInfantry1,techInfantry2,techInfantry3,techTanks1,techTanks2,techTanks3,mechTech,techAircraft1,techAircraft2,techAircraft3,techShips1,techShips2,techEconomy1,techEconomy2,techDefence1,techDefence2,techBallisticMissiles1,techBallisticMissiles2,techStealth,techHyperdrive,techShips2
pos: 2
[action_addtech]
@copyFromSection: template_integratedInNavigator
@define menuID:2
price: 0
text: Теч
description: MONEY
displayType: action
buildSpeed: 0
isActive: if True()
addGlobalTeamTags: techNano1,techNano2,techNano3,techProd1,techProd2,techProd3,techInfantry1,techInfantry2,techInfantry3,techTanks1,techTanks2,techTanks3,mechTech,techAircraft1,techAircraft2,techAircraft3,techShips1,techShips2,techEconomy1,techEconomy2,techDefence1,techDefence2,techBallisticMissiles1,techBallisticMissiles2,techStealth,techHyperdrive,techShips2
isLocked: if self.globalTeamTags(includes='techHyperdrive')
isGuiBlinking: if self.globalTeamTags(includes='techHyperdrive')
isLockedMessage: Все исследования уже активированы
pos: 1
[action_BugTech]
@copyFromSection: template_integratedInNavigator
@define menuID:2
text: Теч жуков
displayType: action
buildSpeed: 0
pos: 3
isLocked: if self.globalTeamTags(includes='bugUnl')
isGuiBlinking: if self.globalTeamTags(includes='bugUnl')
addGlobalTeamTags: bugUnl,bugtechEgg1, bugtechEgg2, bugtechEgg3

[action_reBugTech]
@copyFromSection: template_integratedInNavigator
@define menuID:2
text: Убрать теч жуков
buildSpeed: 0
displayType: action
pos: 3
removeGlobalTeamTags: bugUnl, bugtechEgg1, bugtechEgg2, bugtechEgg3

#------ФРАКЦИИ------
[action_addfraction]
@copyFromSection: template_integratedInNavigator
@define menuID:3
price: 0
text: Разблокировать фракции
description: MONEY
displayType: action
buildSpeed: 0
isActive: if True()
addGlobalTeamTags: FRACTIONUNLOCKED
isLockedMessage: Фракции разблокированы!
isLocked: if self.globalTeamTags(includes='FRACTIONUNLOCKED')

#-----ПУСТЫЕ КНОПКИ И ПРОСТО КНОПКИ------
[action_justAbutton]
buildSpeed: 0
isVisible: true
price: 0
text: Просто кнопка
description: эта кнопка ничего не делает
displayType: action
pos: 0.4
[action_vb1]
@copyFromSection: template_emptybuttom
pos: 0.5
[action_vb2]
@copyFromSection: template_emptybuttom
pos: 0.51
[action_vb3]
@copyFromSection: template_emptybuttom, template_integratedInNavigator
@define menuID: 1
pos: 4.21
[action_vb4]
@copyFromSection: template_emptybuttom, template_integratedInNavigator
@define menuID: 1
pos: 4.22

#НЕ ДЕЙСТВИЯ

[graphics]
total_frames: 1
image: EKE.png
image_back:   NONE
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 150
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 1000000

[movement]
movementType: AIR
moveSpeed: 10
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 6.5
turnAcceleration: 0.4
moveSlidingMode : false
moveIgnoringBody: true
moveSlidingDir:  181
reverseSpeedPercentage:0