#Cavern by Essential Strategy

[core]
name: debug
class: CustomUnitMetadata
price: 0
maxHp: 2000
mass: 10000
displayText: debug
displayDescription: -Инструменты разработчиков
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1
techLevel: 1
#availableInDemo: true
radius: 30
isUnrepairableUnit: true
selfRegenRate: 0.1
softCollisionOnAll: 3

[action_addmoney]
price: 0
text: ДЕНЬГИ
description: MONEY
displayType: action
buildSpeed: 0
pos: 0
isActive:if True()
addResources: credits=1000000

[action_addcrystall]
price: 0
text: КРИСТАЛЛЫ
description: MONEY
displayType: action
buildSpeed: 0
pos: 0
isActive:if True()
addResources: crystalline=1000000

[action_addexperemental]
price: 0
text: ЭКСПА
description: MONEY
displayType: action
buildSpeed: 0
pos: 0
isActive:if True()
addResources: experimental=1000000
[action_addtech]
price: 0
text: ТЕЧ
description: MONEY
displayType: action
buildSpeed: 0
isActive: if True()
addGlobalTeamTags: basicTanksTech,advancedInfantryTech,mediumTanksTech,heavyTanksTech,mechTech,lightAircraftTech,advancedAircraftTech,stealthJet,heavyShipsTech,superHeavyShipsTech,spaceshipsTech,basicEconomyTech,advancedEconomyTech,defenceSystemsTech,satelliteTech,missileSystemsTech
isLocked: if self.globalTeamTags(includes='spaceshipsTech')
isLockedMessage: Все исследования уже активированы

[graphics]
total_frames: 1
image: EKE.png
image_back:   NONE
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 150
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 1000000

[movement]
movementType: AIR
moveSpeed: 10
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 6.5
turnAcceleration: 0.4
moveSlidingMode : false
moveIgnoringBody: true
moveSlidingDir:  181
reverseSpeedPercentage:0