
[core]
copyFrom:ROOT:ASSETS/templates/bio.template
name: bugExtractorMod
class: CustomUnitMetadata
price: biomass=1200
maxHp: 800
mass: 10000
displayText: Extractor
displayDescription: -Generates income\n-Can only be built on resources pools
displayDescription_es: -Genera ingresos\n-Solo puede ser construido en pozos de recursos
overrideAndReplace: bugExtractor
generation_resources: biomass=10
generation_delay: 40
techLevel: 1
buildSpeed: 0.002
unitsSpawnedOnDeath: kusaka
#availableInDemo: true
radius: 16
isBio: true
isBug: true
isUnrepairableUnit: true
isBuilding: true
placeOnlyOnResPool: true
selfRegenRate:0.1
selfBuildRate:0.002
softCollisionOnAll: 3

[action_upgrade]
convertTo: bugExtractorModE2
price: credits=2000, crystalline=600
text: Upgrade - E2
text_es: Mejorar - E2
description: -Produces +8 credits\n-More HP
description_es: -Produce +8 créditos\n-Más PV
displayType: upgrade
buildSpeed: 0.0009
pos: 0

[graphics]
total_frames: 1
image:        bug_extractor.png
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 100
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true

[animation_build]
onActions: underConstructionWithLinkedBuiltTime
blendOut: 1s
body_0: {scale:0}
body_1: {scale:1.2}

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0

[ai]
buildPriority: 0.2
noneGlobalExtraPriority: 0.2
maxEachBase: 15