[core]
copyFrom:   command_starter.ini
name:       commandShield
displayText:Command Center Shielded

maxShield: 8000
shieldRegen: 0
shieldRenderRadius: 35

armour: 30

energyRegen: -0.0001
selfRegenRate: 1.683
showInEditor: false

[action_powerDown]
iconImage: ROOT:ASSETS/ui/action_icons/areaShockIcon.png
convertTo: commandCenterEK
isVisible: false
displayType: action
text: Отключить щиты
autoTrigger: if self.isEnergyEmpty or self.shield(empty=true)
buildSpeed: 0s
addResources: energy=-0.5
canPlayerCancel: false

#[action_upgrade]
#isVisible: false

