[core]
copyFrom:ROOT:ASSETS/templates/vehicle.template
name:EkRhino
displayText:Носорог
displayDescription:-Средний танк\n-Легкая пушка\n-Высокая скорость\n-Не может атаковать воздух
price:350
maxHp:400
mass:3000
armour:10
techLevel:1
buildSpeed:12s
radius:15
displayRadius:16
builtFrom_1_name:landFactory
builtFrom_1_pos:10.002
softCollisionOnAll:0
energyMax:1
energyRegen:0.006
energyNeedsToRechargeToFull:true
maxTransportingUnits:3

[hiddenAction_addCrew]
autoTriggerOnEvent:created
addUnitsIntoTransport:EkInfantryGrunt*3

[graphics]
total_frames:3
icon_zoomed_out:unit_icon_tank.png
image:rhino.png
image_wreak:rhino_dead.png
image_turret:rhino_turret.png
image_shadow:AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start:0
animation_moving_end:2
animation_moving_speed:1.5
dustEffect:true
teamColorsOnTurret:true
scaleImagesTo:21

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:25
turretTurnSpeed:4
maxAttackRange:130
shootDelay:75
aimOffsetSpread:0.25

[projectile_20mm]
#normal barrel
image:ROOT:ASSETS/projectiles/tracer_shot.png
directDamage:1
areaDamage:0
armourIgnoreAmount:15
areaRadius:8
targetGround:true
targetGroundSpread:4
trailEffect:CUSTOM:bulletTrail
trailEffectRate:0.1
life: 200
speed: 29
frame: 1
drawSize: 0.65
lightColor:#ff9600
lightSize:0.8
areaHitAirAndLandAtSameTime:true
spawnProjectilesOnExplode:20mm_damage(yOffsetRelative=-20)

[projectile_20mm_damage]
life:0
speed:0
directDamage:0
spawnUnit:20mm
explodeEffect:NONE
explodeOnEndOfLife:true

[projectile_none]
life:0
directDamage:0

[effect_bulletTrail]
life: 20
image: ROOT:ASSETS/graphicsEffects/trail2.png
color: #CCCCDD
priority: veryhigh
attachedToUnit: false
atmospheric: false
physics: false
physicsGravity: 0
xOffsetRelative: 0
yOffsetRelative: 0
xSpeedRelative: 0
ySpeedRelative: 0
scaleFrom: 0.1
scaleTo: 0.15

[turret_1]
x:0
y:-1
invisible:true
idleDir:0
turnSpeed:2.0
turnSpeedAcceleration:1.0
canShoot:false

[turret_2]
image:rhino_cannon.png
x:0
y:0
attachedTo:1
slave:true
shoot_sound:tank_firing
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFEECCCC
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
projectile:20mm
recoilOffset:-3
recoilOutTime:6
recoilReturnTime:18

[turret_3]
invisible:false
x:0
y:0
attachedTo:1
slave:true
canShoot:false
recoilOffset:0

[movement]
movementType:LAND
moveSpeed:1.10
moveAccelerationSpeed:0.07
moveDecelerationSpeed:0.17
maxTurnSpeed:4.1
turnAcceleration:0.25
moveSlidingMode:false
moveIgnoringBody:false