[core]

#来源于锈蚀科技（已经过授权）
name: artillery
displayLocaleKey: artillery
overrideAndReplace: artillery,c_artillery
price:0, cash=650
maxHp: 150
mass: 14000
techLevel: 1
buildSpeed: 0.0014
radius: 15
@memory frame:float
updateUnitMemory:frame=(memory.frame+select(self.isReversing,19,2)*select(self.isMoving,1,0))%3
updateUnitMemoryRate:4
[graphics]
image:artillery.png
image_wreak:artillery_dead.png
image_shadow:SHADOW:artillery_shadow.png
shadowOffsetX:3
shadowOffsetY:3
dustEffect: true
lock_body_rotation_with_main_turret:true
lock_leg_rotation_with_main_turret:true
[decal_track]
image:track.png
xOffsetRelative:-0.5
total_frames:3
frame:memory.frame
layer:beforeBody
onlyWhileAlive:true
basePositionFromTurret:1
[decal_turret_shadow]
layer:shadow
image:SHADOW:artillery_turret_shadow.png
xOffsetAbsolute:3
yOffsetAbsolute:3
onlyWhileAlive:true
basePositionFromLegEnd:arm_1
alwaysStartHeightAtZero:true
alpha:0.5
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretSize: 22
turretTurnSpeed: 4
isFixedFiring: true
maxAttackRange: 370
shootDelay: 310
[arm_1]
x:0
y:0
image_end:artillery_turret.png
drawOverBody:true
moveSpeed:10000
[arm_2]
x:0
y:0
image_end:artillery_turret_caser.png
drawOverBody:true
moveSpeed:1000
[arm_3]
x:0
y:0
image_end:artillery_turret_cover.png
drawOverBody:true
moveSpeed:10000
[arm_4]
x:0
y:0
image_end:artillery_mantlet.png
drawOverBody:true
[animation_shellThrowing]
arm1_3:{y:-5}
arm1_220:{y:0}
arm2_0:{x:3,y:0}
arm2_3:{x:3,y:-5}
arm2_18:{x:0}
arm2_220:{x:0,y:0}
arm3_3:{y:-5}
arm3_220:{y:0}
arm4_3:{y:-1}
arm4_60:{y:0}
[turret_1]
x: 0
y: 0
projectile: 1
turnSpeedAcceleration: 1
shoot_sound:cannon_firing
shoot_sound_vol:0.3
shoot_flame:small,shell
shoot_light:#FFEEEEEE
recoilOffset: -1
recoilOutTime: 3
recoilReturnTime: 57
onShoot_playAnimation:shellThrowing
[projectile_1]
directDamage: 1
life: 150
speed: 3.5
frame: 2
color: #bebe50
drawSize: 1.2
areaDamage: 90
areaRadius: 80
largeHitEffect: true
targetGround: true
lightColor: #ffe92b
lightSize: 0.4
targetGroundSpread: 30
initialUnguidedSpeedHeight: 1.2
gravity:0.18
lightCastOnGround: true
[effect_shell]
life:100
physics:true
physicsGravity:0.8
hSpeed:1
xSpeedRelative:-1.2
xSpeedRelativeRandom:0.2
yOffsetRelative:-29.5
dirSpeedRandom:0.1
attachedToUnit:false
image:shell.png
imageShadow:SHADOW:shell.png
alpha:3
priority:high
[movement]
movementType: LAND
moveSpeed: 0.59
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.12
maxTurnSpeed: 1.5
turnAcceleration: 0.05
moveSlidingMode :false
moveIgnoringBody:false