#Queen by Essential Strategy
#Graphics by SUSHIMAKI

[core]
copyFrom:ROOT:assets/templates/bio.template
tags: crystalDropoff
name: queen
displayText: Queen
displayText_es: Reina
displayDescription: -Generates spores
displayDescription_es: -Genera esporas
class: CustomUnitMetadata
price: 15000
maxHp: 2000
mass: 800
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,3
techLevel: 1
buildSpeed: 0.002
selfBuildRate:0.002
selfRegenRate:0.1
#availableInDemo: true
radius: 30
isBio: true
isBug: true
isBuilding: true
nukeOnDeath: true
nukeOnDeathRange: 10
nukeOnDeathDamage: 0
isUnrepairableUnit: true
generation_resources: biomass=6
generation_delay: 40
numBitsOnDeath: 15
softCollisionOnAll: 3
exit_x:0
exit_y: 29
canBuild_1_name: setRally, spore, ladybugMod
canBuild_1_pos:  0.1
effectOnDeath: CUSTOM:queenDeath
unitsSpawnedOnDeath: kusaka*200

[action_evolve]
convertTo: cocoon
price: credits=10000, minerals=2000
text: Upgrade - E2
text_es: Mejorar - E2
description: -Ables the queen to move and transport units\n-Increases regeneration rate and HP\n-Cannot produce nothing while its in progress
description_es: -Permite a la reina moverse y transportar unidades\n-Incrementa la tasa de regeneración y los PV\n-No puede producir nada mientras está en progreso
displayType: upgrade
buildSpeed: 0.0008
isActive: if self.hp(greaterThan=1000)
pos: 0

[hiddenAction_aiBoost]
autoTrigger: if self.isControlledByAI()
requireConditional: if self.isControlledByAI()
addResources: minerals=1

[graphics]
imageScale: 1.1
total_frames: 1
image:  queen.png
image_wreak:  NONE
image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:2
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 60
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

[attack]
isMelee: true
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 20
turretTurnSpeed: 3
maxAttackRange: 9
shootDelay: 30

[leg_1]
x: -8
y: 22
hidden: true
attach_x: 0
attach_y: 16
moveSpeed: 1.3
rotateSpeed: 6
resetAngle:5
heightSpeed: 0.8
dust_effect: false
holdDisMin: 1
holdDisMax: 1
image_leg:  leg.png

[leg_2]
x: 8
y: 22
attach_x: 0
attach_y: 16
copyFrom: 1

[leg_3]
x: -12
y: 15
attach_x: 0
attach_y: 16
copyFrom: 1

[leg_4]
x: 12
y: 15
attach_x: 0
attach_y: 16
copyFrom: 1

[leg_5]
x: -12
y: 8
attach_x: 0
attach_y: 16
copyFrom: 1

[leg_6]
x: 12
y: 8
attach_x: 0
attach_y: 16
copyFrom: 1

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0

[ai]
buildPriority: 0.26
noneInBaseExtraPriority: 0.9
noneGlobalExtraPriority: 0.3
maxEachBase: 1

#Queen by Essential Strategy