#Nest by Luke Hoschke
#Edited by Essential Strategy

[core]
copyFrom: nest.ini
name: openNest
price:0, cash=400
maxHp: 800
isBio: false
overrideAndReplace: NONE
displayText: Open Next
displayText_ru: Открытое гнездо
displayDescription: -Generates air insects
displayDescription_es: -Genera insectos de aire
constructionFootprint: -1,-1,1,1
softCollisionOnAll: 4
exit_x:0
exit_y:-1
isUnrepairableUnit: false
unitsSpawnedOnDeath: kusaka*7
canBuild_1_name: setRally, mosquito, fly, pickup, marauder, bee

[action_open]
convertTo: NONE
isVisible: false

[action_upgradeT2]
convertTo: openNestT2
price:0, cash=1000, minerals=500

[graphics]
image:        nest_open.png
image_back:   NONE
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_scale_end:1

[ai]
useAsBuilder: false

#Nest by Luke Hoschke