
[core]
#cOPY
showInEditor: false
name: def_flare
class: CustomUnitMetadata
price: ccredits=1
maxHp: 9999
mass: 9000
techLevel: 1
buildSpeed: 1
#availableInDemo: true
radius: 10
displayRadius: 10
fogOfWarSightRange: 1
isBio: false
isBuilding: true
energyMax:4
energyRegen: 0
transportSlotsNeeded: -1
#LIGHT IT U
#fireTurretXAtSelfOnDeath: 3
isUnselectable:true
canNotBeGivenOrdersByPlayer:true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked:true
numBitsOnDeath: 0
#createOnAggressiveTeam: true
dieOnZeroEnergy: true
explodeOnDeath: false
hideScorchMark: true
showOnMinimap: false
#================================
ignoreInUnitCapCalculation: true
#================================



[hiddenAction_f]
autoTrigger: if self.isAtGroundHeight
deleteSelf: true

[graphics]
#image_back: SHARED:blank.png
drawLayer: top
total_frames: 1
image: 6x6_flare.png 
image_shadow: AUTO
showHealthBar: false
showEnergyBar:true
[attack]
canAttack: false
maxAttackRange: 110
[turret_laserDefence]
#laserdefence
x: 0
y: 0
canShoot: false
invisible: true

laserDefenceEnergyUse: 1
size:0


[animation_idle]
onActions : idle

arm1_0s:{alpha:0.2}
arm1_1.5s:{alpha:0.6}
arm1_2.6s:{alpha:0.8}
arm1_3.9s:{alpha:0.6}
arm1_5.9s:{alpha:0.2}

KeyframeTimeScale: 0.5


[arm_1]
x: 0
y: 0
image_end_shadow: flare_light.png
image_end: flare_light.png 
alpha: 0
drawOverBody: true

[arm_2]
x:0
y:0
image_end_teamColors: true
image_end: countermeasure_rotor.png 
#drawOverBody: true
spinRate:15
image_end_shadow:SHADOW:countermeasure_rotor.png 

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 0
startingHeightOffset: 35
targetHeight:0
#targetHeightDrift:0

heightChangeRate:0.03
