#Firefly by Static Charge Red Field
#Edited by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: firefly
class: CustomUnitMetadata
price: credits=2200, minerals=600
maxHp: 315
mass: 1400
displayText: Firefly
displayText_es: Luciérnaga
displayDescription: -Electric attack\n-Attacks ground only\n-Self regenerate
displayDescription_es: -Ataque eléctrico\n-Ataca solo a tierra\n-Auto-regeneración
techLevel: 2
buildSpeed: 0.0008
#availableInDemo: true
radius: 8
isBio: true
isBug: true
isUnrepairableUnit: true
numBitsOnDeath: 8
selfRegenRate:0.1
softCollisionOnAll: 12
explodeOnDeath: false
explodeOnDeathGroundCollosion: false


[graphics]
total_frames: 2
image:        firefly.png
image_wreak:  firefly_dead.png
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 2
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 18
turretTurnSpeed: 9
maxAttackRange: 190
shootDelay: 120

[turret_1]
x: 0
y: -28
shoot_sound: bug_attack
shoot_sound_vol:0.05
shoot_light:#FFccCCEE
chargeEffectImage: electric_charge.png
warmup:25

[projectile_1]
largeHitEffect: true
areaDamage: 130
areaRadius: 60
directDamage: 70
targetGround:true
targetGroundSpread: 15
life: 100
speed:3.5
lightSize:1.5
color:yellow
lightColor: yellow
drawSize: 1
shieldDamageMultiplier: 1.5
buildingDamageMultiplier: 0.5
explodeEffect:CUSTOM:explosionSound,CUSTOM:sparks2*8,CUSTOM:sparks*4,smallExplosion
explodeEffectOnShield:CUSTOM:sparks*2

[effect_explosionSound]
alsoPlaySound: missile_hit
life:30
attachedToUnit: false
priority: veryhigh

[effect_sparks2]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 1.6
ySpeedRelativeRandom: 1.6
hSpeed: 2
color: #ffffff00
image: particle2.png
priority: verylow

[effect_sparks]
attachedToUnit: false
life: 150
physics: true
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
hSpeed: 1
color: #ffffff00
image: particle2.png
priority: verylow

[movement]
movementType: AIR
moveSpeed: 1.4
moveAccelerationSpeed: 0.04
moveDecelerationSpeed: 0.07
maxTurnSpeed: 5.5
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

#Firefly by Static Charge Red Field