#Cavern by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: cavern
class: CustomUnitMetadata
price: 40000
maxHp: 2000
mass: 10000
displayText: Cavern
displayText_ru: Пещера
displayDescription: -Destruction massive wepon\n-Spreads a poison cloud in the battlefield
displayDescription_es: -Arma de destrucción masiva\n-Segrega una nube de veneno en el campo de batalla
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1
techLevel: 1
buildSpeed: 0.002
selfBuildRate: 0.002
#availableInDemo: true
radius: 30
isBio: true
isBug: true
isUnrepairableUnit: true
isBuilding: true
selfRegenRate: 0.1
softCollisionOnAll: 3
unitsSpawnedOnDeath: kusaka*3

[action_buildFlake]
price: credits=20000, crystalline=4000
text: Generate Flake
text_es: Generar Copo
description: -Unlimited range\n-Spreads acid on the terrain\n-Maximum 3 in storage
description_es: -Rango ilimitado\n-Esparce ácido en el terreno\n-Máximo de 3 en almacén
displayType: upgrade
buildSpeed: 50s
pos: 0
isActive:if self.ammoIncludingQueued(lessThan=3)
addResources: ammo=1

[action_launchFlake]
fireTurretXAtGround: 1
price: ammo=1
text: Launch Flake
text_es: Lanzar Copo
description: i:gui.actions.launchNuke.description
displayType: action
buildSpeed: 3s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true

[graphics]
total_frames: 1
image:        cavern.png
image_back:   NONE
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 150
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 1000000

[turret_1]
x: 3
y: 0
canShoot: false
idleDir:0
#shoot_sound: nuke_launch
#shoot_sound_vol:0.27
shoot_light: #FFEECCCC
projectile: flakeProjectile
size: 1
turnSpeed: 40
shoot_flame:custom:nukeLaunch_wave, custom:nukeLaunch_light
limitingMinRange: 300

[projectile_flakeProjectile]
image: flake.png
drawSize: 0.8
tags: nuke
directDamage: 123
life: 99999
spawnUnit: gas
speed: 0.2
targetSpeed: 3
targetSpeedAcceleration:0.04
largeHitEffect: true
ballistic: true
ballistic_delaymove_height:80
ballistic_height: 110
targetGround: true
areaDamage: 1000
areaRadius: 100
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
areaExpandTime:75
deflectionPower:-1
shouldRevealFog: true
nukeWeapon: true
lightColor: green
lightSize: 1.1
friendlyFire: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate:4

[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
color: green
fadeInTime:5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6
drawUnderUnits:false
atmospheric:true
dirOffsetRandom:180
shadow:true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

[effect_nukeLaunch_wave]
priority:high
stripIndex: shockwave
life: 50
scaleFrom: 0.5
scaleTo: 2.5

[effect_nukeLaunch_light]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FFFFFF
scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.7
drawUnderUnits:false

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0

[ai]
buildPriority: 0.01
noneInBaseExtraPriority: 0.04
noneGlobalExtraPriority: 0.1
maxEachBase: 0
ai_upgradePriority: 0.2

#Cavern by Essential Strategy