#Giant Wasp by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: giantWasp
displayText: Giant Wasp
displayText_es: Avispa Gigante
displayDescription: -Attacks ground only\n-Long range\n-Self regenerate
displayDescription_es: -Ataca a tierra únicamente\n-Amplio rango\n-Auto-regeneración
price:0, biomass=1600
maxHp: 1025
mass: 2000
techLevel: 2
selfRegenRate:0.1
buildSpeed: 0.0008
radius: 14
isBio: true
isBug: true
softCollisionOnAll: 24
explodeOnDeath: false
explodeOnDeathGroundCollosion: false


[graphics]
imageScale: 0.8
total_frames: 2
image:        giant_wasp.png
image_wreak:  giant_wasp_dead.png
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 2
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3
lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 20
maxAttackRange: 400
shootDelay: 150
turretRotateWithBody: true

[turret_1]
x: 0
y: 0
shoot_flame: smoke
canShoot: true
recoilOffset: -3
recoilOutTime: 6
recoilReturnTime: 18

[projectile_2]
areaDamage: 30
areaRadius: 60
targetGround: true
targetGroundSpread: 15
life: 500
largeHitEffect: true
speed: 6
lightSize:1.5
color:green
lightColor: green
drawSize: 2
shieldDamageMultiplier: 1.1

[movement]
movementType: AIR
moveSpeed: 0.9
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.08
maxTurnSpeed: 3
turnAcceleration: 0.08
targetHeightDrift: 1.5
moveSlidingMode :true
moveIgnoringBody: false
moveSlidingDir:  181
reverseSpeedPercentage:0

#Giant Wasp by Essential Strategy