[core]


name:Ek_RedCurtain
displayText:RedCurtain
displayText_zh:红穹移动防空平台
displayDescription:Experimental anti-aircraft\tank-equipped with quad high-power laser cannon\can only target the air\single Body High Damage
displayDescription_zh:实验型防空坦克\n搭载四联大功率激光加农炮\n只能对空\n单体高伤害
class:CustomUnitMetadata
price:120000,experimental=4000
maxHp:4500
maxShield:2000
armour:15
armourMinDamageToKeep:0
mass:5000
techLevel:2
buildSpeed:75s
experimental:true
radius:28
displayRadius:35
tags:Intercept,EkAntiStelth,EkMegatank
isBio:false
softCollisionOnAll:0
fogOfWarSightRange:30
transportSlotsNeeded:5
[graphics]
total_frames:4
icon_zoomed_out:unit_icon_eternity.png
image:eternity_tank.png
image_wreak:eternity_dead.png
image_turret:eternity_turret.png
image_shadow:AUTO
shadowOffsetX:2
shadowOffsetY:2
animation_moving_start:0
animation_moving_end:3
animation_moving_speed:3.5
teamColorsOnTurret:true
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:false
canAttackUnderwaterUnits:false
turretSize:16
turretTurnSpeed:1
maxAttackRange:770
shootDelay:450
[turret_1]
x:0
y:0
invisible:true
turnSpeed:1.5
canShoot:false
recoilOffset:1
[turret_2]
x:-5
y:11
attachedTo:1
slave: true
invisible: true
projectile: 1
turnSpeed: 5.0
#turnSpeedAcceleration: 1.5
shoot_sound:plasma_fire
shoot_sound_vol:0.5
shoot_flame:CUSTOM:lightSlowFade
#shoot_light:#FFff0000
canShoot:true
recoilOffset: -2.5
recoilOutTime: 2
recoilReturnTime: 18
warmup:60
altProjectile:large
altProjectileCondition: if numberOfUnitsInTeam(withTag='EkMegatank',greaterThan=3,withinRange=400)
chargeEffectImage: mech_laser_charge.png
[turret_3]
copyFrom:2
x:5
y:11
warmup:40
warmupCallDownRate:1
projectile:1
linkDelayWithTurret:2
[turret_4]
copyFrom:2
x:-10
y:9
warmup:80
warmupCallDownRate:1
projectile:1
linkDelayWithTurret:2
[turret_5]
copyFrom:2
x:10
y:9
warmup:120
warmupCallDownRate:1
projectile:1
linkDelayWithTurret:2
[turret_6]
invisible:false
x:0
y:0
attachedTo:1
slave:true
canShoot:false
[projectile_1]
directDamage: 2000
life: 10
largeHitEffect: true
instant:true
laserEffect:true
instantReuseLast:true
color:#6fff0000
explodeEffect: CUSTOM:lightSlowFade, CUSTOM:laserExplosion
[projectile_large]
@copyFromSection:projectile_1
directDamage:1100
[effect_lightSlowFade]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FF0000
scaleFrom: 0.3
scaleTo: 0.2
alpha: 1.7
[effect_laserExplosion]
image: laser_explode.png
life: 40
fadeOut: true
attachedToUnit: true
color: #FF0000
dirOffsetRandom:360
alpha: 0.7
[movement]
movementType:LAND
moveSpeed:0.50
moveAccelerationSpeed:0.07
moveDecelerationSpeed:0.17
maxTurnSpeed:1.0
turnAcceleration:0.125
moveSlidingMode:false
moveIgnoringBody:false
[ai]
upgradedFrom:EkChassis
ai_upgradePriority:0.4