#Aquatic Cricket by Essentiao Strategy

[core]
copyFrom: aquatic_cricket_surface.ini
showInEditor:false
name: aquaticCricketSubmerged
effectOnDeath: NONE

[action_submerge]
convertTo: aquaticCricketSurface
text: Emerge
text_es: Emerger
description: -Surface unit
description_es: -Saca a flote a la unidad

[graphics]
splastEffect: false
animation_attack_start: 0
animation_attack_end: 0
animation_attack_speed: 1
animation_attack_scale_start:1
animation_attack_scale_end: 1

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
turretSize: 0
turretTurnSpeed: 10
maxAttackRange: 150
shootDelay: 150

[turret_1]
canShoot: false

[turret_2]
x: 0
y: 0
projectile: smallCricket

[projectile_smallCricket]
directDamage: 0
speed: 5
drawSize:0
life: 0
targetGround: true
spawnUnit: smallCricket*1
explodeEffect: NONE
explodeOnEndOfLife:true

[leg_1]
hidden: true

[leg_2]
hidden: true

[leg_3]
hidden: true

[leg_4]
hidden: true

[leg_5]
hidden: true

[leg_6]
hidden: true

[movement]
movementType: WATER
moveSpeed: 0.5
moveAccelerationSpeed: 0.015
moveDecelerationSpeed: 0.05
targetHeight: -8

#Aquatic Cricket by Essential Strategy