#Aquatic Cricket by Essentiao Strategy

[core]
copyFrom: aquatic_cricket.ini
showInEditor:false
name: aquaticCricketSurface
transportUnitsCanUnloadUnits: false
transportUnitsKillOnDeath: true

[action_water]
autoTrigger: if not self.isOverwater()
convertTo: aquaticCricket
buildSpeed: 0s
isVisible: false

[action_submerge]
convertTo: aquaticCricketSubmerged
displayType: action
price:0, cash=0
text: Submerge
text_es: Sumergir
description: -Dive unit underwater
description_es: -Sumerge a la unidad bajo el agua
buildSpeed: 0s
whenBuilding_cannotMove: true
pos:-1
highPriorityQueue: true

[graphics]
splastEffect: true

[leg_1]
x: 0
y: 0
attach_x: 0
attach_y: 0
hidden: true
lockMovement: true

[leg_2]
x: 0
y: 0
attach_x: 0
attach_y: 0
copyFrom: 1

[leg_3]
x: 0
y: 0
attach_x: 0
attach_y: 2
copyFrom: 1

[leg_4]
x: 0
y: 0
attach_x: 0
attach_y: 2
copyFrom: 1

[leg_5]
x: 0
y: 0
attach_x: 0
attach_y: -2
copyFrom: 1

[leg_6]
x: 0
y: 0
attach_x: 0
attach_y: -2
copyFrom: 1

[movement]
moveSpeed: 0.8
moveAccelerationSpeed: 0.016
moveDecelerationSpeed: 0.06
targetHeight:0.1
targetHeightDrift: 0.1
maxTurnSpeed: 0.8
turnAcceleration: 0.05
moveIgnoringBody: false

#Aquatic Cricket by Essential Strategy