#Small Cricket by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: smallCricket
class: CustomUnitMetadata
price:0, cash=0
maxHp: 135
mass: 500
displayText: Small Cricket
displayText_es: Grillo Pequeño
displayDescription: -Very small unit, weak than the aquatic cricket but also more fast
displayDescription_es: -Unidad muy pequeña, más débil que el grillo acuático pero también más rápida
techLevel: 1
buildSpeed: 0.005
#availableInDemo: true
radius: 6
isBio: true
isBug: true
isUnrepairableUnit: true
selfRegenRate:0.1
softCollisionOnAll: 12
dieOnConstruct: true

[graphics]
total_frames: 2
imageScale: 0.8
image:    small_cricket.png
image_wreak:  NONE
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 80
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true
animation_attack_start: 0
animation_attack_end: 1
animation_attack_speed: 8
animation_attack_scale_start: 1
animation_attack_scale_end:0.97
animation_attack_pingPong: true
lock_body_rotation_with_main_turret: true

[attack]
isMelee: true
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
isFixedFiring: true
turretSize: 8
turretTurnSpeed: 2
maxAttackRange: 9
shootDelay: 30
aimOffsetSpread: 0

[turret_1]
x: 0
y: 0
recoilOffset: 6
recoilOutTime: 6
recoilReturnTime: 18

[projectile_1]
life: 50
instant: true
directDamage: 25
explodeEffect: NONE

[movement]
movementType: WATER
moveSpeed: 0.8
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.03
targetHeight: -8
targetHeightDrift: 0.4
maxTurnSpeed: 2.5
turnAcceleration: 0.05
reverseSpeedPercentage:0

#Small Cricket by Essential Strategy