#Bug Melee Large by Luke Hoshke
#Edited by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: hornedBeetle
class: CustomUnitMetadata
price:0, cash=1200
maxHp: 800
mass: 5000
isUnrepairableUnit: true
overrideAndReplace: bugMeleeLarge
displayText: Horned Beetle
displayText_es: Escarabajo Cornudo
displayDescription: -Strong beetle\n-Powerful melee attack\n-Self regenerate
displayDescription_es: -Escarabajo fuerte\n-Potente ataque cuerpo a cuerpo\n-Auto-regeneración
techLevel: 1
buildSpeed: 0.003
#availableInDemo: true
radius: 14
isBio: true
isBug: true
transportSlotsNeeded: 2
selfRegenRate:0.1
softCollisionOnAll: 15
numBitsOnDeath: 5

[action_evolve]
convertTo: goliathBeetle
price:0, biomass=10000
text: Metamorphosis
text_es: Metamorfosis
description: -Increases HP and damage\n-Adds area damage and allows it to walk over mountains
description_es: -Incrementa los PV y el daño\n-Añade daño en área y le permite caminar sobre montañas
displayType: upgrade
buildSpeed: 16s
pos: 0
whenBuilding_cannotMove: true
canPlayerCancel: false

[graphics]
total_frames: 5
imageScale: 1.5
image:        bug_melee_large.png
image_wreak:  bug_melee_large_dead.png
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true
animation_attack_start: 3
animation_attack_end: 4
animation_attack_speed: 4
lock_body_rotation_with_main_turret: true

[attack]
isMelee: true
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 20
turretTurnSpeed: 3
maxAttackRange: 9
shootDelay: 30

[turret_1]
x: 0
y: 0
shoot_sound: ROOT:assets/sounds/bug_attack_medium.ogg
shoot_sound_vol: 0.4
shoot_light:#FFccCCEE
recoilOffset: 3
recoilOutTime: 6
recoilReturnTime: 18

[projectile_1]
directDamage: 31
life: 50
instant: true
explodeEffect: NONE
armourIgnoreAmount: 20

[movement]
movementType: LAND
moveSpeed: 1.7
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 8.5
turnAcceleration: 0.5
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

#Bug Melee Large by Luke Hoshke