[core]
name:      yakuzBuilder
copyFrom: ROOT:assets/templates/builder.template
displayText: Имперский Строитель 
displayDescription: -Строит и ремонтирует здания\n-Не может атаковать

[canBuild_base]
name: yakuzCC,EkJapanFlag
pos:100

[graphics]
total_frames: 3

imageScale: 0.7
image:        nibblercrab.png
image_turret: NONE

repairEffectRate: 50
reclaimEffectRate: 50

image_shadow: NONE

shadowOffsetX:2
shadowOffsetY:2

icon_zoomed_out: unit_icon_builder.png

splastEffect: true

animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 60
animation_idle_scale_start:1
animation_idle_scale_end:1.02
animation_idle_pingPong: true
#animation_attack_start: 2
#animation_attack_end: 5
#animation_attack_speed: 4

lock_body_rotation_with_main_turret: true
#[animation_attack_I]
#blendIn: 0.5s
#blendOut: 0.5s

#KeyframeTimeScale: 0.15

#left talon
#arm4_0s: {x:2, y:0, dir:0}
#arm4_1s: {x:2, y:2, dir:120}
#arm4_3s: {x:0, y:0, dir:6}

#right talon


#arm5_0s: {x:-2, y:0, dir:0}
#arm5_1s: {x:-2, y:2, dir:-120}
#arm5_3s: {x:0, y:0, dir:-6}

#[arm_4]
#left talom#x: -7.7
#y: 7.5#image_end: lefttalon.png
#image_end_teamColors: true
#drawOverBody: true
#drawDirOffset: 0
#moveSpeed: 6
#rotateSpeed: 6
#[arm_5]
#right talon
#x: 7.7
#y: 7.5
#image_end: righttalon.png
#image_end_teamColors: true
#drawOverBody: true
#drawDirOffset: 0
#moveSpeed: 6
#rotateSpeed: 6

[arm_1]
x: 0
y: 0
image_end:tornadix.png
image_end_teamColors: true
drawOverBody: true

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false


[turret_1]
x: 0
y: 0
invisible: true
canShoot: false
isMainNanoTurret: true
canOnlyAttackUnitsWithTags: building, mechanical


[movement]
movementType: LAND
moveSpeed: 0.80
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 1
maxTurnSpeed: 12
turnAcceleration: 0.7
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.3


[ai]
useAsBuilder: true