
[core]
copyFrom: ROOT:ASSETS/templates/factory.template
name: EkexperimentalFactory
class: CustomUnitMetadata
price: 11000
maxHp: 3200
mass: 9000
overrideAndReplace: experimentalLandFactory
displayText:Experimental factory
displayDescription:-Can produce experimental units
displayText_ru:Экспериментальный завод
displayDescription_ru:-Производит экспериментальные единицы
footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,4


techLevel: 1
buildSpeed: 240s
#availableInDemo: true

radius: 55
#displayRadius: 25
isBio: false
isBuilding: true

explodeTypeOnDeath: building


exit_x:0
exit_y:-1
exit_moveAwayAmount:160

[canBuild_1]
name:setRally
pos:-1

[canBuild_heavyTanksTech]
name:experimentalTank,experimentalHovertank,experimentalSpider,modularSpider,EkChassis
isVisible: if self.globalTeamTags(includes='${tech_tanks3}')
pos:1

[canBuild_lightAircraftTech]
name:fireBee
isVisible: if self.globalTeamTags(includes='${tech_aircraft1}')
pos:2

[canBuild_advancedAircraftTech]
name:experimentalDropship, vulture
isVisible: if self.globalTeamTags(includes='${tech_aircraft2}')
pos:3

[canBuild_mechTech]
name:EkWardenMech,EkBastion,EkElectrostormMech,EkRavagerMech,EkMarshallMech,EkVindicatorMech,EkTitanMech1,EkFenrirMech,EkThetaMech,Ek_EXP_flak_mech
isVisible: if self.globalTeamTags(includes='${tech_mech}')
pos:4

[graphics]
total_frames: 1

image:        experimental_unit_factory_front.png
image_back:   experimental_unit_factory_base.png
image_wreak:  experimental_unit_factory_dead.png

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1





[ai]
buildPriority: 0.02
noneInBaseExtraPriority: 0.011
noneGlobalExtraPriority: 0.05
maxEachBase: 3
