#Bug Spore by Luke Hoshke
#Edited by Essential Strategy

[core]
copyFrom:ROOT:ASSETS/templates/bio.template
name: spore
class: CustomUnitMetadata
price: 100
maxHp: 160
mass: 500
displayText: Spore
displayText_ru: Спора
displayDescription: -Can transmute into structures\n-Self regenerate
displayDescription_es: -Может превращаться в структуры\n-Имеет регенирацию
techLevel: 1
overrideAndReplace: bugSpore
buildSpeed: 0.005
#availableInDemo: true
radius: 8
displayRadius: 10
isBio: true
isBug: true
isBuilder: true
isUnrepairableUnit: true
selfRegenRate:0.1
softCollisionOnAll: 12
dieOnConstruct: true
canRepairBuildings: true
canRepairUnits : false
nanoRange: 12
nanoBuildSpeed: 1
nanoRepairSpeed: 0.2
nanoRangeForRepairIsMelee: true
nanoRangeForReclaimIsMelee: true
canReclaimResources: true
canBuild_1_name: bugExtractorMod, bugNest, HealPool, cavern
canBuild_1_pos:  0

[hiddenAction_moveToUnloadCrystal]
buildSpeed: 0s
convertTo: sporeCrystal
autoTrigger: if self.hasActiveWaypoint(type='reclaim') and self.hasResources(localCrystal=10)
addWaypoint_type: touchTarget
addWaypoint_prepend: true
addWaypoint_target_nearestUnit_tagged: crystalDropoff
addWaypoint_target_nearestUnit_team: own
addWaypoint_triggerActionIfFailed: findFailed
pos: 1

[hiddenAction_findFailed]
clearActiveWaypoint: true

[hiddenAction_unloadCrystal]
autoTriggerOnEvent: touchTargetSuccess
alsoTriggerAction: getCrystal
convertTo: spore

[hiddenAction_getCrystal]
requireConditional: if self.hasResources(localCrystal=10)
addResources: localCrystal=-10
addResourcesScaledByAIHandicaps: crystalline=10

[graphics]
total_frames: 6
image:        bug_spore.png
image_wreak:  bug_spore_dead.png
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 4
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true
repairEffect: NONE
reclaimEffect: NONE
lock_body_rotation_with_main_turret: true

[animation_harvest]
onActions: reclaim
body_0s: {frame:3}
body_0.5s: {frame:4}
body_0.7s: {frame:5} 
body_0.8s: {frame:5}

[attack]
isMelee: true
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0
isFixedFiring: true

[turret_1]
x: 0
y: 0
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
isMainNanoTurret: true

[movement]
movementType: LAND
moveSpeed: 1.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 6.5
turnAcceleration: 0.4
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
reverseSpeedPercentage:0

[ai]
useAsBuilder: true

#Bug Spore by Luke Hoshke