
[core]
copyFrom:ROOT:assets/templates/bio.template
name: bugHive
class: CustomUnitMetadata
overrideAndReplace: bugHive
price: 1
maxHp: 12000
mass: 10000
displayText: Hive
displayText_ru: Улей
displayDescription: -Generates ground insects\n-Cam metamorphosis to the hive queen
displayDescription_ru: -Главная база жуков\n-Может превратить в королеву улья
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,3
techLevel: 1
generation_resources: biomass=25
energyMax:10
energyRegen:0.0002
energyNeedsToRechargeToFull: true
unitsSpawnedOnDeath: kusaka*80
#availableInDemo: true
radius: 30
isBio: true
isBug: true
isUnrepairableUnit: true
isBuilding: true
selfRegenRate:0.1
softCollisionOnAll: 3
exit_x:0
exit_y:-1
tags: hive, bio, bug

[action_spore]
isActive: if true
unitShownInUI: spore
produceUnits: spore
price: biomass=200
textAddUnitName: spore
descriptionAddFromUnit: spore
descriptionAddUnitStats: spore
buildSpeed: 8s
pos: 0.1
displayType: upgrade

[canBuild_1]
name: setRally, smallBeetle, spitter
pos: 0.2

[action_metatoqeen]
convertTo: Queen
price: credits=10000000, minerals=600000, alloys=100000
text: Metamorphosis to queen
text_ru: Превращение в королеву
description: -Позволяет превратить улей в королеву улья\n-Королева улья имеет огромный урон по воздуху и земле\n-Может передвигаться по воде
description_es: -Permite al nido generar insectos de aire, pero no puede generar insectos de tierra
displayType: upgrade
buildSpeed: 180s
pos: 0

[action_scan]
text:Сканирование
price:credits=1500,energy=5,minerals=200
buildSpeed:2s
highPriorityQueue:true
description:-Сканирование выбранной области
isGuiBlinking:false
iconImage:scan.png
displayType:rally
fireTurretXAtGround:1
onlyOneUnitAtATime:true
allowMultipleInQueue:false

[turret_1]
showRangeUIGuide:false
x: 2.5
y: -10
projectile:1
image:SHARED:blank.png
recoilOffset: 0
recoilOutTime: 0
recoilReturnTime: 0
shoot_flame:NONE
shoot_sound:NONE
turnSpeedAcceleration: 1.0
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits: false
aimOffsetSpread: 0
idleSpin:2.5
limitingRange:99999

[projectile_1]
areaDamage:0
areaRadius:0
deflectionPower:-1
life:1
explodeEffect:CUSTOM:scan
image:SHARED:blank.png
drawSize: 0
spawnUnit:vision
instant:true
explodeOnEndOfLife:true

[effect_scan]
life:240
fadeOut: true
fadeInTime:5
priority:critical
attachedToUnit:false
scaleFrom:2.5
scaleTo:3
dirOffsetRandom:180
alpha: 1.0
atmospheric:true
dirSpeed:0.25
showInFog:true
image:detect.png
drawUnderUnits:false
alsoPlaySound:detect.ogg:0.6


[graphics]
total_frames: 1
image:        hive.png
image_wreak:  NONE
image_shadow: NONE
imageScale: 1.3
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 300
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true

[animation_build]
onActions: underConstructionWithLinkedBuiltTime
blendOut: 1s
body_0: {scale:0}
body_1: {scale:1.2}

#[animation_upgrade]
#blendIn: 1s
#blendOut: 1s
#body_0: {scale:1}
#body_1: {scale:1.4}

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 999999

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0

[ai]
buildPriority: 0.25
noneInBaseExtraPriority: 0.2
noneGlobalExtraPriority: 0.3
maxEachBase: 1