[core]

name:EkApollo
displayText:Apollo Attack aircraft
displayText_zh:阿波罗级实验攻击机
class:CustomUnitMetadata
price:0, cash=200000,alloys=4000
maxHp:6000
armour:20
mass:15000
techLevel:2
buildSpeed:60s
radius:64
isBio:false
softCollisionOnAll:25
#energyMax:20
#energyRegen:0.015
#energyNeedsToRechargeToFull:true

[graphics]
total_frames:2
image:飞机.png
image_wreak:飞机dead.png
image_turret:NONE
image_shadow:auto
shadowOffsetX:2
shadowOffsetY:2
animation_idle_start:0
animation_idle_end:0
animation_idle_speed:6
animation_moving_start:1
animation_moving_end:1
animation_moving_speed:6
#lock_shadow_rotation_with_main_turret: true
#lock_body_rotation_with_main_turret: false
teamColorsOnTurret:true
lock_body_rotation_with_main_turret:true
movementEffect:CUSTOM:EkJetwash,CUSTOM:EkRotordust,CUSTOM:EkJetfire,CUSTOM:尾迹云左,CUSTOM:尾迹云右
movementEffectRate:4
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
aimOffsetSpread:0.6
turretMultiTargeting:true
turretRotateWithBody:true
turretTurnSpeed:15
[turret_1]
x:-30
y:-20
#attachedTo:cannonbase
#slave:true
projectile:1
turnSpeed:0
#image:at_rocket.png
shoot_sound:导弹发射.ogg
shoot_sound_vol:0.25
#shoot_flame:CUSTOM:explode_big.png
#shoot_light:#FFff925c
warmup:0
canAttackMaxAngle:366
canAttackLandUnits:true
limitingRange:450
delay:1.5s
size:0
[turret_2]
x:30
y:-20
copyFrom:1
#slave:true
#shoot_flame:large
#shoot_light:#FFff925c
warmup:6
delay:1.4s
size:0

[turret_3]
x:-40
y:-20
copyFrom:1
projectile:2
#shoot_flame:large
#shoot_light:#FFff925c
warmup:1.5s
canAttackLandUnits:true
canAttackFlyingUnits:true
limitingRange:450
delay:2s

[turret_4]
x:40
y:-20
copyFrom:2
projectile:2
canAttackLandUnits:true
canAttackFlyingUnits:true
limitingRange:450
warmup:1.6s
delay:1.9s

[turret_5]
x:5
y:40
#image:炮管.png
#attachedTo:cannonbase
#slave:true
height:-5
projectile:3
turnSpeed:1
shoot_sound:开火.ogg
shoot_sound_vol:0.2
shoot_flame:CUSTOM:弹壳
shoot_light:#FFff925c
limitingRange:250
canAttackMaxAngle:366
delay:0.07s
size:0
idleSpin:5
[projectile_1]
life:600
speed:0
targetSpeed:4
targetSpeedAcceleration:0.2
frame:2
areaDamage:200
areaRadius:50
largeHitEffect:true
trailEffect:true
autoTargetingOnDeadTarget:true
wobbleAmplitude:0.5
wobbleFrequency:0.5s
turnSpeedWhenNear:35
#lightCastOnGround: true
image:at_rocket.png
drawSize:1
deflectionPower:2
tags:EKAmmo

[projectile_2]
life:600
speed:0
targetSpeed:5
targetSpeedAcceleration:0.55
frame:2
areaDamage:700
areaRadius:50
explodeEffect:largeExplosion,shockwave
largeHitEffect:true
trailEffect:true
autoTargetingOnDeadTarget:true
wobbleAmplitude:0.5
wobbleFrequency:0.5s
turnSpeedWhenNear:35
#lightCastOnGround: true
image:at_rocket.png
drawSize:1
deflectionPower:2
tags:EKAmmo
ballistic:true
[projectile_3]
life:180
speed:10
frame:2
directDamage:50
largeHitEffect:true
autoTargetingOnDeadTarget:true
#lightCastOnGround: true
image:机炮.png
drawSize:0.5
explodeEffect:CUSTOM:机炮烟
tags:EKAmmo
deflectionPower:1

[effect_EkJetwash]
image:jetwash.png
createWhenOverLand:false
delayedStartTimer:15
life:60
spawnChance:0.5
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.25
scaleTo:1.5
alpha:0.4
hOffset:-40
ySpeedRelative:0.3
dirOffsetRandom:5
dirSpeedRandom:0.05
atmospheric:true
[effect_EkRotordust]
image:rotorwash.png
createWhenOverLiquid:false
life:40
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:2
scaleFrom:0.5
scaleTo:2.5
alpha:1
color:#916C5B
drawUnderUnits:true
hOffset:-40
dirOffsetRandom:180
dirSpeedRandom:0.6
atmospheric:true
[effect_尾迹云左]
image:尾迹云.png
life:80
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.8
scaleTo:0.8
alpha:0.4
ySpeedRelative:-0.3
yOffsetRelative:-40
xOffsetRelative:-72
atmospheric:true
[effect_尾迹云右]
image:尾迹云.png
life:80
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.8
scaleTo:0.8
alpha:0.4
ySpeedRelative:-0.3
yOffsetRelative:-40
xOffsetRelative:76
atmospheric:true

[effect_弹壳]
life:200
image:弹壳.png
total_frames:1
scaleFrom:0.8
scaleTo:0.7
alpha:20
attachedToUnit:false
drawUnderUnits:true
physicsGravity:2
physics:true
fadeOut:true
dirOffsetRandom:10
xSpeedRelativeRandom:0.3
ySpeedRelativeRandom:0.3
xSpeedRelative:1
ySpeedRelative:-0.5
hSpeedRandom:0.5
hSpeed:2.5
xOffsetRelative:3
yOffsetRelative:-10
[effect_机炮烟]
life:30
image:机炮烟.png
scaleFrom:0.5
scaleTo:1.25
alpha:0.6
total_frames:4
createWhenOverLiquid:false
createWhenOffscreen:true
createWhenOverLand:true
fadeOut:true
drawUnderUnits:true
xSpeedRelativeRandom:0
ySpeedRelativeRandom:0.3
xSpeedRelative:0
ySpeedRelative:1
hOffset:0.1
hSpeed:0.1

[effect_EkJetfire]
image:jetflame1.png
life:16
fadeOut:true
attachedToUnit:false
fadeInTime:3
scaleFrom:1
scaleTo:2.5
alpha:0.8
xSpeedRelativeRandom:0.1
yOffsetRelative:-50
xOffsetRelative:-1
ySpeedRelative:1
dirOffsetRandom:15
drawUnderUnits:false
[movement]
movementType:AIR
moveSpeed:1.3
moveAccelerationSpeed:0.09
moveDecelerationSpeed:0.05
#targetHeight:15
maxTurnSpeed:2.0
turnAcceleration:0.12
moveSlidingMode:true
moveIgnoringBody:true
reverseSpeedPercentage:0.3
slowDeathFall:true
joinsGroupFormations:true