[core]
name:      reichBuilder
copyFrom: ROOT:assets/templates/builder.template
displayDescription: \n основной рабочий ЧеликСтана \n любит ехать на panzerkampfagen IV
displayText: Рабочий

[canBuild_1]
name: extractor,c_turret_t1, c_antiAirTurret, landFactory, airFactory, EkInfantryFactoryT1, mechFactory,EkSupportFactory, EkHelipad, EkBarricade1Y,EkBarricade2Y, EkBarricade1X, EkBarricade2X, EkResourceDrill , EkConcreteblock,EkTanktrap,EkTowerRifleman,EkTurretEmpty,EkBunkerTinyMinigun,Ek_radar,Ek_radarturret,EkTech,experimentalLandFactory,laserDefence, EkHarvesterSolar, seaFactory
pos:0

[canBuild_2]
name: antiNukeLaucher, nukeLaucher, EkHarvesterFactory
pos:99

[canBuild_base]
name: reichCC, EkOZDFlag
pos:100

[graphics]
total_frames: 1

imageScale: 0.7
image:        body2.png
image_wreak:  body3.png

icon_zoomed_out: unit_icon_builder.png

image_turret: NONE

repairEffectRate: 50
reclaimEffectRate: 50

image_shadow: AUTO

shadowOffsetX:2
shadowOffsetY:2



[arm_1]
x: 0
y: 0
image_end: 4elik.png
image_end_teamColors: true
drawOverBody: true
spinRate:1
#drawDirOffset: 0
#moveSpeed: 2
#rotateSpeed: 2

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false


[turret_1]
x: 0
y: 0
invisible: true
canShoot: false
isMainNanoTurret: true
canOnlyAttackUnitsWithTags: building, mechanical


[movement]
movementType: LAND
moveSpeed: 0.80
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 1
maxTurnSpeed: 12
turnAcceleration: 0.7
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.3


[ai]
useAsBuilder: true