[core]
copyFrom: reich_CC.ini
name: reichCCShielded
displayText: Command Center Shielded

maxShield: 4000
shieldRegen: 0
shieldRenderRadius: 35

armour: 30

energyRegen: -0.00105
#selfRegenRate: 0.8415
selfRegenRate: 1.683
showInEditor: false

[action_powerDown]
iconImage: areaShockIcon.png
convertTo: reichCC
isVisible: false
displayType: action
text: Disable Shield
autoTrigger: if self.isEnergyEmpty or self.shield(empty=true)
