#Caterpillar by Static Charge Red Field
#Edited by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: caterpillar
class: CustomUnitMetadata
price:0, cash=900
displayText: Caterpillar
displayText_es: Oruga
displayDescription: -Long range anti-air attack\n-Weak ground attack\n-Self regenerate
displayDescription_es: -Ataque antiaéreo de amplio rango\n-Ataque a tierra débil\n-Auto-regeneración
maxHp: 550
mass: 1000
techLevel: 2
buildSpeed: 0.0009
#availableInDemo: true
radius: 14
selfRegenRate: 0.01
numBitsOnDeath: 6
fogOfWarSightRange: 18
transportSlotsNeeded: 2
isBio: true
isBug: true
isUnrepairableUnit: true
energyMax: 5
energyRegen: 0.01
energyNeedsToRechargeToFull: true
effectOnDeath: CUSTOM:smallDeath

[graphics]
total_frames: 3
imageScale: 1.2
image:        caterpillar.png
image_wreak: caterpillar_dead.png
lock_body_rotation_with_main_turret: true
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true
animation_moving_start: 0
animation_moving_end: 2
animation_moving_scale_start:1
animation_moving_scale_end: 0.97
animation_moving_speed: 4
animation_moving_pingPong: true
animation_attack_start: 0
animation_attack_end: 0
animation_attack_speed: 14
animation_attack_scale_start:1
animation_attack_scale_end:0.97
animation_attack_pingPong: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
isFixedFiring: true
turretSize: 12
turretTurnSpeed: 3
maxAttackRange: 270
shootDelay: 35

[turret_1]
x: 0
y: 5
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
projectile: 1
shoot_light: yellow
energyUsage: 1

[turret_2]
x: 0
y: 4
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
projectile: 2
limitingRange: 200
shoot_light: green
recoilOffset: -3
recoilOutTime: 6
recoilReturnTime: 18

[projectile_1]
directDamage: 100
life: 150
speed: 5
trailEffect: true
targetSpeed: 8
ballistic: true
ballistic_delaymove_height: 40
ballistic_height: 50
image: spike.png
lightColor: #ffffff00
lightSize: 0.4

[projectile_2]
speed: 6
directDamage: 8
life: 150
frame: 6
lightColor: #ffffff00
lightSize: 0.4

[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.04
moveDecelerationSpeed: 0.06
maxTurnSpeed: 1
turnAcceleration: 0.06
moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  181
reverseSpeedPercentage:0

#Caterpillar by Static Charge Red Field