#Mosquito by Essential Strategy

[core]
copyFrom:ROOT:assets/templates/bio.template
name: mosquito
displayText: Small Wasp
displayText_es: Avispa Pequeña
displayDescription: -Can attack ground and air\n-Weak
displayDescription_es: -Puede atacar a tierra y aire\n-Débil
class: CustomUnitMetadata
price: biomass=200
maxHp: 40
mass: 200
techLevel: 1
buildSpeed: 0.005
#availableInDemo: true
radius: 8
softCollisionOnAll: 24
isBio: true
isBug: true
selfRegenRate:0.1
numBitsOnDeath: 3
fogOfWarSightRange: 10
explodeOnDeath: false
explodeOnDeathGroundCollosion: false


[action_evolve]
convertTo: wasp
price: biomass=800
text: Metamorphosis
text_es: Metamorfosis
description: -Increases HP, damage and range
description_es: -Incrementa los PV, el daño y el rango
displayType: upgrade
buildSpeed: 10s
pos: 0
whenBuilding_cannotMove: true
canPlayerCancel: false

[graphics]
total_frames: 2
image:        mosquito.png
image_wreak:  mosquito_dead.png
imageScale:0.7
lock_body_rotation_with_main_turret: true
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 2

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretSize: 9
aimOffsetSpread:0.4
maxAttackRange: 120
shootDelay: 40

[turret_1]
x: 0
y: 0
recoilOffset: 1
recoilOutTime: 10
recoilReturnTime: 14

[projectile_1]
directDamage: 6
life: 80
speed: 6
color: #00ff00
drawSize: 0.8
lightColor: #00ff00
lightSize: 0.2

[movement]
movementType: AIR
targetHeight: 17
targetHeightDrift: 1
reverseSpeedPercentage: 0.6
moveSpeed: 2.3
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.06
maxTurnSpeed: 1
turnAcceleration: 0.1
moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181
slowDeathFall: true
slowDeathFallSmoke: false

#Mosquito by Essential Strategy