[core]

name:EkMountain tilt
displayText:Mountain tilt Guided missile destroyer
displayDescription:-Loaded with a large number of missiles
displayText_zh:山倾导弹驱逐舰
displayDescription_zh:装载了大量导弹
class:CustomUnitMetadata
price:0, cash=40000,alloys=5000
maxHp:9000
buildSpeed:90s
mass:40000
isBio:false
armour:10
radius:80
showInEditor:true
ignoreInUnitCapCalculation:true
showOnMinimap:false
energyMax:15
energyRegen:0.022
energyNeedsToRechargeToFull:false
autoTriggerCooldownTime:2s
[graphics]
total_frames:1
image:Mountain tilt.png
image_wreak:NONE
image_shadow:AUTO
image_turret:cannon turret.png
imageScale:1
shadowOffsetX:3
shadowOffsetY:3
movementEffect:CUSTOM:EkWakeTail,EkWakeFront
scaleImagesTo:30
icon_zoomed_out:unit_icon_largeship.png
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
maxAttackRange:600
turretSize:15
turretTurnSpeed:3
shootDelay:120
aimOffsetSpread:0.45
[hiddenAction_水]
autoTrigger:if self.isInWater and self.isMoving
spawnEffects:CUSTOM:waterSplash1,custom:wave
[effect_wave]
life:150
image:shockwave.png
scaleFrom:0
scaleTo:0.8
createWhenOverLand:false
drawUnderUnits:true
delayedStartTimer:15
attachedToUnit:false
[effect_waterSplash1]
life:100
image:bubbles.png
ySpeedAbsolute:0.1
ySpeedAbsoluteRandom:0.05
xSpeedAbsoluteRandom:0.05
yOffsetRelativeRandom:3
xOffsetRelativeRandom:3
dirOffset:45
createWhenOverLand:false
imageShadow:SHADOW:bubbles.png
shadow:true
alsoEmitEffects:custom:waterSplash2,custom:waterSplash3
drawUnderUnits:true
delayedStartTimer:15
attachedToUnit:false
[effect_waterSplash2]
life:100
image:bubbles.png
ySpeedAbsolute:0.1
ySpeedAbsoluteRandom:0.05
yOffsetRelativeRandom:3
xOffsetRelativeRandom:-3
dirOffset:135
createWhenOverLand:false
imageShadow:SHADOW:bubbles.png
shadow:true
drawUnderUnits:true
delayedStartTimer:15
attachedToUnit:false
[effect_waterSplash3]
life:100
image:bubbles.png
ySpeedAbsolute:-0.1
ySpeedAbsoluteRandom:0.05
yOffsetRelativeRandom:-3
xOffsetRelativeRandom:0
dirOffset:45
createWhenOverLand:false
imageShadow:SHADOW:bubbles.png
shadow:true
drawUnderUnits:true
delayedStartTimer:15
attachedToUnit:false
[action_buy crab]
price:0, cash=0
text:build
description:build
text_zh:制作战斗螃蟹
description_zh:-可以制造内置4个战斗螃蟹
displayType:NONE
buildSpeed:60s
pos:0.2
addResources:ammo=4
[action_fireCrab]
fireTurretXAtGround:1
text:Fire Nuclear Missile
text_zh:发射一个战斗螃蟹
displayType:action
fireTurretXAtGround_withProjectile:2
price:0,ammo=1
#isLocked:if self.resource(greaterThan=0,type='EMP')
[turret_激光拦截]
x:0
y:17
canShoot:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
invisible:true
laserDefenceEnergyUse:1
limitingRange:250
size:0.5
turnSpeed:15

[turret_1]
x:0
y:0
invisible:true
canAttack:false
[attachment_11]
x:0
y:68
redirectDamageToParent:true
onCreateSpawnUnitOf:山也火炮
canAttack:true
setDrawLayerOnTop:true
 
lockRotation:true
addTransportedUnits:false
[attachment_2]
redirectDamageToParent:true
onCreateSpawnUnitOf:山也火炮
canAttack:true
setDrawLayerOnTop:true
idleDir:0
lockRotation:true
addTransportedUnits:false
x:0
y:-30


[attachment_3]
x:0
y:-95
idleDir:-180
redirectDamageToParent:true
onCreateSpawnUnitOf:山也火炮
canAttack:true
setDrawLayerOnTop:true
lockRotation:true
addTransportedUnits:false

[projectile_1]
directDamage:500
life:70
speed:10
areaDamage:450
areaRadius:50
frame:4
drawSize:1
largeHitEffect:true
targetGround:true
targetGroundSpread:10
speedSpread:2
lightColor:#FFFF5500
lightSize:1
trailEffect:CUSTOM:尾焰
trailEffectRate:7
ballistic:false
explodeEffect:CUSTOM:弹坑,烟雾a,CUSTOM:爆炸,CUSTOM:水波,CUSTOM:水波2,CUSTOM:flash1, CUSTOM:flare1*5,CUSTOM:explosion1s2,CUSTOM:flash2
[projectile_2]
directDamage:0
life:450
speed:0.4
targetSpeed:1.6
drawSize:1
color:#1E1E96
trailEffect:true
largeHitEffect:true
autoTargetingOnDeadTarget:true
spawnUnit:Ek_robotCrab2

[effect_烟雾a]
priority:critical
frameIndex:0
image:烟17.png
spawnChance:1
createWhenZoomedOut:false
life:150
attachedToUnit:false
fadeInTime:10
fadeOut:true
scaleFrom:0.2
scaleTo:0.35
alpha:0.7
drawUnderUnits:false
liveAfterAttachedDies:false

hSpeed:0.01
dirOffsetRandom:180
ySpeedRelativeRandom:-0.1
xSpeedRelativeRandom:0.2
ySpeedRelative:0.1
atmospheric:true
[effect_灰尘]
image:烟22.png
createWhenOverLand:true
createWhenOverLiquid:false
life:250
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:100
scaleFrom:0.6
scaleTo:0.6
alpha:3
yOffsetRelative:0
ySpeedRelative:0.5
dirOffsetRandom:5
dirSpeedRandom:0.05
atmospheric:true

[effect_弹坑]
image:FX_Crater2.png
createWhenOverLand:true
createWhenOverLiquid:false
life:1400
spawnChance:1
fadeOut:true
attachedToUnit:false
scaleFrom:0.4
scaleTo:0.4
alpha:100
drawUnderUnits:true
yOffsetRelative:0
ySpeedRelative:0
dirOffsetRandom:0
dirSpeedRandom:0
atmospheric:false

[effect_爆炸]
total_frames:7
animateFrameStart:0
animateFrameEnd:6
animateFrameSpeed:0.2
image:boom.png
createWhenOverLand:true
createWhenOverLiquid:true
life:80
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:7
scaleFrom:0.4
scaleTo:0.8
alpha:0.6
drawUnderUnits:true
yOffsetRelative:0
ySpeedRelative:0.3
dirOffsetRandom:1
dirSpeedRandom:0.05
atmospheric:false

[effect_水波]
total_frames:1
animateFrameStart:0
animateFrameEnd:0
image:water wave.png
createWhenOverLand:false
createWhenOverLiquid:true
life:50
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.007
scaleTo:0.2
alpha:0.6
drawUnderUnits:true
yOffsetRelative:0
ySpeedRelative:0.3
dirOffsetRandom:1
dirSpeedRandom:0.05
atmospheric:false

[effect_水波2]
total_frames:1
animateFrameStart:0
animateFrameEnd:0
image:FX_Splash_Smoke_1.png
createWhenOverLand:false
createWhenOverLiquid:true
life:50
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.08
scaleTo:0.2
alpha:0.6
drawUnderUnits:true
yOffsetRelative:0
ySpeedRelative:0.3
dirOffsetRandom:1
dirSpeedRandom:0.05
atmospheric:false
[effect_尾焰]
priority:critical
image:glow_green.png
life:20
fadeOut:true
alpha:0.6
attachedToUnit:false
fadeInTime:2
scaleFrom:0.3
scaleTo:0.5
drawUnderUnits:false
[effect_explosion1s2]
life:100
scaleFrom:0.8
scaleTo:0.6
image:B.png
alsoPlaySound:sniperFire.ogg
total_frames:14
animateFrameStart:0
animateFrameEnd:13
animateFrameSpeed:0.5
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5
priority:critical


[effect_flare1]
image:SHARED:light_50.png
life:40
fadeOut:true
color:#ff9900
scaleFrom:0.15
scaleTo:0.15
alpha:0.5
xSpeedRelativeRandom:2
ySpeedRelativeRandom:2
priority:critical
[effect_flash1]
image:SHARED:light_50.png
life:80
fadeOut:true
color:#ff9900
scaleFrom:0.5
scaleTo:0
alpha:1
drawUnderUnits:true
priority:critical
[effect_flash2]
priority:critical
image:SHARED:light_50.png
life:35
fadeOut:true
alpha:1
color:#FFA000
attachedToUnit:false
fadeInTime:2
scaleFrom:1
scaleTo:1.3
drawUnderUnits:false
[attachment_高射1]
x:-2
y:38
onCreateSpawnUnitOf:左炮塔部分
canBeAttackedAndDamaged:false
isUnselectable:true
lockRotation:true
addTransportedUnits:true
canAttack:true
deattachIfWantingToMove:false
createIncompleteIfParentIs:false
redirectDamageToParent:false
redirectDamageToParent_shieldOnly:false

[attachment_高射2]
x:-9
y:38
@copyFromSection:attachment_高射1

[attachment_高射3]
x:-3
y:33
@copyFromSection:attachment_高射1

[attachment_高射4]
x:-9
y:32
@copyFromSection:attachment_高射1

[attachment_高射5]
x:-3
y:49.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_高射6]
x:-9
y:49.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_高射7]
x:-3
y:44.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_高射8]
x:-9
y:44.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_副炮1]
x:-3
y:-59.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_副炮2]
x:-9
y:-59.5
@copyFromSection:attachment_高射1

[attachment_副炮3]
x:-3
y:-74
idleDir:0
@copyFromSection:attachment_高射1

[attachment_副炮4]
x:-9
y:-74
@copyFromSection:attachment_高射1

[attachment_副炮5]
x:-3
y:-63.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_副炮6]
x:-9
y:-63.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_副炮7]
x:-3
y:-68.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_副炮8]
x:-9
y:-68.5
idleDir:0
@copyFromSection:attachment_高射1

[attachment_高射9]
x:3
y:39.5
onCreateSpawnUnitOf:右炮塔部分
canBeAttackedAndDamaged:false
isUnselectable:true
lockRotation:true
addTransportedUnits:true
canAttack:true
deattachIfWantingToMove:false
createIncompleteIfParentIs:false
redirectDamageToParent:false
redirectDamageToParent_shieldOnly:false

[attachment_高射10]
x:9
y:39.5
@copyFromSection:attachment_高射9

[attachment_高射11]
x:3
y:34.5
@copyFromSection:attachment_高射9

[attachment_高射12]
x:9
y:34.5
@copyFromSection:attachment_高射9

[attachment_高射13]
x:3
y:49.5
@copyFromSection:attachment_高射9

[attachment_高射14]
x:9
y:49.5
@copyFromSection:attachment_高射9

[attachment_高射15]
x:3
y:44.5
@copyFromSection:attachment_高射9

[attachment_高射16]
x:9
y:44.5
@copyFromSection:attachment_高射9

[attachment_副炮9]
x:3
y:-68.5
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮10]
x:9
y:-68.5
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮11]
x:3
y:-74
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮12]
x:9
y:-74
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮13]
x:3
y:-63.5
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮14]
x:9
y:-63.5
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮15]
x:3
y:-59.5
idleDir:0
@copyFromSection:attachment_高射9

[attachment_副炮16]
x:9
y:-59.5
idleDir:0
@copyFromSection:attachment_高射9
[effect_EkWakeTail]
image:waketail.png
createWhenOverLand:false
life:120
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.25
scaleTo:1.5
alpha:0.6
drawUnderUnits:true
yOffsetRelative:-40
ySpeedRelative:0.3
dirOffsetRandom:10
dirSpeedRandom:0.1
[effect_EkWakeFront]
image:wakefront.png
createWhenOverLand:false
life:90
spawnChance:1
fadeOut:true
attachedToUnit:false
fadeInTime:10
scaleFrom:0.5
scaleTo:1.25
alpha:0.6
drawUnderUnits:true
yOffsetRelative:70
ySpeedRelative:0.3
dirOffsetRandom:5
dirSpeedRandom:0.05
atmospheric:true
[movement]
movementType:WATER
moveSpeed:0.34
moveAccelerationSpeed:0.02
moveDecelerationSpeed:0.05
reverseSpeedPercentage:1
maxTurnSpeed:0.4
turnAcceleration:0.2