[core]

showInEditor:false
name:左炮塔部分
class:CustomUnitMetadata
price:0, cash=1
maxHp:15000
mass:40000
isBio:false
armour:10
radius:1
ignoreInUnitCapCalculation:true
showOnMinimap:false
[graphics]
total_frames:2
image:无.png
image_wreak:NONE
image_shadow:AUTO
showShotDelayBar:false
animation_idle_start:0
animation_idle_end:0
animation_idle_speed:2
animation_attack_start:1
animation_attack_end:1
animation_attack_speed:100
scaleImagesTo:4
imageScale:0.9
[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
canAttackNotTouchingWaterUnits:true
maxAttackRange:600
aimOffsetSpread:5
[turret_rocket]
x:0
y:0
projectile:1
shoot_sound_vol:5
delay:10s
size:0
invisible:true
shoot_sound:rocket fire.ogg
shoot_flame:CUSTOM:爆炸,CUSTOM:闪
shoot_light:#FFEECCCC
idleSweepAngle:360
shouldResetTurret:false
idleSweepSpeed:10
turnSpeed:0.05
[effect_爆炸]
life: 400
scaleTo:4
scaleFrom:3
image: 黑烟.png
alpha:0.6
attachedToUnit: false
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
dirOffsetRandom:360
[effect_闪]
life: 20
image: 闪光.png

scaleTo:3
scaleFrom:3
[projectile_1]
speed:0.1
frame:1
ballistic:true
ballistic_delaymove_height:150
targetSpeedAcceleration:0.09
life:2400
image:rocket small.png
targetSpeed:35
trailEffect:true
trailEffectRate:4
drawSize:1
directDamage:40
areaRadius:50
buildingDamageMultiplier:4
areaRadiusFromEdge:true
tags:EKAmmo
#deflectionPower:-2
explodeEffect:CUSTOM:闪光,CUSTOM:烟阿珂,CUSTOM:大炸,CUSTOM:火花
gravity:0.5
speedSpread:0.2
spawnUnit:震
[effect_大炸]
life: 120
scaleTo:2.5
scaleFrom:2.5
image: 大爆炸.png
alpha:0.5
attachedToUnit: false
total_frames: 6
animateFrameStart:0
animateFrameEnd:5
animateFrameSpeed:0.3
alsoPlaySound:爆.ogg
[effect_啊]
life:15
scaleTo:1.1
scaleFrom:1.1
image:火.png
total_frames: 1
animateFrameStart:1
animateFrameEnd:1
animateFrameSpeed:15
attachedToUnit:false

[effect_火花]
life: 300
image: 丫丫.png
drawUnderUnits:true
scaleTo:1.5
scaleFrom:1.5
attachedToUnit:false

[effect_闪光]
life: 20
image: 闪光.png
drawUnderUnits:true
scaleTo:10
scaleFrom:10
attachedToUnit:false

[effect_烟阿珂]
life: 400
scaleTo:25
scaleFrom:8
image: 黑烟.png
alpha:0.85
attachedToUnit:false

[movement]
movementType:NONE
moveSpeed:0
maxTurnSpeed:0

[effect_sparks]
attachedToUnit:false
life:150
physics:true
xSpeedRelativeRandom:1.2
ySpeedRelativeRandom:1.3
hSpeed:1.8
image:SHARED:spark.png
priority:verylow
scaleFrom:1.8
scaleTo:0.3
color:#F91200

[effect_爆炸x]
life:100
priority:critical
attachedToUnit:false
scaleFrom:0.2
scaleTo:0.3
image:爆炸251.png
total_frames:26
animateFrameStart:0
animateFrameEnd:25
animateFramePingPong:false
animateFrameSpeed:0.35
alwayStartDirAtZero:true
alsoPlaySound:打击音效.ogg

[effect_烟雾a]
priority:critical
frameIndex:0
stripIndex:effects
spawnChance:1
createWhenZoomedOut:false
life:55
fadeOut:true
attachedToUnit:false
color:#FFFFFF
fadeInTime:10
scaleFrom:0.5
scaleTo:1.5
alpha:0.9
drawUnderUnits:false
liveAfterAttachedDies:false
hSpeed:0.01
dirOffsetRandom:180
ySpeedRelativeRandom:0.1
xSpeedRelativeRandom:0.6
yOffsetRelative:0.5
ySpeedRelative:1
atmospheric:true