[core]
name: sanaBuilder
copyFrom: ROOT:assets/templates/builder.template
displayText: Имперский Строитель 
displayDescription: -Строит и ремонтирует здания\n-Не может атаковать

[canBuild_base]
name: sanaCCFake,EkBananaFlag
pos:100

[graphics]
imageScale: 1
total_frames: 1
teamColorsOnTurret: true
image: bodyAltArmored.png
image_wreak:  body_dead.png
#scaleImagesTo: 20
#scaleTurretImagesTo: 9
image_shadow: AUTO
shadowOffsetX:0
shadowOffsetY:4

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
[turret_body]
x: 0
y: 0
idleDirReversing:0
canShoot:false
barrelX: -14
barrelY: 7
invisible:true
turnSpeed:1.3
turnSpeedAcceleration: 0.1
recoilOffset:-1
recoilOutTime:2
recoilReturnTime:10
[turret_nanoTurret]
x: 5
y: -5
attachedTo: body
slave:false
barrelX:-4
barrelY:27
canShoot: false
turnSpeed: 3
turnSpeedAcceleration: 0.2
isMainNanoTurret: true
image:builderToolArmored.png
idleDir:35
idleDirReversing:35
idleSweepAngle:60
idleSweepSpeed:0.3
idleSweepDelay:240
idleSweepAddRandomDelay:30
idleSweepCondition: if not self.isMoving()
limitingRange:150

[leg_1]
x: -13
y: 13
attach_x: -4
attach_y: 4
moveSpeed:2.5
rotateSpeed: 78
heightSpeed: 0.8
resetAngle:25
#draw_foot_on_top: true
dust_effect: false
image_leg:  leg.png
image_foot: foot.png
holdDisMin:20
holdDisMax:40
hardLimit: 50
endDirOffset:135
favourOppositeSideNeighbours: true
holdDisMin_maxMovingLegs:2
moveWarmUp:1
estimatingPositionMultiplier:0.8
[leg_2]
x: 13
y: 13
attach_x: 4
attach_y: 4
copyFrom: 1
endDirOffset:225
[leg_3]
x: -13
y: -13
attach_x: -4
attach_y: -4
copyFrom: 1
endDirOffset:45
[leg_4]
x: 13
y: -13
attach_x: 4
attach_y: -4
copyFrom: 1
endDirOffset:-45
[movement]
movementType: LAND
moveSpeed: 0.80
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 1
maxTurnSpeed: 12
turnAcceleration: 0.7
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.3

[ai]
useAsBuilder: true
