#Queen T2 by Essential Strategy

[core]
dont_load: true
name: queenT2
showInEditor: false
class: customUnitMetadata
price: 2500
maxHp: 4000
mass:10000
displayText: Queen - T2
displayText_es: Reina - T2
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,2
generation_credits: 4
techLevel: 2
buildSpeed: 0.0008
#availableInDemo: true
radius: 28
isBio: true
isBug: true
exit_x:0
exit_y: 24
isUnrepairableUnit: true
numBitsOnDeath: 17
isBuilding: true
selfRegenRate: 0.1
selfBuildRate:0.0008
softCollisionOnAll: 3
canBuild_1_name: setRally
canBuild_1_pos:  0
canBuild_2_name: spore
canBuild_2_pos: 0.2
nukeOnDeath: true
nukeOnDeathRange: 10
nukeOnDeathDamage: 0

[action_evolve]
convertTo: queenT3
price:  3000
text: i:gui.actions.upgradeT3
displayType: upgrade
buildSpeed: 0.0006
pos: 0.1

[graphics]
total_frames: 1
imageScale: 1.7
image:        queen_t2.png
image_wreak:  NONE
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 150
animation_idle_scale_start:1
animation_idle_scale_end:1.05
animation_idle_pingPong: true

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0

[ai]
upgradedFrom: queen

#Queen T2 by Essential Strategy