[core]
name: yakuzCC
copyFrom:ROOT:assets/templates/navigations/buildNavigation/buildNavigation.ini
displayText: Империя Восходящего Солнца
displayDescription: -Секретная технология Империи\n-Может взорваться при смерти
class:             CustomUnitMetadata
price:400000
maxHp:             10000
mass:              9000
techLevel:         1
buildSpeed:        0.000005
nukeOnDeath:true
nukeOnDeathRange:242464624
nukeOnDeathDamage:100
nukeOnDeathDisableWhenNoNuke:true
explodeOnDeathGroundCollosion:true
radius:            18
reclaimPrice:0
isBio:             false
isBuilding:        true
energyMax:          1
energyRegen:       0.0001
energyNeedsToRechargeToFull: true
autoRepair: true
selfRegenRate:0.2
generation_credits: 25
softCollisionOnAll: 5
footprint:-1,-1,1,1
constructionFootprint:-1,-1,1,2
exit_x:-8
exit_y:-8
tags: commandCenter

[action_showLore]
@copyFromSection: template_showLoreAction
description:Империя Восходящего Солнца — фракция, вдохновлённая восточными культурами, особенно японской. Она объединила множество планет, придерживающихся традиционных ценностей, уважения к природе и общественного порядка.\nИдеология: Консерватизм, коллективизм и гармония с природой. Империя верит в важность поддержания традиций и социальной стабильности, стремясь создать общество, где каждый индивид играет свою роль на благо общего дела.\nВоенные силы: Боевые духовые войска с акцентом на дисциплину и тактику.\nОсобенности: Сильная культурная идентичность и высокий уровень социальной организации. Экономика ориентирована на производство качественных товаров и поддержание инфраструктуры.

[action_showPowersToPlayer]
@copyFromSection: template_showMenuAction
@define menuID:101
text: Силы
isVisible: true

[template_baseSuperPowerAction]
@define menuID: 1
isVisible: if memory.currentMenu == ${menuID} 

[template_powersAction]
@define menuID:101
isVisible:if memory.currentMenu == ${menuID}
pos:1.01

[action_fireRockets]
@copyFromSection: template_powersAction
price:energy=1
fireTurretXAtGround:1
deleteSelf: true
text: Отправить ядерную боеголовку
displayType:action
ai_isDisabled:true
buildSpeed:1.9s
displayRemainingStockpile:false
highPriorityQueue:true
onlyOneUnitAtATime:true
iconImage: ROOT:assets/ui/action_icons/launch_missile.png

[action_explode]
@copyFromSection: template_powersAction
switchToAggressiveTeam:true
addResources:hp=-1000000
text: Взорвать базу
displayType:action
ai_isDisabled:true
buildSpeed:20s
displayRemainingStockpile:false
highPriorityQueue:true
onlyOneUnitAtATime:true
iconImage: ROOT:assets/ui/action_icons/area_shock.png

[canBuild_1]
name:          yakuzBuilder, scout, EkmegaBuilder, setRally
pos: 1


[graphics]
image:        hiroshima.png
image_back:   hiroshima.png

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1

[attack]
canAttack:            false
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize:      0
turretTurnSpeed: 100

#стрельба
maxAttackRange: 242464624
shootDelay:     70

[hiddenAction_removeEnergy]
autoTriggerOnEvent:created
addResources: energy=-0.99

[turret_1]
x:0
y:0
warmup:0
shouldResetTurret:false
shoot_sound:nuke_launch
shoot_sound_vol:0.15
shoot_light:#FFEECCCC
canShoot:true
canAttackCondition:if self.isControlledByAI()
canAttackFlyingUnits:false
canAttackLandUnits:if self.isControlledByAI()
canAttackUnderwaterUnits:false
projectile:1
size:1
turnSpeed:90
shoot_flame:shockwave
[projectile_1]
tags:nuke,ballisticmissile,ballistic_missile,cruisemissile,cruise_missile
nukeWeapon:true
life:9999
speed:0
targetSpeed:2.5
shadowFrame:10
image:hiroshima.png
drawSize:1.025
areaDamage:10000
areaRadius:500
largeHitEffect:true
targetGround:true
targetGroundSpread:0
areaHitAirAndLandAtSameTime:true
ballistic:true
ballistic_delaymove_height:80
ballistic_height:110
lightColor:#ffe92b
lightSize:1
friendlyFire:true
alwaysVisibleInFog:true
shouldRevealFog:true
deflectionPower:-1
explodeOnEndOfLife:true

[movement]
movementType:NONE
moveSpeed:0
moveAccelerationSpeed:0.01
moveDecelerationSpeed:0.01
maxTurnSpeed:0
turnAcceleration:0.1