
[core]
copyFrom:airFactory.ini
name: EkairFactoryT2
class: CustomUnitMetadata
price: 3000
maxHp: 1000
mass: 9000

overrideAndReplace:NONE

[action_upgrade]
isVisible:false

[canBuild_1]
name: setRally
pos:  0.1

[canBuild_2]
name:lightGunship
pos:0.2

[canBuild_3]
name:c_helicopter
pos:0.6

[canBuild_4]
name:c_interceptor
pos:0.4

[canBuild_5]
name: dropship
pos:  0.5

[canBuild_6]
name:heavyInterceptor
pos:0.3

[canBuild_7]
name:gunShip
pos:0.7

[canBuild_8]
name:amphibiousJet
pos:0.8

[canBuild_9]
name:aaBeamGunship
pos:0.9


[canBuild_10]
name:missileAirship, bomber
pos:0.92 

[canBuild_lightAircraftTech]
name:EkSmallFighter, EkSmallDrone
isVisible: if self.globalTeamTags(includes='${tech_aircraft1}')
pos:1

[canBuild_advancedAircraftTech]
name:EkairBuilder,EkScoutDrone,EkSwallowtail,EkHunterDrone2,EkHunterDrone,Ek_largeGunship,EkBasicFighter,EkLargeDrone,EkInterceptor,EkMissileDrone,Ek_beamGunshipReaper
isVisible: if self.globalTeamTags(includes='${tech_aircraft2}')
pos:2

[canBuild_stealthJet]
name:Ek_expinterceptorStelth,Ek_Stallion_Smode,Ek_protos_Smode
isVisible: if self.globalTeamTags(includes='${tech_stealth}')
pos:3

[graphics]
total_frames: 5

animation_idle_start:0
animation_idle_end:4
animation_idle_speed:25
image:        air_factory_t2.png
image_wreak:  air_factory_t2_dead.png

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1





[ai]
upgradedFrom:EkairFactoryT2





