[core]
copyFrom:missile.md,ROOT:ASSETS/templates/hyperdrive.template
#showInEditor:false
name:Ekgorgon
displayText:Горгон всея EK
displayDescription:Бойтесь.
class:CustomUnitMetadata
price:5000000,experimental=1600000
maxHp:350000
selfRegenRate:0.8
armour:280
armourMinDamageToKeep:0
maxShield:190000
shieldRegen:1.5
mass:50000000
buildSpeed:260s
availableInDemo:true
tags:Gorgon,EkGorgonLaserActing,Ekgorgon
radius:500
uiTargetRadius:180
displayRadius:550
softCollisionOnAll:65
isBio:false
fogOfWarSightRange:64
shieldRenderRadius:530
shieldDisplayOnlyDeflection: true
action_1_convertTo: Ekgorgon 2
action_1_buildSpeed:3.3s
action_1_text:Raise flight altitude
action_1_text_zh:提升飞行高度
action_1_isLocked:if self.height(greaterThan=300)
action_1_isLockedMessage:The engine is undergoing a descent command
action_1_isLockedMessage_zh:发动机正在进行下降指令
autoTriggerCooldownTime:0
autoTriggerCooldownTime_allowDangerousHighCPU:true
@memory blinktarget:unit

[hiddenAction_ready]
autoTriggerOnEvent:created
showQuickWarLogToAllPlayers:[ПЛАНЕТАРНОЕ ПРЕДУПРЕЖДЕНИЕ] НА ПЛАНЕТУ ПРИБЫЛ ГОРГОН!
playSoundGlobally:ROOT:/ASSETS/sounds/event_warning1.wav:3.5


[graphics]
total_frames:1
imageScale:2.3
image: base1.png
image_wreak: dead.png
image_shadow:AUTO
shadowOffsetX:4
shadowOffsetY:4
splastEffect:true
movementEffect: CUSTOM:pt1,CUSTOM:pt2,CUSTOM:pt3
movementEffectRate: 2
icon_zoomed_out_neverShow:true
[effect_pt1]
createWhenZoomedOut: true
priority:high
image: beam_flare.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 3
scaleTo: 1
alpha: 2
drawUnderUnits:true
ySpeedRelative:-8
atmospheric: true
xOffsetRelative:0
yOffsetRelative:-500
[effect_pt2]
@copyFromSection:effect_pt1
#xOffsetRelative:-205
#yOffsetRelative: ${-513-22}
xOffsetRelative:-30
image: jetflame2.png
scaleFrom: 2.5
scaleTo: 1
[effect_pt3]
@copyFromSection:effect_pt2
#xOffsetRelative:205
xOffsetRelative:30

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits:false
turretMultiTargeting:true
maxAttackRange:800

[attachment_laser]
x:0
y:0
idleDir:0
onCreateSpawnUnitOf: EkTestLaser
lockLegMovement:true
keepAliveWhenParentDies:false
canBeAttackedAndDamaged:false
isUnselectable:true
prioritizeParentsMainTarget:true
alwaysAllowedToAttackParentsMainTarget:false
canAttack:true
lockRotation:true
createIncompleteIfParentIs:false

[attachment_laserTemplate]
x:0
y:0
idleDir:0
lockLegMovement:true
keepAliveWhenParentDies:false
canBeAttackedAndDamaged:true
isUnselectable:true
prioritizeParentsMainTarget:true
alwaysAllowedToAttackParentsMainTarget:false
canAttack:true
lockRotation:true
createIncompleteIfParentIs:false

[attachment_laserU1R]
@copyFromSection:attachment_laserTemplate
onCreateSpawnUnitOf: EkTestLaserB
x: -205
y: -212
alwaysAllowedToAttackParentsMainTarget:true

[attachment_laserU2R]
@copyFromSection:attachment_laserTemplate
onCreateSpawnUnitOf: EkTestLaserB
x: 205
y: -212
alwaysAllowedToAttackParentsMainTarget:true

[attachment_L1]
setDrawLayerOnBottom:true
@copyFromSection:attachment_laser
x:-160
y:-43
onCreateSpawnUnitOf:EkTestCannonL
alwaysAllowedToAttackParentsMainTarget:true
[attachment_L2]
@copyFromSection:attachment_L1
x:-160
y:-23
[attachment_L3]
@copyFromSection:attachment_L1
x:-150
y:45
[attachment_L4]
@copyFromSection:attachment_L1
x:-150
y:65
[attachment_L5]
@copyFromSection:attachment_L1
x:-150
y:230
[attachment_L6]
@copyFromSection:attachment_L1
x:-150
y:250
[attachment_L7]
@copyFromSection:attachment_L1
x:-100
y:-150
setDrawLayerOnTop:true
setDrawLayerOnBottom:false
onCreateSpawnUnitOf:EkTestCannonL2
[attachment_L8]
@copyFromSection:attachment_L7
x:-100
y:-81
[attachment_L9]
@copyFromSection:attachment_L7
x:-85
y:103
[attachment_L10]
@copyFromSection:attachment_L7
x:-85
y:171
[attachment_R1]
setDrawLayerOnBottom:true
@copyFromSection:attachment_laser
x:160
y:-43
onCreateSpawnUnitOf:EkTestCannonR
alwaysAllowedToAttackParentsMainTarget:true
[attachment_R2]
@copyFromSection:attachment_R1
x:160
y:-23
[attachment_R3]
@copyFromSection:attachment_R1
x:150
y:45
[attachment_R4]
@copyFromSection:attachment_R1
x:150
y:65
[attachment_R5]
@copyFromSection:attachment_R1
x:150
y:230
[attachment_R6]
@copyFromSection:attachment_R1
x:150
y:250
[attachment_R7]
@copyFromSection:attachment_R1
x:100
y:-150
setDrawLayerOnTop:true
setDrawLayerOnBottom:false
onCreateSpawnUnitOf:EkTestCannonR2
[attachment_R8]
@copyFromSection:attachment_R7
x:100
y:-81
[attachment_R9]
@copyFromSection:attachment_R7
x:85
y:103
[attachment_R10]
@copyFromSection:attachment_R7
x:85
y:171

[action_a1]
isActive:if self.hasUnitInTeam(withTag='Ekgorgon',withinRange=1000) and not self.queueSize(greaterThan=0)
fireTurretXAtGround: main_cannon
fireTurretXAtGround_withProjectile: main_cannon
whenBuilding_cannotMove: true
price:0
text:主炮开火
description: 
displayType: action
buildSpeed: 3s
pos: -1
highPriorityQueue: true
onlyOneUnitAtATime: true
allowMultipleInQueue:false
playSoundToPlayerOnQueue:主炮蓄力.ogg
addActionCooldownTime:120s
[turret_main_cannon]
x:0
y:480
image:SHARED:blank.png
canAttackFlyingUnits: false
canAttackLandUnits: false
size:0
delay:40
projectile:main_cannon
shouldResetTurret:false
shoot_sound:主炮爆炸.ogg
shoot_sound_vol:0.46
shoot_flame:NONE
canShoot:true
canAttackMaxAngle:360
aimOffsetSpread:0
turnSpeed:0
limitingRange:1500

[projectile_main_cannon]
image:Yamato Cannon.png
life:10
speed:20
turnSpeed:0
drawSize:1
areaDamage:24000
areaRadius:600
directDamage:22000
largeHitEffect:true
trailEffect:CUSTOM:projectileTrail,CUSTOM:projectileTrail2
trailEffectRate:1
explodeEffect:CUSTOM:projectileFlash,CUSTOM:explosionblue_L,CUSTOM:blackSmoke1*30,CUSTOM:boom1,CUSTOM:crater,CUSTOM:blackSmoke2*10,CUSTOM:wave1
explodeEffectOnShield:CUSTOM:projectileFlash,CUSTOM:explosionblue_L,CUSTOM:blackSmoke1*30,CUSTOM:boom1,CUSTOM:crater,CUSTOM:blackSmoke2*10,CUSTOM:wave1
deflectionPower:-400
spawnProjectilesOnEndOfLife:main_cannon2
spawnProjectilesOnCreate:main_cannon_show
areaHitAirAndLandAtSameTime:true
armourIgnoreAmount:200
areaRadiusFromEdge:true
[projectile_main_cannon_show]
image:none.png
life: 0
areaDamage: 0
areaRadius: 0
explodeEffect:custom:showmaincannon
explodeEffectOnShield:custom:showmaincannon
instant:true

[projectile_main_cannon2]
@copyFromSection:projectile_main_cannon
life:30
turnSpeed:10
spawnProjectilesOnEndOfLife:main_cannon3
[projectile_main_cannon3]
@copyFromSection:projectile_main_cannon
life:300
turnSpeed:36000
spawnProjectilesOnEndOfLife:NONE
[effect_projectileTrail]
image:SHARED:light_50.png
life:20
attachedToUnit:false
color:#FFFF00
fadeInTime:0
fadeOut:true
scaleFrom:2
scaleTo:0
alpha:1
drawUnderUnits:true
dirSpeed:180
createWhenOffscreen:true
[effect_projectileTrail2]
image:trail_ring.png
life:30
attachedToUnit:false
color:#FFFF00
scaleFrom:0
scaleTo:4
alpha:1.0
drawUnderUnits:false
[effect_projectileTrail3]
image:SHARED:light_50.png
life:60
attachedToUnit:false
color:#FFFF00
fadeOut:true
scaleFrom:0.4
scaleTo:0.4
alpha:1
drawUnderUnits:true
dirSpeed:180
createWhenOffscreen:true
[effect_projectileFlash]
image:SHARED:light_50.png
delayedStartTimer:5
life:30
fadeOut:true
attachedToUnit:false
color:#FFFF00
fadeInTime:2
scaleFrom:6
scaleTo:4
alpha:1
drawUnderUnits:false
atmospheric:false
[effect_explosionblue_S]
life:30
priority:critical
alsoPlaySound:unit_explode:0.25
xOffsetRelative:0
yOffsetRelative:0
dirOffset:0
dirOffsetRandom:180
dirSpeedRandom:1
fadeInTime:0
fadeOut:true
attachedToUnit:false
scaleFrom:1.3
scaleTo:1.3
image:blue_explosion.png
total_frames:14
animateFrameStart:0
animateFrameEnd:13
animateFramePingPong:false
animateFrameSpeed:0.65
animateFrameSpeedRandom:0.1
alpha:1
[effect_explosionblue_M]
@copyFromSection:effect_explosionblue_S
scaleFrom:1.1
scaleTo:1.1
[effect_explosionblue_L]
@copyFromSection:effect_explosionblue_S
scaleFrom:2.2
scaleTo:2.2
[effect_EkMuzzleLarge]
life:30
showInFog:true
attachedToUnit:true
image:muzzle_large.png
total_frames:5
animateFrameStart:0
animateFrameEnd:4
animateFrameSpeed:0.4
scaleFrom:1.2
scaleTo:1.2
fadeOut:false
yOffsetRelative:17.5
[effect_showmaincannon]
priority:critical
image:lack.png
life:60
fadeOut:true
attachedToUnit:false
scaleFrom:5
scaleTo:1.1
alpha:1
drawUnderUnits:true
alwayStartDirAtZero:true
dirSpeed:4
[effect_blackSmoke1]
priority:veryhigh
image:blackSmoke1.png
life:240
lifeRandom:120
delayedStartTimer:60
delayedStartTimerRandom:60
fadeOut:true
attachedToUnit:false
color:#6D5448
fadeInTime:5
scaleFrom:0.2
scaleTo:2
alpha:2
drawUnderUnits:false
hSpeed:0.2
hOffsetRandom:0.15
atmospheric:true
dirOffsetRandom:180
xOffsetRelativeRandom:120
yOffsetRelativeRandom:120
xSpeedAbsoluteRandom:0.5
ySpeedAbsoluteRandom:0.5
[effect_blackSmoke2]
@copyFromSection:effect_blackSmoke1
delayedStartTimer:0
delayedStartTimerRandom:0
[effect_boom1]
life:136
image:explode.png
priority:critical
total_frames:10
animateFrameStart:0
animateFrameEnd:9
animateFrameSpeed:0.2
alwayStartDirAtZero:true
scaleFrom:4
scaleTo:4
[effect_crater]
priority:critical
image: FX_Crater2.png
createWhenOverLiquid: false
life: 600
fadeOut: true
scaleFrom: 3
scaleTo: 3
alpha: 1
drawUnderUnits:true
alwayStartDirAtZero:true
[effect_wave1]
priority:critical
image:bo.png
life:30
scaleFrom: 2
scaleTo:6
alpha:1
drawUnderUnits:true
alwayStartDirAtZero:true

[comment_tornado]
#[turret_Heavy duty laser]
invisible: true
canAttackLandUnits: true
x: -205
y: -212
turnSpeed:0
canAttackMaxAngle:181
delay:8s
projectile: Heavy duty laser
limitingRange:600
shoot_flame:custom:EkMuzzleLarge2
#[turret_Heavy duty laser gun 2]
copyFrom:tornado1
x: 205
y: -212
#[projectile_Heavy duty laser]
life: 10
targetSpeed:8
image:SHARED:blank.png
directDamage: 1800
areaDamage: 1400
areaRadius: 80
trailEffect: true
largeHitEffect: true
frame: 4
turnSpeed:4
drawSize:1.6
autoTargetingOnDeadTarget:true
autoTargetingOnDeadTargetRange:500
areaRadiusFromEdge:true
explodeOnEndOfLife:true
[effect_EkMuzzleLarge2]
life:30
showInFog:true
attachedToUnit:true
image:muzzle_large.png
total_frames:5
animateFrameStart:0
animateFrameEnd:4
animateFrameSpeed:0.4
scaleFrom:1.2
scaleTo:1.2
fadeOut:false
yOffsetRelative:11

[turret_mainturret1l]
x:0
y:0
image:mainturret1.png
delay:180
projectile:mainturret
shouldResetTurret:false
shoot_sound:cannon_firing
shoot_sound_vol:0.6
shoot_flame:NONE
canShoot:true
canAttackMaxAngle:30
turnSpeed:0
barrelX: ${graphics.imageScale*-88}
barrelY: ${graphics.imageScale*208}
attachedTo:mainturret2
#slave:true
recoilOffset: -15
recoilOutTime: 5
recoilReturnTime:30
aimOffsetSpread:0
limitingMinRange:500
[turret_mainturret1r]
@copyFromSection:turret_mainturret1l
x:0
y:0
image:none.png
barrelX: ${graphics.imageScale*88}

[turret_mainturret2]
x:0
y:0
image:mainturret2.png
canShoot:false
turnSpeed:0
limitingRange:500

[projectile_mainturret]
image:none.png
life: 600
areaDamage: 3400
areaRadius: 250
speed: 10
targetGround: true
areaHitAirAndLandAtSameTime:true
explodeEffect: custom:mainturreteffect_1,custom:projectileSound1,custom:maintboom
explodeEffectOnShield: custom:mainturreteffect_1,custom:projectileSound1,custom:maintboom
spawnProjectilesOnCreate:mainturret2
directDamage:3200
armourIgnoreAmount:60
areaRadiusFromEdge:true
[projectile_mainturret2]
image:none.png
life: 0
areaDamage: 3400
areaRadius: 250
explodeEffect:custom:showmainturret,custom:projectileSound1,custom:maintboom
explodeEffectOnShield:custom:showmainturret,custom:projectileSound1,custom:maintboom
targetGround: true
instant:true
armourIgnoreAmount:60
directDamage:3200
areaRadiusFromEdge:true
areaHitAirAndLandAtSameTime:true
[effect_showmainturret]
priority:critical
image:atta.png
life:60
fadeOut:true
attachedToUnit:false
scaleFrom:1.5
scaleTo:0.4
alpha:1
drawUnderUnits:true
alwayStartDirAtZero:true
dirSpeed:3

[effect_projectileSound1]
priority:critical
alsoPlaySound:boom.ogg:0.5
life:2

[effect_mainturreteffect_1]
priority:critical
image:bo.png
life:20
scaleFrom: 0
scaleTo:1.92
alpha:1
drawUnderUnits:true
alwayStartDirAtZero:true

[effect_maintboom]
life:150
image:boom3.png
priority:critical
total_frames:16
frame_width:64
frame_height:64
animateFrameStart:0
animateFrameEnd:15
animateFrameSpeed:0.3
alwayStartDirAtZero:true
scaleFrom:8
scaleTo:8


[effect_c_light]
createWhenZoomedOut: true
priority:critical
image: beam_flareb.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 4
scaleTo: 10
alpha: 2
drawUnderUnits:true
xOffsetRelative:0
yOffsetRelative:0
ySpeedAbsolute:60

[effect_c_smoke]
priority:critical
image:whitesmoke.png
life:120
lifeRandom:30
fadeOut:true
attachedToUnit:false
fadeInTime:5
scaleFrom:2
scaleTo:2
alpha:5
drawUnderUnits:false
atmospheric:true
dirOffsetRandom:180
xOffsetRelativeRandom:150
yOffsetRelativeRandom:500
xSpeedAbsoluteRandom:3
ySpeedAbsoluteRandom:3
ySpeedAbsolute:-5

[effect_c_fire]
priority:critical
image: flame.png
life:60
lifeRandom:120
fadeOut:true
attachedToUnit:false
fadeInTime:5
scaleFrom:10
scaleTo:20
alpha:3
drawUnderUnits:false
atmospheric:true
dirOffset:-90
xOffsetRelativeRandom:150
yOffsetRelativeRandom:500
xSpeedAbsoluteRandom:3
ySpeedAbsoluteRandom:3
ySpeedAbsolute:-5

[effect_c_wave1]
priority:critical
image:bo.png
life:120
scaleFrom: 0
scaleTo:24
alpha:1
drawUnderUnits:true
alwayStartDirAtZero:true
[effect_c_wave2]
@copyFromSection:effect_c_wave1
scaleFrom: -1
scaleTo:23
[effect_c_wave3]
@copyFromSection:effect_c_wave1
scaleFrom: -2
scaleTo:22
[effect_c_wave4]
@copyFromSection:effect_c_wave1
scaleFrom: -3
scaleTo:21
[effect_c_wave5]
@copyFromSection:effect_c_wave1
scaleFrom: -4
scaleTo:20

[movement]
movementType:AIR
moveSpeed:0.4
moveAccelerationSpeed:0.005
moveDecelerationSpeed:0.005
reverseSpeedPercentage:0.4
maxTurnSpeed:0.25
turnAcceleration:0.02
slowDeathFall:true
#heightChangeRate:0.3
startingHeightOffset:3000
targetHeight:100
[hiddenAction_created]
autoTriggerOnEvent:created
temporarilyAddTags:created
#sendMessageTo: self
#sendMessageWithTags:ce

[hiddenAction_createdeffect_1]
#autoTriggerOnEvent:newMessage(withTag='ce')
#requireConditional:if self.tags(includes='created') and self.height>110
autoTrigger:if self.tags(includes='created') and self.height>110
spawnEffects:custom:c_light,custom:c_fire*2,custom:c_smoke*2
#sendMessageTo:self
#sendMessageWithTags:ce

[hiddenAction_createdeffect_2]
#autoTriggerOnEvent:newMessage(withTag='ce')
autoTrigger:if self.tags(includes='created') and self.height<=120
spawnEffects:custom:c_wave1,custom:c_wave2,custom:c_wave3,custom:c_wave4,custom:c_wave5
temporarilyRemoveTags:created