[action_deadDebug]
autoTrigger:if numberOfUnitsInEnemyTeam(withTag='EkGorgonLaserActing',lessThan=1,withinRange=1000) or self.timeAlive(laterThanSeconds=3.5)
isVisible:false
deleteSelf:true
showMessageToPlayer:114514


[core]

showInEditor:false
@memory dir:number
name:Ek_beamgunshiplaser
price:0
maxHp:10000
mass:1
#showInEditor:false
displayText:激光重修
displayDescription:百夫长激光特效
techLevel:1
buildSpeed:0.005
createNeutral:true
stayNeutral:true
hideScorchMark:true
showOnMinimap:false
createOnAggressiveTeam:true
disableAllUnitCollisions:true
canNotBeDirectlyAttacked:true
canNotBeDamaged:true
explodeOnDeath:false
radius:-1
displayRadius:-1
softCollisionOnAll:99
autoTriggerCooldownTime:6
isUnselectable:true
tags: EkLaserG

[hiddenAction_0]
autoTriggerOnEvent:created
setUnitMemory:dir=self.customTarget1.dir()
addWaypoint_type:touchTarget
addWaypoint_target_fromReference:self.customTarget1
alsoTriggerAction:2

[hiddenAction_2]
autoTrigger:true
spawnEffects:CUSTOM:scorchMark,CUSTOM:hit,CUSTOM:hit2,CUSTOM:explosionMain2,CUSTOM:explosionMain,CUSTOM:Trail, CUSTOM:smoke*5, CUSTOM:boomwater
fireTurretXAtGround:1
fireTurretXAtGround_withTarget:self.getOffsetAbsolute(x=self.customTarget1.x-self.x,y=self.customTarget1.y-self.y+self.customTarget1.height)
alsoTriggerAction:2A

[hiddenAction_2A]
fireTurretXAtGround:2


[graphics]
image:SHARED:blank.png

[attack]
canAttack:true
canAttackFlyingUnits:true
canAttackLandUnits:true
canAttackUnderwaterUnits:false
canOnlyAttackUnitsWithTags:Ek_beamGunship_base
turretSize:1
turretTurnSpeed:99
maxAttackRange:114514
shootDelay:4
aimOffsetSpread:0

[turret_1]
x:0
y:0
projectile:1
aimOffsetSpread:0
[turret_2]
x:0
y:0
canShoot:false
projectile:2
aimOffsetSpread:0
[projectile_1]
directDamage:0
life:10
speed:10
instant:true
moveWithParent:true
beamImage:beam.png
beamImageEnd:end.png
beamImageStart:start.png
beamImageOffsetRate:3
laserEffect:true
instantReuseLast:true
color:#dd99bcf2
explodeEffect:CUSTOM:HitLight
drawUnderUnits:false
targetGroundSpread:0
explodeOnEndOfLife:true


[projectile_2]
life:1
largeHitEffect:false
speed:99
image:SHARED:blank.png
areaDamage:500
areaRadius:100
areaHitAirAndLandAtSameTime:true
areaHitUnderwaterAlways:true
explodeOnEndOfLife:true
hitSound:false
explodeEffect:NONE
targetGroundSpread:0


[effect_HitLight]
priority:critical
image:fire0.png
life:30
fadeOut:true
attachedToUnit:false
color:#dd99bcf2
scaleFrom:0.5
scaleTo:0.5
alpha:0.3
drawUnderUnits:false

[effect_boomwater]
priority:critical
image:boomwater.png
life:15
scaleFrom: 0
scaleTo:3
alpha:1
drawUnderUnits:true
alwayStartDirAtZero:true
createWhenOverLand:false
createWhenOverLiquid:true

[effect_scorchMark]
priority:critical
image:scorchmark.png
life:100
fadeOut:true
dirOffsetRandom:180
attachedToUnit:false
color:#ffffff
fadeInTime:10
scaleFrom:0.5
scaleTo:0.5
alpha:2.8
createWhenOverLiquid:false
drawUnderUnits:true
[effect_explosionMain]
life:25
priority:critical
xOffsetRelative:0
yOffsetRelative:0
dirOffset:0
dirOffsetRandom:180
dirSpeedRandom:1
fadeInTime:0
fadeOut:true
attachedToUnit:false
scaleFrom:1.1
scaleTo:2.2
color:#dd99bcf2
image:boom2.png
total_frames:25
animateFrameStart:0
animateFrameEnd:24
animateFramePingPong:false
animateFrameSpeed:1.6
animateFrameSpeedRandom:0.2
alpha:2.8
[effect_explosionMain2]
life:20
priority:critical
xOffsetRelative:0
yOffsetRelative:0
dirOffset:0
dirOffsetRandom:180
dirSpeedRandom:1
fadeInTime:0
fadeOut:true
ySpeedRelative:1
attachedToUnit:false
scaleFrom:0.9
scaleTo:1.9
color:#dd99bcf2
image:boom2.png
total_frames:25
animateFrameStart:0
animateFrameEnd:24
animateFramePingPong:false
animateFrameSpeed:1.8
animateFrameSpeedRandom:0.1
alpha:2.1
[effect_hit]
createWhenOverLiquid:false
priority:critical
image:hit_light.png
life:90
fadeOut:true
attachedToUnit:false
color:#ffff00
scaleFrom:0.5
scaleTo:0.5
alpha:0.8
drawUnderUnits:false
[effect_hit2]
createWhenOverLand:false
priority:critical
image:hit_light.png
life:60
fadeOut:true
attachedToUnit:false
color:#ffff00
scaleFrom:0.5
scaleTo:0.5
alpha:0.6
drawUnderUnits:false
[effect_Trail]
createWhenOverLand:false
priority:critical
stripIndex:effects
frameIndex:0
life:20
fadeOut:true
attachedToUnit:false
color:#FFC2E5E5
fadeInTime:5
scaleFrom:0.3
scaleTo:1.2
alpha:0.7
drawUnderUnits:false
atmospheric:true
hSpeed:1
hOffsetRandom:0.75
dirOffsetRandom:180
xSpeedAbsoluteRandom:0.2
ySpeedAbsoluteRandom:0.2
[effect_smoke]
priority:critical
image:smoke59.png
life:120
lifeRandom:60
fadeOut:true
attachedToUnit:false
color:#6D5448
fadeInTime:5
scaleFrom:0.2
scaleTo:2
alpha:2
drawUnderUnits:false
hSpeed:0.2
hOffsetRandom:0.15
atmospheric:true
dirOffsetRandom:180
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5
xSpeedAbsoluteRandom:1
ySpeedAbsoluteRandom:1

[movement]
movementType:AIR
moveSpeed:-5
moveAccelerationSpeed:0.2
moveDecelerationSpeed:5
targetHeight:1
targetHeightDrift:0
landOnGround:false
maxTurnSpeed:99
turnAcceleration:99
moveSlidingMode:false
moveIgnoringBody:true
moveSlidingDir:181